using System.Linq;
using System.Numerics;
using Content.Shared.AU14.AllianceConsole;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.AU14.AllianceConsole;

[GenerateTypedNameReferences]
public sealed partial class AllianceConsoleWindow : DefaultWindow
{
    public event Action<string, AllianceStatus>? OnSetStatus;

    private readonly Dictionary<string, OptionButton> _factionButtons = new();

    public AllianceConsoleWindow()
    {
        RobustXamlLoader.Load(this);
    }

    public void UpdateState(AllianceConsoleBuiState state)
    {
        FactionLabel.Text = $"Alliance Console — {state.Faction.ToUpperInvariant()}";

        // Rebuild faction list if the set of factions changed.
        var existing = _factionButtons.Keys.ToHashSet();
        var incoming = state.ControllableFactions.ToHashSet();
        if (!existing.SetEquals(incoming))
        {
            FactionList.RemoveAllChildren();
            _factionButtons.Clear();

            foreach (var faction in state.ControllableFactions.OrderBy(f => f))
            {
                var row = new BoxContainer { Orientation = BoxContainer.LayoutOrientation.Horizontal, SeparationOverride = 6 };

                var displayName = AllianceConsoleComponent.FactionDisplayNames.TryGetValue(faction, out var name) ? name : faction;
                var label = new Label { Text = displayName, HorizontalExpand = true, MinSize = new Vector2(160, 0) };
                row.AddChild(label);

                var btn = new OptionButton { MinSize = new Vector2(130, 0) };
                btn.AddItem("Neutral", (int)AllianceStatus.Neutral);
                btn.AddItem("Friendly", (int)AllianceStatus.Friendly);
                btn.AddItem("Hostile",  (int)AllianceStatus.Hostile);

                var capturedFaction = faction;
                btn.OnItemSelected += args =>
                {
                    btn.SelectId(args.Id);
                    OnSetStatus?.Invoke(capturedFaction, (AllianceStatus)args.Id);
                };

                row.AddChild(btn);
                FactionList.AddChild(row);
                _factionButtons[faction] = btn;
            }
        }

        // Sync button selections to current state.
        foreach (var (faction, btn) in _factionButtons)
        {
            var status = state.FactionStatuses.TryGetValue(faction, out var s) ? s : AllianceStatus.Neutral;
            btn.SelectId((int)status);
        }
    }
}
