using System;
using Content.Client.Lobby.UI;
using Content.Client.Stylesheets;
using Content.Shared.CCVar;
using Content.Shared.Ghost;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Configuration;
using Robust.Shared.Maths;
using Robust.Shared.Timing;
using Robust.Shared.Utility;

namespace Content.Client.Voting.UI
{
    [GenerateTypedNameReferences]
    public sealed partial class VotePopup : Control
    {
        [Dependency] private IGameTiming _gameTiming = default!;
        [Dependency] private IVoteManager _voteManager = default!;
        [Dependency] private IEntityNetworkManager _net = default!;
        [Dependency] private IConfigurationManager _cfg = default!;
        [Dependency] private IStylesheetManager _stylesheetManager = default!;

        private readonly VoteManager.ActiveVote _vote;
        private readonly Button[] _voteButtons;
        private readonly NetEntity? _targetEntity;
        private int _optionColumns = -1;
        private int _optionMinWidth = -1;
        private int _optionMinHeight = -1;

        private const int CompactOptionMinWidth = 220;
        private const int WideOptionMinWidth = 400;
        private const int SingleOptionMinWidth = 560;
        private const int OptionMinHeight = 30;
        private const int TallOptionMinHeight = 44;
        private const int WideOptionTextLength = 24;
        private const int VeryWideOptionTextLength = 42;
        private const int TallOptionTextLength = 32;

        public VotePopup(VoteManager.ActiveVote vote)
        {
            _vote = vote;
            IoCManager.InjectDependencies(this);
            RobustXamlLoader.Load(this);

            ApplyCrtPalette();
            CrtLobbyTheme.Apply(this);
            _cfg.OnValueChanged(CCVars.CrtUiEnabled, OnCrtUiEnabledChanged);
            _cfg.OnValueChanged(CCVars.CrtUiColor, OnCrtUiColorChanged);

            if (_vote.TargetEntity != null && _vote.TargetEntity != 0)
            {
                _targetEntity = new NetEntity(_vote.TargetEntity.Value);
                FollowVoteTarget.Visible = true;
                FollowVoteTarget.OnPressed += _ => AttemptFollowVoteEntity();
            }

            Modulate = Color.White.WithAlpha(0.96f);
            _voteButtons = new Button[vote.Entries.Length];
            var group = new ButtonGroup();

            for (var i = 0; i < _voteButtons.Length; i++)
            {
                var button = new Button
                {
                    ToggleMode = true,
                    Group = group,
                    HorizontalExpand = true,
                    MinHeight = OptionMinHeight,
                    ClipText = false,
                    RectClipContent = false,
                    TextAlign = Label.AlignMode.Center,
                    StyleClasses = { StyleNano.StyleClassCrtButton }
                };
                button.Label.AddStyleClass(StyleNano.StyleClassCrtButtonLabel);
                button.Label.HorizontalExpand = true;
                button.Label.VAlign = Label.VAlignMode.Center;
                _voteButtons[i] = button;
                VoteOptionsContainer.AddChild(button);
                var i1 = i;
                button.OnPressed += _ => _voteManager.SendCastVote(vote.Id, i1);
            }

            ReflowOptions(GetRawOptionTexts());
        }

        [Obsolete("Controls should only be removed from UI tree instead of being disposed")]
        protected override void Dispose(bool disposing)
        {
            base.Dispose(disposing);

            _cfg.UnsubValueChanged(CCVars.CrtUiEnabled, OnCrtUiEnabledChanged);
            _cfg.UnsubValueChanged(CCVars.CrtUiColor, OnCrtUiColorChanged);
        }

        private void OnCrtUiEnabledChanged(bool _)
        {
            ApplyCrtPalette();
            CrtLobbyTheme.Apply(this);
        }

        private void OnCrtUiColorChanged(string _)
        {
            ApplyCrtPalette();
            CrtLobbyTheme.Apply(this);
        }

        private void ApplyCrtPalette()
        {
            Stylesheet = _stylesheetManager.SheetNano;
            VotePanel.PanelOverride = CreateVotePanelStyleBox();
        }

        private static CrtStyleBox CreateVotePanelStyleBox()
        {
            return new CrtStyleBox
            {
                BackgroundColor = StyleNano.CrtPanelBackground,
                BorderColor = StyleNano.CrtGreenDim,
                CornerColor = StyleNano.CrtGreen.WithAlpha(0.28f),
                ScanlineColor = StyleNano.CrtGreen.WithAlpha(0.016f),
                GridColor = StyleNano.CrtGreen.WithAlpha(0.01f),
                NoiseColor = StyleNano.CrtGreenSoft.WithAlpha(0.045f),
                PixelationColor = StyleNano.CrtGreen.WithAlpha(0.035f),
                PixelationShadowColor = StyleNano.CrtBackground.WithAlpha(0.16f),
                BorderThickness = new Thickness(1),
                DrawPixelation = true,
                CornerLength = 10,
                PixelationBlockSize = 3,
                PixelationSpacing = 150,
                PixelationChance = 12,
                PixelationClusterSize = 2,
                PixelationSeed = 61,
                NoiseSpacing = 10,
                NoiseChance = 9,
                NoiseSeed = 11,
                ContentMarginLeftOverride = 10,
                ContentMarginRightOverride = 10,
                ContentMarginTopOverride = 8,
                ContentMarginBottomOverride = 8
            };
        }

        public void UpdateData()
        {
            VoteTitle.SetMessage(FormattedMessage.FromUnformatted(_vote.Title));
            VoteCaller.Text = Loc.GetString("ui-vote-created", ("initiator", _vote.Initiator));

            var buttonTexts = new string[_voteButtons.Length];

            for (var i = 0; i < _voteButtons.Length; i++)
            {
                var entry = _vote.Entries[i];
                string buttonText;
                if (_vote.DisplayVotes)
                {
                    buttonText = Loc.GetString("ui-vote-button", ("text", entry.Text), ("votes", entry.Votes));
                }
                else
                {
                    buttonText = Loc.GetString("ui-vote-button-no-votes", ("text", entry.Text));
                }

                buttonTexts[i] = buttonText;
                _voteButtons[i].Text = buttonText;
                _voteButtons[i].ToolTip = buttonText;

                if (_vote.OurVote == i)
                    _voteButtons[i].Pressed = true;
            }

            ReflowOptions(buttonTexts);
        }

        private string[] GetRawOptionTexts()
        {
            var texts = new string[_vote.Entries.Length];
            for (var i = 0; i < _vote.Entries.Length; i++)
            {
                texts[i] = _vote.Entries[i].Text;
            }

            return texts;
        }

        private void ReflowOptions(string[] texts)
        {
            if (texts.Length == 0)
                return;

            var longest = GetLongestTextLine(texts);
            var columns = GetOptionColumns(texts.Length, longest);
            var minWidth = GetOptionMinWidth(columns, longest);
            var minHeight = longest > TallOptionTextLength ? TallOptionMinHeight : OptionMinHeight;

            if (_optionColumns == columns &&
                _optionMinWidth == minWidth &&
                _optionMinHeight == minHeight)
            {
                return;
            }

            _optionColumns = columns;
            _optionMinWidth = minWidth;
            _optionMinHeight = minHeight;

            VoteOptionsContainer.Columns = columns;

            foreach (var button in _voteButtons)
            {
                button.MinWidth = minWidth;
                button.MinHeight = minHeight;
                button.ClipText = false;
                button.RectClipContent = false;
            }
        }

        private static int GetOptionColumns(int optionCount, int longestText)
        {
            if (optionCount <= 0)
                return 1;

            if (optionCount <= 1)
                return 1;

            if (longestText > VeryWideOptionTextLength)
                return 1;

            if (longestText > WideOptionTextLength)
                return 2;

            return Math.Min(3, optionCount);
        }

        private static int GetOptionMinWidth(int columns, int longestText)
        {
            if (columns == 1)
                return Math.Max(SingleOptionMinWidth, 12 * longestText);

            if (longestText > WideOptionTextLength)
                return Math.Max(WideOptionMinWidth, 10 * longestText);

            return CompactOptionMinWidth;
        }

        private static int GetLongestTextLine(string[] texts)
        {
            var longest = 0;
            foreach (var text in texts)
            {
                var lineStart = 0;
                for (var i = 0; i <= text.Length; i++)
                {
                    if (i != text.Length && text[i] != '\n')
                        continue;

                    longest = Math.Max(longest, i - lineStart);
                    lineStart = i + 1;
                }
            }

            return longest;
        }

        private void AttemptFollowVoteEntity()
        {
            if (_targetEntity != null)
            {
                var msg = new GhostWarpToTargetRequestEvent(_targetEntity.Value);
                _net.SendSystemNetworkMessage(msg);
            }
        }

        protected override void FrameUpdate(FrameEventArgs args)
        {
            // Logger.GetSawmill("content").Debug($"{_gameTiming.ServerTime}, {_vote.StartTime}, {_vote.EndTime}");

            var curTime = _gameTiming.RealTime;
            var timeLeft = _vote.EndTime - curTime;
            if (timeLeft < TimeSpan.Zero)
                timeLeft = TimeSpan.Zero;

            // Round up a second.
            timeLeft = TimeSpan.FromSeconds(Math.Ceiling(timeLeft.TotalSeconds));

            TimeLeftBar.Value = Math.Min(1, (float) ((curTime.TotalSeconds - _vote.StartTime.TotalSeconds) /
                                                     (_vote.EndTime.TotalSeconds - _vote.StartTime.TotalSeconds)));

            TimeLeftText.Text = $"{timeLeft:m\\:ss}";
        }
    }
}
