- type: job
  parent: AU14JobWorkingJoeBase
  id: AU14JobHazmatWorkingJoe
  whitelisted: true
  whitelistParent: RMCWhitelistMedium
  requirements:
  - !type:TraitsRequirement
    inverted: true
    traits:
    - SocialAnxietyHeavy
    - FrontalLisp
    - NonResuscitable
    - Epilepsy
  icon: "AU14JobIconColonyWorkingJoe"
  spawnMenuRoleName: Working Joe (Hazmat)
  supervisors: au14-job-supervisors-workingjoe-colony
  usePlayerProfile: false
  hasIcon: false
  accessGroups:
  - auadmin
  - Colonist
  - AUPrisonStaff
  - auwy
  special:
  - !type:AddComponentSpecial
    components:
    - type: IntrinsicRadioTransmitter
      channels:
      - radioAI
      - Colony
      - radioWEYU
      - radioCMB
    - type: ActiveRadio
      channels:
      - radioAI
      - Colony
      - radioWEYU
      - radioCMB
    - type: Access
      groups:
      - auadmin
      - Colonist
      - AUPrisonStaff
      - auwy
    - type: Loadout
      prototypes: [ AU14GearHazmatWorkingJoe ]
  dummyStartingGear: AU14GearHazmatWorkingJoe
  hidden: false

- type: startingGear
  id: AU14GearHazmatWorkingJoe
  equipment:
    id: AU14IDCardColonyWorkingJoe
    ears: AU14HeadsetWorkingJoe
    shoes: AU14BootsCBRN
    gloves: RMCHandsVeteranCBRN
    jumpsuit: AU14JoeHazmat
    belt: CMBeltUtilityFilled
    back: AU14IMPBackpackMarine
    pocket2: RMCPouchConstructionFillFull
  storage:
      belt:
      - AU14MaintenanceJack
      - RMCSynthResetKeySeegson
      back:
      - AU14SprayCleanerExperimental
      - RMCBucketJanitorial
      - CMMop
      - CMWetSign
      - RMCLightReplacer
      - AU14StampJoe
  inhand:
  - CMFireExtinguisher

- type: entity
  parent: CMSpawnPointJobBase
  id: AU14SpawnPointHazmatWorkingJoe
  name: Spawn Point Working Joe (Hazmat)
  components:
  - type: SpawnPoint
    job_id: AU14JobHazmatWorkingJoe
  - type: Sprite
    state: syn_spawn
