ent-ClothingOuterSuitBomb-name = bomb suit
ent-ClothingOuterSuitBomb-desc = A heavy suit designed to withstand the pressure generated by a bomb and any fragments the bomb may produce.

ent-ClothingOuterSuitJanitorBomb-name = janitorial bomb suit
ent-ClothingOuterSuitJanitorBomb-desc = Heavy body armor designed to withstand explosions formed from reactions between chemicals.

ent-ClothingOuterSuitFire-name = fire suit
ent-ClothingOuterSuitFire-desc = A suit that helps protect against hazardous temperatures.

ent-ClothingOuterSuitAtmosFire-name = atmos fire suit
ent-ClothingOuterSuitAtmosFire-desc = An expensive firesuit that protects against even the most deadly of station fires. Designed to protect even if the wearer is set aflame.

ent-ClothingOuterSuitRad-name = radiation suit
ent-ClothingOuterSuitRad-desc = A suit that protects against radiation. The label reads, 'Made with lead. Please do not consume insulation.'

ent-ClothingOuterSuitSpaceNinja-name = space ninja suit
ent-ClothingOuterSuitSpaceNinja-desc = This black technologically advanced, cybernetically-enhanced suit provides many abilities like invisibility or teleportation.

ent-ClothingOuterSuitChicken-name = chicken suit
ent-ClothingOuterSuitChicken-desc = Bok bok bok!

ent-ClothingOuterSuitShrineMaiden-name = shrine maiden outfit
ent-ClothingOuterSuitShrineMaiden-desc = Makes you want to go deal with some troublesome youkai.

ent-ClothingOuterSuitWitchRobes-name = witch robes
ent-ClothingOuterSuitWitchRobes-desc = Magic is all about the spell power, ZE!

ent-ClothingOuterSuitMonkey-name = monkey suit
ent-ClothingOuterSuitMonkey-desc = A suit that looks like a primate.

ent-ClothingOuterSuitIan-name = ian suit
ent-ClothingOuterSuitIan-desc = Who's a good boy?

ent-ClothingOuterSuitCarp-name = carp suit
ent-ClothingOuterSuitCarp-desc = A special suit that makes you look just like a space carp, if your eyesight is bad.

ent-ClothingOuterHardsuitCarp-name = carp suit
ent-ClothingOuterHardsuitCarp-desc = A special suit that makes you look just like a space carp, if your eyesight is bad.

