using Content.Shared.AU14.Objectives;
using Content.Client.UserInterface.Controls;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using System;

namespace Content.Client.AU14.Objectives;

[GenerateTypedNameReferences]
public sealed partial class ObjectivesConsoleWindow : FancyWindow
{
    public Action<string>? RequestIntelCallback;

    public ObjectivesConsoleWindow()
    {
        RobustXamlLoader.Load(this);
        CloseButton.OnPressed += _ => Close();
    }

    public void UpdateObjectives(List<ObjectiveEntry> objectives, int currentWinPoints, int requiredWinPoints)
    {
        CurrentWinPointsLabel.Text = Loc.GetString("au14-objectives-console-current-win-points", ("points", currentWinPoints)); // RuMC edit
        RequiredWinPointsLabel.Text = Loc.GetString("au14-objectives-console-points-to-final", ("points", requiredWinPoints)); // RuMC edit
        ObjectivesList.DisposeAllChildren();
        foreach (var obj in objectives)
        {
            var container = new BoxContainer { Orientation = BoxContainer.LayoutOrientation.Horizontal };
            string typeText = obj.Type switch
            {
                // RuMC edit start
                ObjectiveTypeDisplay.Minor => Loc.GetString("au14-objectives-type-minor") + " ",
                ObjectiveTypeDisplay.Major => Loc.GetString("au14-objectives-type-major") + " ",
                ObjectiveTypeDisplay.Win => Loc.GetString("au14-objectives-type-win") + " ",
                // RuMC edit end
                _ => ""
            };
            var labelText = typeText + obj.Description;
            if (obj.Repeating)
                labelText += " " + Loc.GetString("au14-objectives-repeating"); // RuMC edit
            if (!string.IsNullOrEmpty(obj.Progress))
                labelText += $" ({obj.Progress})";
            if (obj.MaxRepeatable is { } maxRepeat && maxRepeat > 0)
            {
                if (obj.RepeatsCompleted is int repeats)
                    labelText += " " + Loc.GetString("au14-objectives-completed-times", ("current", repeats), ("max", maxRepeat)); // RuMC edit
                else
                    labelText += " " + Loc.GetString("au14-objectives-can-complete-times", ("max", maxRepeat)); // RuMC edit
            }
            else if (obj.RepeatsCompleted is int repeats && repeats > 0)
            {
                labelText += " " + Loc.GetString("au14-objectives-times-completed", ("count", repeats)); // RuMC edit
            }
            if (obj.Points > 0)
                labelText += " " + Loc.GetString("au14-objectives-worth-points", ("points", obj.Points)); // RuMC edit
            var label = new Label { Text = labelText };
            // Add Intel button
            var intelButton = new Button { Text = "Intel", Margin = new Thickness(8, 0, 0, 0) };
            intelButton.OnPressed += _ =>
            {
                RequestIntelCallback?.Invoke(obj.Id);
            };

            string statusText;
            Color statusColor;
            switch (obj.Status)
            {
                case ObjectiveStatusDisplay.Completed:
                    statusText = Loc.GetString("au14-objectives-status-completed"); // RuMC edit
                    statusColor = Color.Lime;
                    break;
                case ObjectiveStatusDisplay.Failed:
                    statusText = Loc.GetString("au14-objectives-status-failed"); // RuMC edit
                    statusColor = Color.Red;
                    break;
                case ObjectiveStatusDisplay.Captured:
                    statusText = Loc.GetString("au14-objectives-status-captured"); // RuMC edit
                    statusColor = Color.Cyan;
                    break;
                case ObjectiveStatusDisplay.Uncaptured:
                    statusText = Loc.GetString("au14-objectives-status-uncaptured"); // RuMC edit
                    statusColor = Color.Orange;
                    break;
                default:
                    statusText = Loc.GetString("au14-objectives-status-uncompleted"); // RuMC edit
                    statusColor = Color.Gold;
                break;
            }
            var status = new Label
            {
                Text = statusText,
                Modulate = statusColor,
                HorizontalAlignment = HAlignment.Right,
                Margin = new Thickness(8, 0, 0, 0)
            };
            container.AddChild(label);
            container.AddChild(intelButton);
            container.AddChild(status);
            ObjectivesList.AddChild(container);
        }
    }
}
