using Content.Shared.AU14.ColonyEconomy;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.AU14.ColonyEconomy;

[GenerateTypedNameReferences]
public sealed partial class CorporateConsoleWindow : DefaultWindow
{
    public CorporateConsoleWindow()
    {
        RobustXamlLoader.Load(this);

        // RuMC edit start
        Title = Loc.GetString("corporate-console-title");
        WithdrawCashLabel.Text = Loc.GetString("corporate-console-withdraw-section");
        Withdraw100.Text = "$100";
        Withdraw250.Text = "$250";
        Withdraw500.Text = "$500";
        TransitTariffSectionLabel.Text = Loc.GetString("corporate-console-tariff-section");
        TariffDescLabel.Text = Loc.GetString("corporate-console-tariff-desc");
        TariffInputLabel.Text = Loc.GetString("corporate-console-tariff-input");
        TariffInput.PlaceHolder = Loc.GetString("corporate-console-tariff-placeholder");
        SetTariffButton.Text = Loc.GetString("corporate-console-tariff-apply");
        EconomyOverviewLabel.Text = Loc.GetString("corporate-console-economy-section");
        ThirdPartySectionLabel.Text = Loc.GetString("corporate-console-third-party-section");
        OpenThirdPartyBtn.Text = Loc.GetString("corporate-console-open-third-party");
        // RuMC edit end
    }

    public void UpdateState(CorporateConsoleBuiState state)
    {
        CorporateBudgetLabel.Text = Loc.GetString("corporate-console-budget", ("amount", state.CorporateBudget));
        CurrentTariffLabel.Text = Loc.GetString("corporate-console-current-tariff", ("tariff", state.TransitTariffPercent));
        TariffInput.Text = $"{state.TransitTariffPercent:F0}";

        var incomeTax = state.EconomyStatus.IncomeTaxPercent;
        WithdrawTaxNote.Text = incomeTax > 0
            ? Loc.GetString("corporate-console-withdraw-tax", ("tax", incomeTax))
            : Loc.GetString("corporate-console-withdraw-no-tax");

        UpdateEconomyStatus(state.EconomyStatus);
    }

    private void UpdateEconomyStatus(EconomyStatusState econ)
    {
        EconomyStatusPanel.RemoveAllChildren();
        EconomyStatusPanel.AddChild(new Label { Text = Loc.GetString("corporate-console-sales-tax", ("tax", econ.SalesTaxPercent)) });
        EconomyStatusPanel.AddChild(new Label { Text = Loc.GetString("corporate-console-income-tax", ("tax", econ.IncomeTaxPercent)) });
        EconomyStatusPanel.AddChild(new Label { Text = Loc.GetString("corporate-console-transit-tariff", ("tariff", econ.TransitTariffPercent)) });

        if (econ.ActiveEmbargoes.Count > 0)
            EconomyStatusPanel.AddChild(new Label
            {
                Text = Loc.GetString("corporate-console-active-embargoes", ("list", string.Join(", ", econ.ActiveEmbargoes))),
                StyleClasses = { "Caution" }
            });
        else
            EconomyStatusPanel.AddChild(new Label
            {
                Text = Loc.GetString("corporate-console-no-embargoes"),
                StyleClasses = { "LabelSubText" }
            });

        if (econ.ActiveTradePacts.Count > 0)
            EconomyStatusPanel.AddChild(new Label { Text = Loc.GetString("corporate-console-active-trade-pacts", ("list", string.Join(", ", econ.ActiveTradePacts))) });
        else
            EconomyStatusPanel.AddChild(new Label
            {
                Text = Loc.GetString("corporate-console-no-trade-pacts"),
                StyleClasses = { "LabelSubText" }
            });
    }
}
