using Content.Shared.AU14.ColonyEconomy;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Localization;

namespace Content.Client.AU14.ColonyEconomy;

[GenerateTypedNameReferences]
public sealed partial class DepartmentConsoleWindow : DefaultWindow
{
    public event Action<NetEntity>? OnFirePressed;
    public event Action<NetEntity, int>? OnSetIndividualSalaryPressed;
    public event Action<NetEntity>? OnRemoveOverridePressed;
    public event Action<int, int, string, string>? OnOrderPressed;

    public DepartmentConsoleWindow()
    {
        RobustXamlLoader.Load(this);

        Title = Loc.GetString("department-console-title");
        TabContainer.SetTabTitle(ManagementTab, Loc.GetString("department-console-tab-management"));
        TabContainer.SetTabTitle(OrdersTab, Loc.GetString("department-console-tab-orders"));

        // Static labels
        WithdrawLabel.Text = Loc.GetString("department-console-withdraw-label");
        DefaultSalaryLabel.Text = Loc.GetString("department-console-default-salary-label");
        HireHintLabel.Text = Loc.GetString("department-console-hire-hint");
        EmployeesLabel.Text = Loc.GetString("department-console-employees-label");
        AnnouncementLabel.Text = Loc.GetString("department-console-announcement-label");
        ReasonLabel.Text = Loc.GetString("department-console-reason-label");
        DeliverLabel.Text = Loc.GetString("department-console-deliver-label");
        CategoriesLabel.Text = Loc.GetString("department-console-categories-label");

        // Buttons
        WithdrawButton.Text = Loc.GetString("department-console-withdraw-btn");
        SetDefaultSalaryButton.Text = Loc.GetString("department-console-default-salary-btn");
        SendAnnouncementButton.Text = Loc.GetString("department-console-send-btn");

        // PlaceHolders
        WithdrawAmountInput.PlaceHolder = Loc.GetString("department-console-withdraw-placeholder");
        AnnouncementInput.PlaceHolder = Loc.GetString("department-console-announcement-placeholder");
        OrderReasonInput.PlaceHolder = Loc.GetString("department-console-reason-placeholder");
        OrderDeliverToInput.PlaceHolder = Loc.GetString("department-console-deliver-placeholder");
    }

    public void UpdateState(DepartmentConsoleBuiState state)
    {
        DeptNameLabel.Text = state.DepartmentName;
        DeptBudgetLabel.Text = Loc.GetString("department-console-budget", ("amount", $"{state.DepartmentBudget:F0}"));
        OrdersBudgetLabel.Text = Loc.GetString("department-console-budget", ("amount", $"{state.DepartmentBudget:F0}"));
        DefaultSalaryInput.Text = state.DefaultSalary.ToString();

        // Rebuild employee list
        EmployeeList.RemoveAllChildren();

        foreach (var emp in state.Employees)
        {
            var row = new BoxContainer
            {
                Orientation = BoxContainer.LayoutOrientation.Horizontal,
                SeparationOverride = 4
            };

            var nameLabel = new Label
            {
                Text = emp.Name,
                HorizontalExpand = true,
                SizeFlagsStretchRatio = 2
            };

            var jobLabel = new Label
            {
                Text = emp.JobTitle,
                HorizontalExpand = true,
                SizeFlagsStretchRatio = 1
            };

            var salaryLabel = new Label
            {
                Text = emp.HasOverride
                    ? Loc.GetString("department-console-salary-display", ("amount", emp.Salary))
                    : Loc.GetString("department-console-salary-display-default", ("amount", emp.Salary)),
                HorizontalExpand = true,
                SizeFlagsStretchRatio = 1
            };

            var salaryInput = new LineEdit
            {
                PlaceHolder = Loc.GetString("department-console-salary-placeholder"),
                HorizontalExpand = true,
                SizeFlagsStretchRatio = 1
            };

            var setSalaryBtn = new Button { Text = Loc.GetString("department-console-btn-set") };
            var idCopy = emp.IdCardUid;
            setSalaryBtn.OnPressed += _ =>
            {
                if (salaryInput.Text is { } text && int.TryParse(text, out var salary))
                    OnSetIndividualSalaryPressed?.Invoke(idCopy, salary);
            };

            var resetBtn = new Button { Text = Loc.GetString("department-console-btn-reset") };
            resetBtn.OnPressed += _ => OnRemoveOverridePressed?.Invoke(idCopy);

            var fireBtn = new Button { Text = Loc.GetString("department-console-btn-fire") };
            fireBtn.OnPressed += _ => OnFirePressed?.Invoke(idCopy);

            row.AddChild(nameLabel);
            row.AddChild(jobLabel);
            row.AddChild(salaryLabel);
            row.AddChild(salaryInput);
            row.AddChild(setSalaryBtn);
            row.AddChild(resetBtn);
            row.AddChild(fireBtn);

            EmployeeList.AddChild(row);
        }

        if (state.Employees.Count == 0)
            EmployeeList.AddChild(new Label { Text = Loc.GetString("department-console-no-employees") });

        // Rebuild order catalog categories
        OrderCategoryList.RemoveAllChildren();
        OrderItemList.RemoveAllChildren();
        SelectedCategoryLabel.Text = Loc.GetString("department-console-select-category");

        for (var catIdx = 0; catIdx < state.Catalog.Count; catIdx++)
        {
            var cat = state.Catalog[catIdx];
            var catBtn = new Button { Text = cat.Name };
            var catCopy = cat;
            catBtn.OnPressed += _ => ShowCategory(catCopy);
            OrderCategoryList.AddChild(catBtn);
        }

        if (state.Catalog.Count == 0)
            OrderCategoryList.AddChild(new Label { Text = Loc.GetString("department-console-no-catalog") });
    }

    private void ShowCategory(DepartmentOrderCatalogCategory category)
    {
        OrderItemList.RemoveAllChildren();
        SelectedCategoryLabel.Text = Loc.GetString("department-console-category-selected", ("name", category.Name));

        foreach (var entry in category.Entries)
        {
            var row = new BoxContainer
            {
                Orientation = BoxContainer.LayoutOrientation.Horizontal,
                SeparationOverride = 4
            };

            var nameLabel = new Label
            {
                Text = entry.Name,
                HorizontalExpand = true,
                SizeFlagsStretchRatio = 3
            };

            var costLabel = new Label
            {
                Text = $"${entry.Cost}",
                HorizontalExpand = true,
                SizeFlagsStretchRatio = 1
            };

            var orderBtn = new Button { Text = Loc.GetString("department-console-btn-order") };
            var catIdx = entry.CategoryIndex;
            var entIdx = entry.EntryIndex;
            orderBtn.OnPressed += _ =>
            {
                var reason = OrderReasonInput.Text ?? "";
                var deliverTo = OrderDeliverToInput.Text ?? "";
                OnOrderPressed?.Invoke(catIdx, entIdx, reason, deliverTo);
            };

            row.AddChild(nameLabel);
            row.AddChild(costLabel);
            row.AddChild(orderBtn);

            OrderItemList.AddChild(row);
        }

        if (category.Entries.Count == 0)
            OrderItemList.AddChild(new Label { Text = Loc.GetString("department-console-no-items") });
    }
}

