- type: job
  parent: AU14JobSectionSergeantBase
  id: AU14JobGOVFORSectionSergeantCMBCIU
  name: Unit Leader
  ranks:
    AU14RankCMBChiefDeputy: []
  spawnMenuRoleName: Section Sergeant (CMBCIU)
  special:
  - !type:AddComponentSpecial
    components:
    - type: JobPrefix
      prefix: au14-job-prefix-AU14JobGOVFORSectionSergeantCMBCIU
