- type: job
  parent: AU14JobSquadSergeantBase
  id: AU14JobGOVFORSquadSergeantCMBCIU
  name: Team Leader
  spawnMenuRoleName: Squad Sergeant (CMBCIU)
  overwatchRoleName: Squad Sergeant
  ranks:
    AU14RankCMBSrDeputy: []
  special:
  - !type:AddComponentSpecial
    components:
    - type: JobPrefix
      prefix: au14-job-prefix-AU14JobGOVFORSquadSergeantCMBCIU
