- type: job
  parent: AU14JobPlatCoBase
  id: AU14JobGOVFORPlatCoCMBCIU
  name: Platoon Commander
  spawnMenuRoleName: Platoon Commander (CMBCIU)
  ranks:
    AU14RankCMBMarshal: []
  special:
  - !type:AddComponentSpecial
    components:
    - type: JobPrefix
      prefix: au14-job-prefix-AU14JobGOVFORPlatCoCMBCIU
