- type: job
  parent: AU14JobPlatoonCorpsmanBase
  id: AU14JobGOVFORPlatoonCorpsmanCMBCIU
  name: Tactical Medic
  spawnMenuRoleName: Hospital Corpsman (CMBCIU)
  ranks:
    AU14RankCMBSrDeputy:
    - !type:RoleTimeRequirement
      role: AU14JobGOVFORPlatoonCorpsman
      time: 108000 # 30 hours
    AU14RankCMBDeputy: []
  special:
  - !type:AddComponentSpecial
    components:
    - type: Skills
      skills:
        RMCSkillFirearms: 2
        RMCSkillFireman: 1
        RMCSkillJtac: 1
        RMCSkillMedical: 2
        RMCSkillSurgery: 1
        RMCSkillConstruction: 2
        RMCSkillEngineer: 3
        RMCSkillPolice: 2
    - type: JobPrefix
      prefix: au14-job-prefix-AU14JobGOVFORPlatoonCorpsmanCMBCIU
