- type: job
  parent: AU14JobSectionSergeantBase
  id: AU14JobGOVFORSectionSergeant
  # hidden: false # plt. sgt. is disabled
  # setPreference: true # don't show in loadout menu
  basePlaytimeTracker: true
