- type: job
  parent: AU14JobPlatCoBase
  id: AU14JobGOVFORPlatCo
  whitelisted: true
  whitelistParent: RMCWhitelistEasy
  name: au14-job-name-govforplatco
  description: au14-job-description-govforplatco
  setPreference: true
  basePlaytimeTracker: true
