ent-ClothingHeadHelmetBasic-name = helmet
ent-ClothingHeadHelmetBasic-desc = Standard security gear. Protects the head from impacts.

ent-ClothingHeadHelmetMerc-name = mercenary helmet
ent-ClothingHeadHelmetMerc-desc = The combat helmet is commonly used by mercenaries, is strong, light and smells like gunpowder and the jungle.

ent-ClothingHeadHelmetSwat-name = SWAT helmet
ent-ClothingHeadHelmetSwat-desc = An extremely robust helmet, commonly used by paramilitary forces. This one has the Nanotrasen logo emblazoned on the top.

ent-ClothingHeadHelmetSwatSyndicate-name = SWAT helmet
ent-ClothingHeadHelmetSwatSyndicate-desc = An extremely robust helmet, commonly used by paramilitary forces. It is adorned in a nefarious red and black stripe pattern.

ent-ClothingHeadHelmetRiot-name = light riot helmet
ent-ClothingHeadHelmetRiot-desc = It's a helmet specifically designed to protect against close range attacks.

ent-ClothingHeadHelmetBombSuit-name = bombsuit helmet
ent-ClothingHeadHelmetBombSuit-desc = A heavy helmet designed to withstand the pressure generated by a bomb and any fragments the bomb may produce.

ent-ClothingHeadHelmetJanitorBombSuit-name = janitorial bombsuit helmet
ent-ClothingHeadHelmetJanitorBombSuit-desc = A heavy helmet designed to withstand explosions formed from reactions between chemicals.

ent-ClothingHeadHelmetCult-name = cult helmet
ent-ClothingHeadHelmetCult-desc = A robust, evil-looking cult helmet.

ent-ClothingHeadHelmetSpaceNinja-name = space ninja helmet
ent-ClothingHeadHelmetSpaceNinja-desc = What may appear to be a simple black garment is in fact a highly sophisticated nano-weave helmet. Standard issue ninja gear.

ent-ClothingHeadHelmetTemplar-name = knight helmet
ent-ClothingHeadHelmetTemplar-desc = Decorative helmet fashioned to resemble the knights of old.

ent-ClothingHeadHelmetThunderdome-name = thunderdome helmet
ent-ClothingHeadHelmetThunderdome-desc = Let the battle commence!

ent-ClothingHeadHelmetWizardHelm-name = wizard helm
ent-ClothingHeadHelmetWizardHelm-desc = Strange-looking helmet that most certainly belongs to a real magic user.

ent-ClothingHeadHelmetFire-name = fire helmet
ent-ClothingHeadHelmetFire-desc = An atmos tech's best friend. Provides some heat resistance and looks cool.

ent-ClothingHeadHelmetAtmosFire-name = atmos fire helmet
ent-ClothingHeadHelmetAtmosFire-desc = An atmos fire helmet, able to keep the user cool in any situation.

ent-ClothingHeadHelmetLing-name = chitinous helmet
ent-ClothingHeadHelmetLing-desc = An all-consuming chitinous mass of armor.

ent-ClothingHeadHelmetERTLeader-name = ERT leader helmet
ent-ClothingHeadHelmetERTLeader-desc = An in-atmosphere helmet worn by the leader of a Nanotrasen Emergency Response Team. Has blue highlights.

ent-ClothingHeadHelmetERTSecurity-name = ERT security helmet
ent-ClothingHeadHelmetERTSecurity-desc = An in-atmosphere helmet worn by security members of the Nanotrasen Emergency Response Team. Has red highlights.

ent-ClothingHeadHelmetERTMedic-name = ERT medic helmet
ent-ClothingHeadHelmetERTMedic-desc = An in-atmosphere helmet worn by medical members of the Nanotrasen Emergency Response Team. Has white highlights.

ent-ClothingHeadHelmetERTEngineer-name = ERT engineer helmet
ent-ClothingHeadHelmetERTEngineer-desc = An in-atmosphere helmet worn by engineering members of the Nanotrasen Emergency Response Team. Has orange highlights.

ent-ClothingHeadHelmetERTJanitor-name = ERT janitor helmet
ent-ClothingHeadHelmetERTJanitor-desc = An in-atmosphere helmet worn by janitorial members of the Nanotrasen Emergency Response Team. Has dark purple highlights.

ent-ClothingHeadHelmetRaid-name = syndicate raid helmet
ent-ClothingHeadHelmetRaid-desc = An armored helmet for use with the syndicate raid suit. Very stylish.

ent-ClothingHeadHelmetBone-name = bone helmet
ent-ClothingHeadHelmetBone-desc = Cool-looking helmet made of skull of your enemies.

ent-ClothingHeadHelmetPodWars-name = ironclad II helmet
ent-ClothingHeadHelmetPodWars-desc = An ironclad II helmet, a relic of the pod wars.

ent-ClothingHeadHelmetJustice-name = justice helm
ent-ClothingHeadHelmetJustice-desc = Advanced security gear. Protects the station from ne'er-do-wells.

ent-ActionToggleJusticeHelm-name = Toggle Justice Helm
ent-ActionToggleJusticeHelm-desc = Toggles the justice helm on and off.

ent-ClothingHeadHelmetBase-name = lathe-category-clothing

ent-ClothingHeadHelmetArmoredBase-name = lathe-category-clothing

ent-ClothingHeadHelmetJusticeEmpty-name = helmet
ent-ClothingHeadHelmetJusticeEmpty-desc = Standard security gear. Protects the head from impacts.

