ent-ClothingUniformRandom-name = lathe-category-clothing
ent-ClothingUniformRandom-desc = Generated by neural networks based on the latest fashion trends.

ent-ClothingRandomSpawner-name = random colorful costume
ent-ClothingRandomSpawner-desc = Generated by neural networks based on the latest fashion trends.

ent-ClothingUniformRandomArmless-name = colorful hands-free costume
ent-ClothingUniformRandomArmless-desc = Generated by neural networks based on the latest fashion trends.

ent-ClothingUniformRandomStandard-name = colorful costume
ent-ClothingUniformRandomStandard-desc = Generated by neural networks based on the latest fashion trends.

ent-ClothingUniformRandomBra-name = colorful bra
ent-ClothingUniformRandomBra-desc = Generated by neural networks based on the latest fashion trends.

ent-ClothingUniformRandomShorts-name = colorful pants
ent-ClothingUniformRandomShorts-desc = Generated by neural networks based on the latest fashion trends.

ent-ClothingUniformRandomShirt-name = colorful costume
ent-ClothingUniformRandomShirt-desc = Generated by neural networks based on the latest fashion trends.

