- type: job
  abstract: true
  parent: AU14JobMilitaryBase
  id: AU14JobDCCBaseAbstract
  name: au14-job-name-govfordcc
  description: au14-job-description-govfordcc
  icon: "AU14JobIconDCC"
  spawnMenuRoleName: Dropship Crew Chief (GOVFOR)
  startingGear: AU14GearGOVFORDCC
  dummyStartingGear: AU14GearGOVFORDCCDummy
  playTimeTracker: AU14JobGOVFORDCC
  requireAdminNotify: true
  canBeAntag: false
  accessGroups:
  - AU14GovforPilot
  - AU14GovforCorpsman
  - AU14GovforSquad

- type: job
  abstract: true
  parent: AU14JobDCCBaseAbstract
  id: AU14JobDCCBase
  requirements:
  - !type:TraitsRequirement
    inverted: true
    traits:
    - Epilepsy
    - NonResuscitable
  ranks:
    AU14RankUSASFCMSgt:
    - !type:RoleTimeRequirement
      role: AU14JobGOVFORDCC
      time: 360000 # 100 hours
    AU14RankUSASFSMSgt:
    - !type:RoleTimeRequirement
      role: AU14JobGOVFORDCC
      time: 216000 # 60 hours
    AU14RankUSASFMasterSergeant:
    - !type:RoleTimeRequirement
      role: AU14JobGOVFORDCC
      time: 43200 # 12 hours
    AU14RankUSASFTechnicalSergeant: []
  special:
  - !type:AddComponentSpecial
    components:
    - type: Skills
      preset: AU14SkillPresetPlatoonDCC
    - type: JobPrefix
      prefix: au14-job-prefix-govfordcc
    - type: TacticalMapIcon
      icon:
        sprite: /Textures/_AU14/Interface/au14govforhud.rsi
        state: govfor_dcc

- type: playTimeTracker
  id: AU14JobGOVFORDCC
  isHumanoid: true

- type: startingGear
  id: AU14GearGOVFORDCC
  equipment:
    id: AU14IDCardGOVFORDCC
    ears: AU14HeadsetGovforCommand

- type: startingGear
  id: AU14GearGOVFORDCCDummy
  equipment:
    outerClothing: AU14USASFICPS2
    shoes: CMBootsBrown
    head: AU14USASFAirCrewHelmet
    jumpsuit: AU14USASFPilotJumpsuit
    ears: AU14HeadsetGovforMarine

- type: entity
  parent: CMSpawnPointJobBase
  id: AU14SpawnPointGOVFORDCC
  name: Spawn Point GOVFOR Dropship Crew Chief
  components:
  - type: SpawnPoint
    job_id: AU14JobGOVFORDCC
  - type: Sprite
    state: syn_spawn
