- type: job
  parent: CMJobBase
  id: AU14JobDSPilotBase
  name: au14-job-name-govfordspilot
  description: au14-job-description-govfordspilot
  playTimeTracker: AU14JobGOVFORDSPilot
  basePlaytimeTracker: true
  hidden: true
  abstract: true
  requirements:
  - !type:DepartmentTimeRequirement
    department: AU14DepartmentGovernmentForces
    time: 72000 # 20 hours

- type: playTimeTracker
  id: AU14JobGOVFORDSPilot
  isHumanoid: true