- type: job
  abstract: true
  parent: AU14JobMilitaryBase
  id: AU14JobDSPilotBaseAbstract
  name: au14-job-name-govfordspilot
  description: au14-job-description-govfordspilot
  icon: "AU14JobIconPilotOfficer"
  spawnMenuRoleName: Pilot Officer (GOVFOR)
  startingGear: AU14GearGOVFORDSPilot
  dummyStartingGear: AU14GearGOVFORDSPilotDummy
  playTimeTracker: AU14JobGOVFORDSPilot
  requireAdminNotify: true
  canBeAntag: false
  accessGroups:
  - AU14GovforPilot
  - AU14GovforCorpsman
  - AU14GovforSquad

- type: job
  abstract: true
  parent: AU14JobDSPilotBaseAbstract
  id: AU14JobDSPilotBase
  requirements:
  - !type:AgeRequirement
    requiredAge: 25
  - !type:TraitsRequirement
    inverted: true
    traits:
    - SocialAnxietyHeavy
    - FrontalLisp
    - NonResuscitable
    - Epilepsy
  ranks:
    RMCRankCaptain:
    - !type:RoleTimeRequirement
      role: AU14JobGOVFORDSPilot
      time: 360000 # 100 hours
    RMCRankFirstLT:
    - !type:RoleTimeRequirement
      role: AU14JobGOVFORDSPilot
      time: 86400 # 24 hours
    RMCRankSecondLT: []
  special:
  - !type:AddComponentSpecial
    components:
    - type: Skills
      preset: AU14SkillPresetPlatoonDP
    - type: JobPrefix
      prefix: au14-job-prefix-govfordspilot
    - type: TacticalMapIcon
      icon:
        sprite: /Textures/_AU14/Interface/au14govforhud.rsi
        state: govfor_po

- type: playTimeTracker
  id: AU14JobGOVFORDSPilot
  isHumanoid: true

- type: startingGear
  id: AU14GearGOVFORDSPilot
  equipment:
    id: AU14IDCardGOVFORDSPilot
    ears: AU14HeadsetGovforCommand

- type: startingGear
  id: AU14GearGOVFORDSPilotDummy
  equipment:
    outerClothing: AU14USASFICPS2
    shoes: CMBootsBrown
    mask: AU14MaskUSASFPilotOxygen
    head: AU14USASFAirCrewHelmet
    jumpsuit: AU14USASFPilotJumpsuit
    ears: AU14HeadsetGovforCommand

- type: entity
  parent: CMSpawnPointJobBase
  id: AU14SpawnPointGOVFORDSPilot
  name: Spawn Point GOVFOR Dropship Pilot
  components:
  - type: SpawnPoint
    job_id: AU14JobGOVFORDSPilot
  - type: Sprite
    state: syn_spawn
