- type: job
  parent: CMJobBase
  id: AU14JobMilitaryPoliceBase
  name: au14-job-name-govformilitarypoliceman
  description: au14-job-description-govformilitarypoliceman
  playTimeTracker: AU14JobGOVFORMilitaryPoliceMan
  basePlaytimeTracker: true
  hidden: true

- type: playTimeTracker
  id: AU14JobGOVFORMilitaryPoliceMan
  isHumanoid: true