- type: job
  parent: CMJobBase
  id: AU14JobPlatOpBase
  name: au14-job-name-govforplatop
  description: au14-job-description-govforplatop
  playTimeTracker: AU14JobGOVFORPlatOp
  basePlaytimeTracker: true
  hidden: true
  abstract: true
  requirements:
  - !type:DepartmentTimeRequirement
    department: AU14DepartmentGovernmentForces
    time: 72000 # 20 hours
  - !type:RoleTimeRequirement
    role: AU14JobGOVFORSectionSergeant
    time: 36000 # 20 hours

- type: playTimeTracker
  id: AU14JobGOVFORPlatOp
  isHumanoid: true