using System.Linq;
using System.Numerics;
using Content.Shared._AU14.Radio;
using Content.Shared.Radio;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.IoC;
using Robust.Shared.Maths;
using Robust.Shared.Prototypes;
using Robust.Shared.Timing;

namespace Content.Client._AU14.Radio;

[GenerateTypedNameReferences]
public sealed partial class ANPRCRadioWindow : DefaultWindow
{
    [Dependency] private IPrototypeManager _prototype = default!;

    public event Action<int>? OnSelectSlot;
    public event Action? OnTogglePower;
    public event Action? OnToggleMonitor;
    public event Action<RadioMode>? OnSetMode;
    public event Action<bool>? OnSetScan;
    public event Action<RadioTxPower>? OnSetTxPower;
    public event Action<int>? OnSetSquelch;
    public event Action<string>? OnSetCallsign;
    public event Action<string>? OnAddSlot;
    public event Action<int>? OnDeleteSlot;
    public event Action<int, ProtoId<RadioChannelPrototype>>? OnSetSlotChannel;
    public event Action<int>? OnClearSlot;
    public event Action? OnCryptoZeroize;
    public event Action? OnCryptoDestroy;
    public event Action? OnCryptoRecrypto;
    public event Action? OnRadioCheck;
    public event Action? OnOpenDirectory;
    public event Action<int, string>? OnManualFrequency;

    private static readonly Color LcdBright = Color.FromHex("#3FCF8E");
    private static readonly Color LcdMid = Color.FromHex("#2D9E60");
    private static readonly Color LcdDim = Color.FromHex("#4A7A55");
    private static readonly Color LcdOff = Color.FromHex("#1E4A2E");
    private static readonly Color LcdWarning = Color.FromHex("#D6B85A");

    private static readonly Color TextBright = Color.FromHex("#C8D2E8");
    private static readonly Color TextDim = Color.FromHex("#687A9A");
    private static readonly Color TextGood = Color.FromHex("#78D69B");
    private static readonly Color TextWarn = Color.FromHex("#D6B85A");
    private static readonly Color TextBad = Color.FromHex("#D65A5A");
    private static readonly Color TextLog = Color.FromHex("#3FCF8E");

    private ANPRCRadioState? _lastState;

    // the BUI rebuilds this window every open, remember the operator's size for the
    // session so they aren't re-dragging it to fit their screen each time
    private static Vector2? _rememberedSize;

    private bool _recryptoArmed;
    private DateTime _recryptoArmedUntil;

    private int _entryTargetSlot = -1;

    private enum EntryTab { Freq, Net }
    private EntryTab _activeEntryTab = EntryTab.Freq;

    private string? _netLogChannelFilter;
    private string _netLogSearchFilter = string.Empty;
    private readonly List<string> _netLogChannels = new();

    private readonly List<string> _callsignPresets = new();

    public ANPRCRadioWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        Title = Loc.GetString("anprc-window-title");

        PowerButton.OnPressed += _ => OnTogglePower?.Invoke();

        ModeButton.OnPressed += _ =>
        {
            if (_lastState == null) return;
            var next = _lastState.Mode switch
            {
                RadioMode.FrequencyHopping => RadioMode.SingleChannel,
                RadioMode.SingleChannel => RadioMode.CipherText,
                RadioMode.CipherText => RadioMode.PlainText,
                RadioMode.PlainText => RadioMode.FrequencyHopping,
                _ => RadioMode.FrequencyHopping,
            };
            OnSetMode?.Invoke(next);
        };

        MonitorButton.OnPressed += _ => OnToggleMonitor?.Invoke();

        ScanButton.OnPressed += _ =>
        {
            if (_lastState == null) return;
            OnSetScan?.Invoke(!_lastState.ScanEnabled);
        };

        SquelchButton.OnPressed += _ =>
        {
            if (_lastState == null) return;
            var next = _lastState.SquelchLevel >= ANPRCRadioComponent.MaxSquelchLevel ? 0 : _lastState.SquelchLevel + 1;
            OnSetSquelch?.Invoke(next);
        };

        TxPowerButton.OnPressed += _ =>
        {
            if (_lastState == null) return;
            var next = _lastState.TxPower switch
            {
                RadioTxPower.Low => RadioTxPower.Medium,
                RadioTxPower.Medium => RadioTxPower.High,
                _ => RadioTxPower.Low,
            };
            OnSetTxPower?.Invoke(next);
        };

        CallsignSetButton.OnPressed += _ =>
        {
            var text = CallsignLineEdit.Text.Trim().ToUpperInvariant();
            if (text.Length > ANPRCRadioComponent.MaxCallsignLength)
                text = text[..ANPRCRadioComponent.MaxCallsignLength];
            OnSetCallsign?.Invoke(text);
            CallsignLineEdit.Text = string.Empty;
        };

        // picking a preset just fills the line edit, SET still confirms and the field
        // stays free-text for custom callsigns
        CallsignPresetButton.OnItemSelected += args =>
        {
            CallsignPresetButton.SelectId(0);

            if (args.Id <= 0 || args.Id > _callsignPresets.Count)
                return;

            CallsignLineEdit.Text = _callsignPresets[args.Id - 1];
        };

        AddSlotButton.OnPressed += _ =>
        {
            AddSlotPanel.Visible = true;
            AddSlotLabelEdit.Text = string.Empty;
            AddSlotLabelEdit.GrabKeyboardFocus();
        };

        AddSlotConfirmButton.OnPressed += _ =>
        {
            var label = AddSlotLabelEdit.Text.Trim().ToUpperInvariant();
            if (label.Length > ANPRCRadioComponent.MaxLabelLength)
                label = label[..ANPRCRadioComponent.MaxLabelLength];
            if (string.IsNullOrWhiteSpace(label)) label = "СЕТЬ";
            OnAddSlot?.Invoke(label);
            AddSlotPanel.Visible = false;
            AddSlotLabelEdit.Text = string.Empty;
        };

        AddSlotCancelButton.OnPressed += _ =>
        {
            AddSlotPanel.Visible = false;
            AddSlotLabelEdit.Text = string.Empty;
        };

        EntryTabFreqButton.OnPressed += _ => ShowEntryTab(EntryTab.Freq);
        EntryTabNetButton.OnPressed += _ => ShowEntryTab(EntryTab.Net);

        EntryTabClearButton.OnPressed += _ =>
        {
            if (_entryTargetSlot < 0) return;
            OnClearSlot?.Invoke(_entryTargetSlot);
            CloseSlotEntryPanel();
        };

        EntryFreqConfirmButton.OnPressed += _ =>
        {
            if (_entryTargetSlot < 0) return;
            var text = EntryFreqLineEdit.Text.Trim();
            if (!string.IsNullOrEmpty(text))
                OnManualFrequency?.Invoke(_entryTargetSlot, text);
            CloseSlotEntryPanel();
        };

        SlotEntryCloseButton.OnPressed += _ => CloseSlotEntryPanel();

        ZeroizeButton.OnPressed += _ => OnCryptoZeroize?.Invoke();
        DestroyButton.OnPressed += _ => OnCryptoDestroy?.Invoke();

        // superseding every fill card in the faction is not a one-misclick action:
        // first press arms the button, a second press within the window confirms
        RecryptoButton.Text = Loc.GetString("anprc-recrypto-button");
        RecryptoButton.OnPressed += _ =>
        {
            if (_recryptoArmed && DateTime.UtcNow <= _recryptoArmedUntil)
            {
                DisarmRecrypto();
                OnCryptoRecrypto?.Invoke();
                return;
            }

            _recryptoArmed = true;
            _recryptoArmedUntil = DateTime.UtcNow + TimeSpan.FromSeconds(4);
            RecryptoButton.Text = Loc.GetString("anprc-recrypto-button-confirm");
            RecryptoButton.ModulateSelfOverride = TextBad;
        };

        RadioCheckButton.OnPressed += _ => OnRadioCheck?.Invoke();
        DirectoryButton.OnPressed += _ => OnOpenDirectory?.Invoke();

        NetLogChannelFilter.OnItemSelected += args =>
        {
            NetLogChannelFilter.SelectId(args.Id);
            _netLogChannelFilter = args.Id == 0 ? null : _netLogChannels[args.Id - 1];
            if (_lastState != null)
                RebuildNetLog(_lastState);
        };

        NetLogSearchEdit.OnTextChanged += args =>
        {
            _netLogSearchFilter = args.Text.Trim();
            if (_lastState != null)
                RebuildNetLog(_lastState);
        };

        NetLogFilterClearButton.OnPressed += _ =>
        {
            _netLogChannelFilter = null;
            _netLogSearchFilter = string.Empty;
            NetLogSearchEdit.Text = string.Empty;
            NetLogChannelFilter.SelectId(0);
            if (_lastState != null)
                RebuildNetLog(_lastState);
        };

        AddSlotPanel.Visible = false;
        SlotEntryPanel.Visible = false;
    }

    // clamp to the viewport so the panel never opens taller than a small screen, and
    // restore the size the operator last dragged it to
    protected override void EnteredTree()
    {
        base.EnteredTree();

        var target = _rememberedSize ?? SetSize;

        if (Root is { } root)
            target = Vector2.Min(target, root.Size * 0.95f);

        SetSize = Vector2.Max(target, new Vector2(MinWidth, MinHeight));
    }

    protected override void Resized()
    {
        base.Resized();

        if (IsInsideTree)
            _rememberedSize = Size;
    }

    protected override void FrameUpdate(FrameEventArgs args)
    {
        base.FrameUpdate(args);

        if (_recryptoArmed && DateTime.UtcNow > _recryptoArmedUntil)
            DisarmRecrypto();
    }

    private void DisarmRecrypto()
    {
        _recryptoArmed = false;
        RecryptoButton.Text = Loc.GetString("anprc-recrypto-button");
        RecryptoButton.ModulateSelfOverride = null;
    }

    public void UpdateState(ANPRCRadioState state)
    {
        _lastState = state;

        var hasActiveDynFreq = state.FrequencyOverrides.TryGetValue(state.ActiveSlot, out var activeDynFreq);
        RadioChannelPrototype? activeProto = null;
        var hasActiveChannel = !hasActiveDynFreq &&
                               state.Presets.TryGetValue(state.ActiveSlot, out var activeChannel) &&
                               _prototype.TryIndex(activeChannel, out activeProto);

        var hasAnyActive = hasActiveChannel || hasActiveDynFreq;
        // planted retrans stations are fully operable from the panel without being worn
        var deployed = state.IsEquipped || state.Planted;
        var online = state.Enabled && deployed;
        var ready = online && hasAnyActive && state.ActiveSlot >= 0;

        HeaderPowerLabel.Text = state.Enabled ? "ПИТАНИЕ: ВКЛ" : "ПИТАНИЕ: ВЫКЛ";
        HeaderPowerLabel.FontColorOverride = state.Enabled ? TextGood : TextBad;

        if (state.Planted)
        {
            HeaderLinkLabel.Text = "СВЯЗЬ: РЕТРАНСЛЯТОР";
            HeaderLinkLabel.FontColorOverride = state.Enabled ? TextGood : TextDim;
        }
        else if (!state.IsEquipped)
        {
            HeaderLinkLabel.Text = "СВЯЗЬ: НЕ НАДЕТА";
            HeaderLinkLabel.FontColorOverride = TextWarn;
        }
        else if (!state.Enabled)
        {
            HeaderLinkLabel.Text = "СВЯЗЬ: ОЖИДАНИЕ";
            HeaderLinkLabel.FontColorOverride = TextDim;
        }
        else
        {
            HeaderLinkLabel.Text = hasAnyActive ? "СВЯЗЬ: ГОТОВА" : "СВЯЗЬ: НЕТ СЕТИ";
            HeaderLinkLabel.FontColorOverride = hasAnyActive ? TextGood : TextWarn;
        }

        LcdModeLabel.Text = $"РЕЖИМ: {ModeShort(state.Mode)}";
        LcdModeLabel.FontColorOverride = online ? LcdDim : LcdOff;
        CryptoLabel.FontColorOverride = online ? LcdDim : LcdOff;

        if (hasActiveDynFreq)
        {
            var fStr = FormatFreq(activeDynFreq);
            FrequencyLabel.Text = fStr;
            ChannelNameLabel.Text = "ПРЯМАЯ ЧАСТОТА";
            ChannelIdLabel.Text = $"ЧАСТОТА: {fStr}";
            BandLabel.Text = $"ДИАПАЗОН: {BandName(activeDynFreq)}";
            WaveformLabel.Text = "СИГНАЛ: ПРЯМОЙ";

            FrequencyLabel.FontColorOverride = ready ? LcdBright : LcdOff;
            ChannelNameLabel.FontColorOverride = ready ? LcdMid : LcdOff;
            ChannelIdLabel.FontColorOverride = online ? LcdDim : LcdOff;
            BandLabel.FontColorOverride = online ? LcdDim : LcdOff;
            WaveformLabel.FontColorOverride = online ? LcdDim : LcdOff;
        }
        else if (activeProto != null)
        {
            FrequencyLabel.Text = FormatFreq(PlanFreq(activeProto));
            ChannelNameLabel.Text = activeProto.LocalizedName.ToUpperInvariant();
            ChannelIdLabel.Text = $"КАНАЛ: {activeProto.ID}";
            BandLabel.Text = $"ДИАПАЗОН: {BandName(PlanFreq(activeProto))}";
            WaveformLabel.Text = $"СИГНАЛ: {(activeProto.LongRange ? "СПУТНИК" : "ПРЯМОЙ")}";

            FrequencyLabel.FontColorOverride = ready ? LcdBright : LcdOff;
            ChannelNameLabel.FontColorOverride = ready ? LcdMid : LcdOff;
            ChannelIdLabel.FontColorOverride = online ? LcdDim : LcdOff;
            BandLabel.FontColorOverride = online ? LcdDim : LcdOff;
            WaveformLabel.FontColorOverride = online ? LcdDim : LcdOff;
        }
        else
        {
            FrequencyLabel.Text = "-- . ---";
            ChannelNameLabel.Text = state.ActiveSlot < 0 ? "НЕТ АКТИВНОЙ ЯЧЕЙКИ" : "ЯЧЕЙКА ПУСТА";
            ChannelIdLabel.Text = "КАНАЛ: ---";
            BandLabel.Text = "ДИАПАЗОН: ---";
            WaveformLabel.Text = "СИГНАЛ: ---";

            FrequencyLabel.FontColorOverride = LcdOff;
            ChannelNameLabel.FontColorOverride = LcdOff;
            ChannelIdLabel.FontColorOverride = LcdOff;
            BandLabel.FontColorOverride = LcdOff;
            WaveformLabel.FontColorOverride = LcdOff;
        }

        if (!online)
        {
            TxIndicator.FontColorOverride = LcdOff;
            TxLabel.Text = "ВЫКЛ";
            TxLabel.FontColorOverride = LcdOff;
        }
        else if (!hasAnyActive)
        {
            TxIndicator.FontColorOverride = LcdWarning;
            TxLabel.Text = "НЕТ СЕТИ";
            TxLabel.FontColorOverride = LcdWarning;
        }
        else
        {
            TxIndicator.FontColorOverride = LcdBright;
            TxLabel.Text = state.MonitorEnabled ? "МОНИТОР" : "ОЖИДАНИЕ";
            TxLabel.FontColorOverride = state.MonitorEnabled ? LcdBright : LcdDim;
        }

        if (!deployed)
        {
            BitStatusLabel.Text = "ТЕСТ: НЕ НАДЕТА";
            BitStatusLabel.FontColorOverride = LcdWarning;
        }
        else if (!state.Enabled)
        {
            BitStatusLabel.Text = "ТЕСТ: НЕТ СВЯЗИ";
            BitStatusLabel.FontColorOverride = LcdOff;
        }
        else if (!hasAnyActive)
        {
            BitStatusLabel.Text = "ТЕСТ: НЕТ СЕТИ";
            BitStatusLabel.FontColorOverride = LcdWarning;
        }
        else
        {
            BitStatusLabel.Text = "ТЕСТ: НОРМА";
            BitStatusLabel.FontColorOverride = LcdBright;
        }

        SignalBarsLabel.Text = Bars(ready ? 8 : 0, 8);
        SignalBarsLabel.FontColorOverride = ready ? LcdBright : LcdOff;

        var batteryFilled = state.HasBattery ? (int)Math.Round(state.BatteryFraction * 6) : 0;
        BatteryBarsLabel.Text = state.HasBattery ? Bars(batteryFilled, 6) : "НЕТ БАТАРЕИ";
        BatteryBarsLabel.FontColorOverride = !state.HasBattery ? TextBad
                                            : state.BatteryFraction <= 0.2f ? LcdWarning
                                            : LcdDim;

        AntennaLabel.Text = $"АНТ: {state.AntennaLabel}";
        AntennaLabel.FontColorOverride = online ? LcdDim : LcdOff;

        if (!deployed)
        {
            FaultLabel.Text = "ОШИБКА: НЕ НАДЕТА";
            FaultLabel.FontColorOverride = TextWarn;
        }
        else if (!state.Enabled)
        {
            FaultLabel.Text = "ОШИБКА: ВЫКЛ";
            FaultLabel.FontColorOverride = TextDim;
        }
        else if (!hasAnyActive)
        {
            FaultLabel.Text = "ОШИБКА: НЕТ СЕТИ";
            FaultLabel.FontColorOverride = TextWarn;
        }
        else
        {
            FaultLabel.Text = "ОШИБКА: НЕТ";
            FaultLabel.FontColorOverride = TextGood;
        }

        // callsign: manual station override > wearer's assigned callsign (AUTO)
        if (!string.IsNullOrEmpty(state.Callsign))
        {
            CallsignDisplayLabel.Text = state.Callsign;
            CallsignDisplayLabel.FontColorOverride = TextGood;
        }
        else if (!string.IsNullOrEmpty(state.WearerCallsign))
        {
            CallsignDisplayLabel.Text = $"{state.WearerCallsign} (АВТО)";
            CallsignDisplayLabel.FontColorOverride = TextGood;
        }
        else
        {
            CallsignDisplayLabel.Text = "НЕИЗВЕСТНАЯ СТАНЦИЯ";
            CallsignDisplayLabel.FontColorOverride = TextDim;
        }

        RebuildCallsignPresets(state);

        RebuildSlotList(state);

        var slotCount = state.SlotLabels.Count;
        PresetSummaryLabel.Text = $"{slotCount}/{ANPRCRadioComponent.MaxSlots}";
        PresetSummaryLabel.FontColorOverride = slotCount > 0 ? TextDim : TextWarn;
        AddSlotButton.Disabled = slotCount >= ANPRCRadioComponent.MaxSlots || !online;

        ModeButton.Text = $"РЕЖИМ {ModeShort(state.Mode)}";
        MonitorButton.Text = state.MonitorEnabled ? "МОНИТОР ВКЛ" : "МОНИТОР ВЫКЛ";
        ScanButton.Text = state.ScanEnabled ? "СКАН ВКЛ" : "СКАН ВЫКЛ";
        SquelchButton.Text = $"ШУМ {state.SquelchLevel}";
        TxPowerButton.Text = $"ПЕРЕДАЧА {state.TxPower.Short()}";

        ModeButton.Disabled = !online;
        MonitorButton.Disabled = !online;
        ScanButton.Disabled = !online;
        SquelchButton.Disabled = !online;
        TxPowerButton.Disabled = !online;
        MonitorButton.Pressed = state.MonitorEnabled && online;
        ScanButton.Pressed = state.ScanEnabled && online;

        RoleValueLabel.Text = state.Planted ? "СТАНЦИЯ-РЕТРАНСЛЯТОР" : "РЕТРАНСЛЯТОР РТО";

        RelayValueLabel.Text = online && hasAnyActive ? "ОПОРА" : "ОЖИДАНИЕ";
        RelayValueLabel.FontColorOverride = online && hasAnyActive ? TextGood : TextDim;

        DiagnosticLineA.Text = online && hasAnyActive ? "ОПОРА: АКТИВНА"
                                          : online ? "ОПОРА: ОЖИДАНИЕ"
                                                                   : "ОПОРА: НЕТ СВЯЗИ";
        DiagnosticLineA.FontColorOverride = online && hasAnyActive ? TextGood : TextDim;
        DiagnosticLineB.Text = online && hasAnyActive ? "ОБХОД: ГОТОВ" : "ОБХОД: НЕТ";
        DiagnosticLineB.FontColorOverride = online && hasAnyActive ? TextGood : TextDim;

        RoleValueLabel.FontColorOverride = online ? TextBright : TextDim;

        var hasFill = !string.IsNullOrEmpty(state.CryptoFaction);
        var secured = hasFill && !state.CryptoStale;

        CryptoStatusLabel.Text = secured ? $"ЗАЩИЩЕНО ({state.CryptoDesignation})"
                                             : hasFill ? $"УСТАРЕЛО ({state.CryptoDesignation})"
                                                        : "НЕ ЗАЩИЩЕНО";
        CryptoStatusLabel.FontColorOverride = secured ? TextGood : hasFill ? TextWarn : TextBad;

        CryptoFillLabel.Text = hasFill
            ? state.CryptoStale
                ? $"КЛЮЧ: {state.CryptoDesignation} ({state.CryptoFaction.ToUpperInvariant()}) — УСТАРЕЛ, НУЖНА СМЕНА"
                : $"КЛЮЧ: {state.CryptoDesignation} ({state.CryptoFaction.ToUpperInvariant()})"
            : "КЛЮЧ: НЕТ — вставьте карту";
        CryptoFillLabel.FontColorOverride = secured ? TextGood : hasFill ? TextWarn : TextDim;

        ZeroizeButton.Disabled = !online || !hasFill;
        DestroyButton.Disabled = !online || !hasFill;
        RecryptoButton.Disabled = !online || !secured;

        if (RecryptoButton.Disabled && _recryptoArmed)
            DisarmRecrypto();

        RadioCheckButton.Disabled = !ready;

        RebuildNetLog(state);

        PowerButton.Text = state.Enabled
            ? Loc.GetString("anprc-power-off-button")
            : Loc.GetString("anprc-power-on-button");

        var net = hasActiveDynFreq
            ? $"ПРЯМАЯ {FormatFreq(activeDynFreq)}"
            : activeProto?.LocalizedName ?? "Нет сети";

        StatusLabel.Text =
            $"{(state.Planted ? "РАЗВЁРНУТА" : state.IsEquipped ? "НАДЕТА" : "НЕ НАДЕТА")}" +
            $" · {(state.Enabled ? "ВКЛ" : "ВЫКЛ")}" +
            $" · {net}";
    }

    // only rebuild the dropdown when the pool actually changes, otherwise the periodic
    // state updates yank an open dropdown shut
    private void RebuildCallsignPresets(ANPRCRadioState state)
    {
        if (state.CallsignPresets.SequenceEqual(_callsignPresets))
        {
            CallsignPresetButton.Visible = _callsignPresets.Count > 0;
            return;
        }

        _callsignPresets.Clear();
        _callsignPresets.AddRange(state.CallsignPresets);

        CallsignPresetButton.Clear();
        CallsignPresetButton.AddItem("ШАБЛОНЫ", 0);
        for (var i = 0; i < _callsignPresets.Count; i++)
        {
            CallsignPresetButton.AddItem(_callsignPresets[i], i + 1);
        }

        CallsignPresetButton.SelectId(0);
        CallsignPresetButton.Visible = _callsignPresets.Count > 0;
    }

    private void RebuildSlotList(ANPRCRadioState state)
    {
        SlotListContainer.RemoveAllChildren();

        // planted retrans stations stay tunable from the panel, matching the
        // deployed logic above, so nobody has to pack the bag up to switch nets
        var online = state.Enabled && (state.IsEquipped || state.Planted);
        var sortedSlots = state.SlotLabels.Keys.OrderBy(k => k).ToList();

        foreach (var slot in sortedSlots)
        {
            var label = state.SlotLabels[slot];
            var isActive = slot == state.ActiveSlot;

            string freqText;
            if (state.FrequencyOverrides.TryGetValue(slot, out var dynFreq))
                freqText = $"{FormatFreq(dynFreq)} МГц · ПРЯМАЯ";
            else if (state.Presets.TryGetValue(slot, out var ch) && _prototype.TryIndex(ch, out var proto))
                freqText = $"{FormatFreq(PlanFreq(proto))} МГц · {proto.LocalizedName.ToUpperInvariant()}";
            else
                freqText = "--- ПУСТО ---";

            var row = new BoxContainer { Orientation = BoxContainer.LayoutOrientation.Horizontal, SeparationOverride = 4 };

            var selectBtn = new Button
            {
                Text = $"[{label}]  {freqText}",
                HorizontalExpand = true,
                Pressed = isActive && online,
                Disabled = !online,
            };
            var capturedSlot = slot;
            selectBtn.OnPressed += _ => OnSelectSlot?.Invoke(capturedSlot);

            var tuneBtn = new Button
            {
                Text = "НАСТР.",
                MinWidth = 52,
                Disabled = !online,
            };
            tuneBtn.OnPressed += _ => OpenSlotEntryPanel(capturedSlot, state);

            var delBtn = new Button
            {
                Text = "УДАЛ.",
                MinWidth = 44,
            };
            delBtn.OnPressed += _ => OnDeleteSlot?.Invoke(capturedSlot);

            row.AddChild(selectBtn);
            row.AddChild(tuneBtn);
            row.AddChild(delBtn);
            SlotListContainer.AddChild(row);
        }
    }

    private void OpenSlotEntryPanel(int slot, ANPRCRadioState state)
    {
        _entryTargetSlot = slot;
        var label = state.SlotLabels.TryGetValue(slot, out var lbl) ? lbl : $"P{slot + 1}";
        SlotEntryHeaderLabel.Text = $"НАСТРОЙКА [{label}]:";
        SlotEntryPanel.Visible = true;
        EntryFreqLineEdit.Text = string.Empty;
        ShowEntryTab(EntryTab.Freq);
        RebuildNetList(state);
    }

    private void CloseSlotEntryPanel()
    {
        SlotEntryPanel.Visible = false;
        _entryTargetSlot = -1;
        EntryFreqLineEdit.Text = string.Empty;
    }

    private void ShowEntryTab(EntryTab tab)
    {
        _activeEntryTab = tab;
        EntryFreqPanel.Visible = tab == EntryTab.Freq;
        EntryNetScroll.Visible = tab == EntryTab.Net;

        EntryTabFreqButton.Pressed = tab == EntryTab.Freq;
        EntryTabNetButton.Pressed = tab == EntryTab.Net;
    }


    // frequencies come from the round's signal plan carried in the BUI state,
    // the prototype value is only the fallback book number
    private int PlanFreq(RadioChannelPrototype proto)
    {
        return _lastState != null && _lastState.ChannelFrequencies.TryGetValue(proto.ID, out var freq)
            ? freq
            : proto.Frequency;
    }

    private void RebuildNetList(ANPRCRadioState state)
    {
        EntryNetList.RemoveAllChildren();

        var opFaction = state.OperatorFaction;

        foreach (var proto in _prototype.EnumeratePrototypes<RadioChannelPrototype>())
        {
            // skip sentinels and non-displayable channels
            if (proto.Frequency <= 0)
                continue;

            // only list the radio's own faction nets. faction-less channels (colony,
            // civilian) get tuned by raw frequency instead
            if (!string.IsNullOrEmpty(opFaction) && proto.Faction != opFaction)
                continue;

            var capturedProto = proto;
            var btn = new Button
            {
                Text = $"{proto.LocalizedName.ToUpperInvariant()}  -  {FormatFreq(PlanFreq(proto))} МГц",
                HorizontalExpand = true,
            };
            btn.OnPressed += _ =>
            {
                if (_entryTargetSlot < 0) return;
                OnSetSlotChannel?.Invoke(_entryTargetSlot, new ProtoId<RadioChannelPrototype>(capturedProto.ID));
                CloseSlotEntryPanel();
            };
            EntryNetList.AddChild(btn);
        }
    }

    private void RebuildNetLog(ANPRCRadioState state)
    {
        RebuildNetLogChannelFilter(state);

        NetLogContainer.RemoveAllChildren();

        var shown = 0;
        foreach (var entry in state.NetLog)
        {
            if (!NetLogEntryMatchesFilters(entry))
                continue;

            shown++;
            var ts = TimeSpan.FromSeconds(entry.Timestamp);
            var timeStr = $"{(int) ts.TotalMinutes:D2}:{ts.Seconds:D2}";

            var line = new Label
            {
                Text = $"[{timeStr}] {entry.SenderName} · {entry.ChannelDisplay}",
                FontColorOverride = TextLog,
                ClipText = true,
            };
            var msg = new Label
            {
                Text = $"  {entry.Message}",
                FontColorOverride = TextDim,
                ClipText = true,
            };
            NetLogContainer.AddChild(line);
            NetLogContainer.AddChild(msg);
        }

        var filtered = _netLogChannelFilter != null || _netLogSearchFilter.Length > 0;
        NetLogCountLabel.Text = filtered
            ? $"Записей: {shown}/{state.NetLog.Count}"
            : $"Записей: {state.NetLog.Count}";

        if (filtered && shown == 0 && state.NetLog.Count > 0)
        {
            NetLogContainer.AddChild(new Label
            {
                Text = "НЕТ ЗАПИСЕЙ ПО ФИЛЬТРУ",
                FontColorOverride = TextDim,
            });
        }
    }

    private bool NetLogEntryMatchesFilters(ANPRCNetLogEntry entry)
    {
        if (_netLogChannelFilter != null && entry.ChannelDisplay != _netLogChannelFilter)
            return false;

        return _netLogSearchFilter.Length == 0 ||
               entry.SenderName.Contains(_netLogSearchFilter, StringComparison.OrdinalIgnoreCase) ||
               entry.Message.Contains(_netLogSearchFilter, StringComparison.OrdinalIgnoreCase);
    }

    // same deal as the callsign dropdown, only rebuild when the set of nets in the log
    // changes so an open dropdown doesn't get yanked shut
    private void RebuildNetLogChannelFilter(ANPRCRadioState state)
    {
        var channels = state.NetLog
            .Select(e => e.ChannelDisplay)
            .Distinct()
            .OrderBy(c => c, StringComparer.OrdinalIgnoreCase)
            .ToList();

        if (channels.SequenceEqual(_netLogChannels))
            return;

        _netLogChannels.Clear();
        _netLogChannels.AddRange(channels);

        NetLogChannelFilter.Clear();
        NetLogChannelFilter.AddItem("ВСЕ СЕТИ", 0);
        for (var i = 0; i < _netLogChannels.Count; i++)
        {
            NetLogChannelFilter.AddItem(_netLogChannels[i], i + 1);
        }

        // reselect the previously chosen net, if it rotated out of the 50-entry log fall
        // back to ALL instead of filtering on a ghost
        var selectedIdx = _netLogChannelFilter == null ? -1 : _netLogChannels.IndexOf(_netLogChannelFilter);
        if (selectedIdx < 0)
        {
            _netLogChannelFilter = null;
            NetLogChannelFilter.SelectId(0);
        }
        else
        {
            NetLogChannelFilter.SelectId(selectedIdx + 1);
        }
    }

    private static string FormatFreq(int raw)
        => raw >= 1000 ? $"{raw / 1000}.{raw % 1000:D3}" : $"00.{raw:D3}";

    private static string BandName(int f)
        => f < 3000 ? "LF" : f < 30000 ? "HF" : f < 88000 ? "VHF" : f < 300000 ? "UHF" : "SHF";

    private static string Bars(int filled, int total)
    {
        filled = Math.Clamp(filled, 0, total);
        return new string('█', filled) + new string('░', total - filled);
    }

    private static string ModeShort(RadioMode m) => m switch
    {
        RadioMode.FrequencyHopping => "FH",
        RadioMode.SingleChannel => "SC",
        RadioMode.CipherText => "CT",
        RadioMode.PlainText => "PT",
        _ => "FH",
    };
}
