- type: job
  parent: CMJobBase
  id: RuMCBlackDragoonsBulwarkBreacher
  roundSide: ThirdParty
  roundForce: BlackDragoons
  roundRole: RuMCBlackDragoonsBulwarkBreacher
  roundComponents:
  - type: AssignSquad
    whitelist:
      tags:
      - RuMCSquadBD
  - type: Skills
    skills:
      RMCSkillCqc: 3
      RMCSkillEngineer: 2
      RMCSkillConstruction: 2
      RMCSkillFirearms: 2
      RMCSkillPolice: 2
      RMCSkillFireman: 3
      RMCSkillEndurance: 3
      RMCSkillJtac: 1
      RMCSkillMedical: 1
  - type: JobPrefix
    prefix: Breacher
  - type: Language
    spokenLanguages:
    - Japanese
    - English
    understoodLanguages:
    - Japanese
    - English
    currentLanguage: Japanese
    defaultLanguage: Japanese

  name: Bulwark Breacher
  description: Black Dragoons Bulwark Breacher
  playTimeTracker: RuMCJobBlackDragoonsBulwarkBreacher
  ranks:
    RuMCRankSeniorContractor: []
  spawnMenuRoleName: Black Dragoons Bulwark Breacher
  startingGear: RuMCGearBlackDragoonsBulwarkBreacher
  greeting: You are a member of the "Black Dragoons" PMC. You have been summoned by the TWE ambassador to provide personal security. You have been informed of rebel activity in the sector. Your primary objective is the safety of the TWE ambassador; however, with the ambassador's permission, you may also assist law enforcement agencies in suppressing the uprising. You are [color=green]friendly[/color] toward TWE forces and [color=red]hostile[/color] toward the CLF.
  icon: "CMJobIconEmpty"
  joinNotifyCrew: false
  supervisors: au14-job-name-civilianambassadortwe
  accessGroups:
  - AU14GovforCommand
  - AU14GovforSquad
  hidden: false

- type: entity
  parent: RuMCBaseMobSpeciesOrganicBlackDragoons
  id: RuMCJobBlackDragoonsBulwarkBreacher
  name: Black Dragoons Bulwark Breacher
  components:
  - type: GhostTakeoverAvailable
  - type: GhostRoleApplySpecial
    squad: RuMCSquadBD
  - type: GhostRole
    makeSentient: true
    allowSpeech: true
    allowMovement: true
    name: Black Dragoons Bulwark Breacher
    description: You are a breacher with the "Black Dragoons" PMC. You are a senior contractor for the company's heavy assault and counter-insurgency force.
    job: RuMCBlackDragoonsBulwarkBreacher
    raffle:
      settings: short

- type: startingGear
  parent: RuMCGearBulwarkBase
  id: RuMCGearBlackDragoonsBulwarkBreacher
  equipment:
    id: RuCMIDCardBlackDragoonsBulwarkBreacher
    belt: RuMCBeltShotgunBDFull
    suitstorage: RuMCWeaponShotgunP79
  storage:
    outerClothing:
    - RMCRangefinder
    back:
    - AU14MRETWERMC
    - CMCanteen
    - AU14PacketGrenadeFragM12Filled
    - AU14PacketGrenadeTearGasFilled
    - CMEntrenchingTool
    - CMStunbaton
    - RMCBoxZiptie

- type: playTimeTracker
  id: RuMCJobBlackDragoonsBulwarkBreacher
