- type: job
  parent: AU14JobAuxSupportSynthBase
  id: AU14JobOPFORAuxSupportSynth
  whitelisted: true
  whitelistParent: RMCWhitelistMedium
  name: au14-job-name-opforauxsupportsynth
  description: au14-job-description-opforauxsupportsynth
  icon: "AU14JobIconOPFORSynth"
  spawnMenuRoleName: Support Synth (OPFOR)
  supervisors: au14-job-supervisors-opforplatco
  startingGear: AU14GearOPFORAuxSupportSynth
  dummyStartingGear: AU14GearOPFORAuxSupportSynthDummy
  accessGroups:
  - AU14OpforCommand
  - CMCargoTech
  special:
  - !type:AddComponentSpecial
    components:
    - type: Marine
      Faction: govfor
    - type: UserIFF
      factions:
      - OPFOR
    - type: NpcFactionMember
      factions:
      - OPFOR
    - type: TacticalMapIcon
      icon:
        sprite: /Textures/_AU14/Interface/au14opforhud.rsi
        state: synth

- type: startingGear
  id: AU14GearOPFORAuxSupportSynth
  equipment:
    id: AU14IDCardOPFORAuxSupportSynth
    ears: AU14HeadsetOpforCommand
    ears2: RMCM5CameraGear
    gloves: CMHandsInsulated
    shoes: CMBootsBlackFilled
    jumpsuit: AU14CivilianBoilerSuitDarkBlueSynth
    belt: AU14BeltMedicBagSupportSynth
    head: AU14CivBallCapBlack
    back: AU14SmartpackBlackFilled
    pocket1: AU14PouchToolsFilledSupportSynthetic
    pocket2: AU14PouchPoliceEquipmentSupportSynth
    outerClothing: AU14CMDefibrillator

- type: entity
  parent: CMSpawnPointJobBase
  id: AU14SpawnPointOPFORAuxSupportSynth
  name: Spawn Point OPFOR Support Synth
  components:
  - type: SpawnPoint
    job_id: AU14JobOPFORAuxSupportSynth
  - type: Sprite
    state: syn_spawn

- type: startingGear
  id: AU14GearOPFORAuxSupportSynthDummy
  equipment:
    gloves: CMHandsInsulated
    shoes: CMBootsBlackFilled
    jumpsuit: AU14CivilianBoilerSuitDarkBlueSynth
    belt: AU14BeltMedicBagSupportSynth
    head: AU14CivBallCapBlack
    back: AU14SmartpackBlackFilled
    eyes: RMCGlassesMedicalHUDGlasses
