- type: job
  parent: AU14JobAuxTechBase
  id: AU14JobOPFORAuxTech
  name: au14-job-name-opforAuxTech
  description: au14-job-description-opforAuxTech
  icon: "AU14JobIconOPFORRTO"
  spawnMenuRoleName: Техник (OPFOR)
  supervisors: au14-job-supervisors-opfor
  startingGear: AU14GearOPFORAuxTech
  dummyStartingGear: AU14GearOPFORAuxTechDummy
  accessGroups:
  - AU14OpforAuxTech
  special:
  - !type:AddComponentSpecial
    components:
    - type: Marine
      Faction: opfor
    - type: UserIFF
      factions:
      - OPFOR
    - type: NpcFactionMember
      factions:
      - OPFOR
    - type: TacticalMapIcon
      icon:
        sprite: /Textures/_AU14/Interface/au14opforhud.rsi
        state: rto

- type: startingGear
  id: AU14GearOPFORAuxTech
  equipment:
    shoes: CMBootsBlackFilled
    ears: AU14HeadsetOpforAuxiliary
    ears2: RMCM5CameraGear
    id: AU14JobIDCardOPFORAuxTech
  storage:
    back:
    - CMStampApproved
    - AU14StampAUX

- type: startingGear
  id: AU14GearOPFORAuxTechDummy
  equipment:
    shoes: CMBootsBlackFilled
    back: CMSatchelMarine
  storage:
    back:
    - CMStampApproved
    - AU14StampAUX

- type: entity
  parent: CMSpawnPointJobBase
  id: AU14SpawnPointOPFORAuxTech
  name: Точка спавна техника OPFOR
  components:
  - type: SpawnPoint
    job_id: AU14JobOPFORAuxTech
  - type: Sprite
    state: syn_spawn
