- type: job
  parent: AU14JobadvisorBase
  id: AU14JobOPFORadvisor
  name: au14-job-name-opforadvisor
  description: au14-job-description-opforadvisor
  icon: "AU14JobIconOPFORAdvisor"
  spawnMenuRoleName: Platoon Advisor (OPFOR)
  startingGear: AU14GearOPFORadvisor
  dummyStartingGear: AU14GearOPFORadvisorDummy
  supervisors: au14-job-supervisors-opfor
  whitelisted: true
  whitelistParent: RMCWhitelistMedium
  accessGroups:
  - AU14OpforCommand
  special:
  - !type:AddComponentSpecial
    components:
    - type: Marine
      Faction: opfor
    - type: UserIFF
      factions:
      - OPFOR
    - type: NpcFactionMember
      factions:
      - OPFOR
    - type: TacticalMapIcon
      icon:
        sprite: /Textures/_AU14/Interface/au14opforhud.rsi
        state: advisor

- type: startingGear
  id: AU14GearOPFORadvisor
  equipment:
    id: AU14IDCardOPFORAdvisor
    ears: AU14HeadsetOpforCommand
    back: AU14SatchelMarineAdvisorMilitary

- type: entity
  parent: CMSpawnPointJobBase
  id: AU14SpawnPointOPFORadvisor
  name: Spawn Point OPFOR Advisor
  components:
  - type: SpawnPoint
    job_id: AU14JobOPFORadvisor
  - type: Sprite
    state: syn_spawn

- type: startingGear
  id: AU14GearOPFORadvisorDummy
  equipment:
    shoes: CMBootsBrownFilled
    head: CMHeadCapDrill
    jumpsuit: CMJumpsuitBO
    ears: AU14HeadsetOpforCommand
