- type: job
  parent: AU14JobSquadCombatTechBase
  id: AU14JobOPFORSquadCombatTech
  name: au14-job-name-opforsquadcombattech
  description: au14-job-description-opforsquadcombattech
  icon: "AU14JobIconOPFORCT"
  spawnMenuRoleName: Combat Tech (OPFOR)
  supervisors: au14-job-supervisors-opfor
  startingGear: AU14GearOPFORSquadCombatTech
  dummyStartingGear: AU14GearOPFORCTDummy
  accessGroups:
  - AU14OpforEngineer
  special:
  - !type:AddComponentSpecial
    components:
    - type: Marine
      Faction: opfor
    - type: UserIFF
      factions:
      - OPFOR
    - type: NpcFactionMember
      factions:
      - OPFOR
    - type: TacticalMapIcon
      icon:
        sprite: /Textures/_AU14/Interface/au14opforhud.rsi
        state: ct
    - type: CMVendorUser
      id: AU14JobOPFORSquadCombatTech
      points: 50

- type: startingGear
  id: AU14GearOPFORSquadCombatTech
  equipment:
    id: AU14IDCardOPFORCT
    ears: AU14HeadsetOpforMarine

- type: entity
  parent: CMSpawnPointJobBase
  id: AU14SpawnPointOPFORSquadCombatTech
  name: Spawn Point OPFOR Comtech
  components:
  - type: SpawnPoint
    job_id: AU14JobOPFORSquadCombatTech
  - type: Sprite
    state: syn_spawn

- type: startingGear
  id: AU14GearOPFORCTDummy
  equipment:
    outerClothing: AU14ArmorM3JungleThree
    shoes: AU14BootsJungle
    head: AU14JungleM10Helmet
    jumpsuit: AU14JungleFatigues
    ears: AU14HeadsetOpforMarine
