- type: job
  parent: AU14JobSquadRiflemanBase
  id: AU14JobOpforSquadRifleman
  name: au14-job-name-opforsquadrifleman
  description: au14-job-description-opforsquadrifleman
  icon: "AU14JobIconOPFORRifleman"
  spawnMenuRoleName: Rifleman (OPFOR)
  supervisors: au14-job-supervisors-opfor
  startingGear: AU14GearopforSquadRifleman
  dummyStartingGear: AU14GearopforRiflemanDummy
  accessGroups:
  - AU14OpforSquad
  special:
  - !type:AddComponentSpecial
    components:
    - type: Marine
      Faction: opfor
    - type: UserIFF
      factions:
      - OPFOR
    - type: NpcFactionMember
      factions:
      - OPFOR
    - type: TacticalMapIcon
      icon:
        sprite: /Textures/_AU14/Interface/au14opforhud.rsi
        state: background

- type: startingGear
  id: AU14GearopforSquadRifleman
  equipment:
    id: AU14IDCardopforSquadRifleman
    ears: AU14HeadsetOpforMarine

- type: entity
  parent: CMSpawnPointJobBase
  id: AU14SpawnPointopforSquadRifleman
  name: Spawn Point opfor Squad Rifleman
  components:
  - type: SpawnPoint
    job_id: AU14JobOpforSquadRifleman
  - type: Sprite
    state: syn_spawn

- type: startingGear
  id: AU14GearopforRiflemanDummy
  equipment:
    outerClothing: AU14ArmorM3JungleThree
    shoes: AU14BootsJungle
    head: AU14JungleM10Helmet
    jumpsuit: AU14JungleFatigues
    ears: AU14HeadsetOpforMarine
