- type: job
  parent: AU14JobPlatCoBase
  id: AU14JobOpforPlatCo
  name: au14-job-name-opforplatco
  description: au14-job-description-opforplatco
  icon: "AU14JobIconOPFORPlatCo"
  spawnMenuRoleName: Platoon Commander (OPFOR)
  supervisors: au14-job-supervisors-opforplatco
  startingGear: AU14GearOPFORPlatCo
  dummyStartingGear: AU14GearOPFORPlatCoDummy
  accessGroups:
  - AU14OpforCommand
  special:
  - !type:AddComponentSpecial
    components:
    - type: NpcFactionMember
      factions:
      - OPFOR
    - type: Marine
      Faction: opfor
    - type: UserIFF
      factions:
      - OPFOR
    - type: JobPrefix
      prefix: au14-job-prefix-opforplatco

- type: startingGear
  id: AU14GearOPFORPlatCo
  equipment:
    id: AU14IDCardopforPlatCo
    ears: AU14HeadsetOpforCommand
  inhand:
   -  AU14TabletOpfor

- type: startingGear
  id: AU14GearOPFORPlatCoDummy
  equipment:
    shoes: CMBootsBlack
    head: CMHeadCapPeakedFormal
    jumpsuit: CMJumpsuitXOFormal
    ears: AU14HeadsetOpforCommand

- type: entity
  parent: CMSpawnPointJobBase
  id: AU14SpawnPointopforPlatCo
  name: Spawn Point opfor Platoon Commander
  components:
  - type: SpawnPoint
    job_id: AU14JobOpforPlatCo
  - type: Sprite
    state: syn_spawn
