- type: job
  parent: AU14JobDCCBase
  id: AU14JobOpforDCC
  name: au14-job-name-opfordcc
  description: au14-job-description-opfordcc
  icon: "AU14JobIconOPFORDCC"
  spawnMenuRoleName: Dropship Crew Chief (OPFOR)
  supervisors: au14-job-supervisors-opfor
  startingGear: AU14GearopforDCC
  dummyStartingGear: AU14GearopforDCCDummy
  accessGroups:
  - AU14OpforPilot
  - AU14OpforCorpsman
  - AU14OpforSquad
  special:
  - !type:AddComponentSpecial
    components:
    - type: Marine
      Faction: opfor
    - type: UserIFF
      factions:
      - OPFOR
    - type: NpcFactionMember
      factions:
      - OPFOR
    - type: TacticalMapIcon
      icon:
        sprite: /Textures/_AU14/Interface/au14opforhud.rsi
        state: dcc

- type: startingGear
  id: AU14GearopforDCC
  equipment:
    id: AU14IDCardopforDCC
    ears: AU14HeadsetOpforCommand

- type: entity
  parent: CMSpawnPointJobBase
  id: AU14SpawnPointopforDCC
  name: Spawn Point opfor Dropship Crew Chief
  components:
  - type: SpawnPoint
    job_id: AU14JobOpforDCC
  - type: Sprite
    state: syn_spawn

- type: startingGear
  id: AU14GearopforDCCDummy
  equipment:
    outerClothing: AU14USASFICPS2
    shoes: CMBootsBrown
    head: AU14USASFAirCrewHelmet
    jumpsuit: AU14USASFPilotJumpsuit
    ears: AU14HeadsetOpforMarine
