- type: job
  parent: AU14JobPlatoonCorpsmanBase
  id: AU14JobOpforPlatoonCorpsman
  name: au14-job-name-opforplatooncorpsman
  description: au14-job-description-opforplatooncorpsman
  icon: "AU14JobIconOPFORCorpsman"
  spawnMenuRoleName: Hospital Coprsman (OPFOR)
  supervisors: au14-job-supervisors-opfor
  startingGear: AU14GearopforPlatoonCorpsman
  dummyStartingGear: AU14GearopforCorpsmanDummy
  accessGroups:
  - AU14OpforCorpsman
  - AU14OpforSquad
  special:
  - !type:AddComponentSpecial
    components:
    - type: Marine
      Faction: opfor
    - type: UserIFF
      factions:
      - OPFOR
    - type: NpcFactionMember
      factions:
      - OPFOR
    - type: TacticalMapIcon
      icon:
        sprite: /Textures/_AU14/Interface/au14opforhud.rsi
        state: corpsman

- type: startingGear
  id: AU14GearopforPlatoonCorpsman
  equipment:
    id: AU14JobIDCardopforPlatoonCorpsman
    ears: AU14HeadsetOpforMarine

- type: entity
  parent: CMSpawnPointJobBase
  id: AU14SpawnPointopforPlatoonCorpsman
  name: Spawn Point opfor Squad Sergeant
  components:
  - type: SpawnPoint
    job_id: AU14JobOpforPlatoonCorpsman
  - type: Sprite
    state: syn_spawn

- type: startingGear
  id: AU14GearopforCorpsmanDummy
  equipment:
    outerClothing: AU14ArmorM3JungleOne
    gloves: CMHandsLatex
    shoes: CMBootsBlack
    head: AU14JungleM10CorpsmanHelmet
    jumpsuit: AU14JungleFatigues
    ears: AU14HeadsetOpforMarine
