- type: job
  parent: AU14JobSquadSergeantBase
  id: AU14JobOpforSquadSergeant
  name: au14-job-name-opforsquadsergeant
  description: au14-job-description-opforsquadsergeant
  icon: "AU14JobIconOPFORPlatoonSarge"
  spawnMenuRoleName: Squad Sergeant (OPFOR)
  supervisors: au14-job-supervisors-opfor
  startingGear: AU14GearOpforSquadSergeant
  dummyStartingGear: AU14GearOpforSquadSergeantDummy
  accessGroups:
  - AU14OpforFTL
  special:
  - !type:AddComponentSpecial
    components:
    - type: NpcFactionMember
      factions:
      - OPFOR
    - type: Marine
      Faction: opfor
    - type: UserIFF
      factions:
      - OPFOR
    - type: JobPrefix
      prefix: au14-job-prefix-opforsquadsergeant

- type: startingGear
  id: AU14GearOpforSquadSergeant
  equipment:
    id: AU14IDCardopforSquadSergeant
    ears: AU14HeadsetOpforCommand

- type: startingGear
  id: AU14GearOpforSquadSergeantDummy
  equipment:
    outerClothing: AU14ArmorM3JungleOne
    shoes: CMBootsBrown
    head: AU14JungleBoonieHat
    jumpsuit: AU14JungleFatigues
    ears: AU14HeadsetOpforCommand

- type: entity
  parent: CMSpawnPointJobBase
  id: AU14SpawnPointopforSquadSergeant
  name: Spawn Point opfor Squad Sergeant
  components:
  - type: SpawnPoint
    job_id: AU14JobOpforSquadSergeant
  - type: Sprite
    state: syn_spawn
