- type: job
  parent: AU14JobSectionSergeantBase
  id: AU14JobOpforSectionSergeant
  name: au14-job-name-opforSSG
  description: au14-job-description-opforSSG
  icon: "AU14JobIconOPFORPlatoonSarge"
  spawnMenuRoleName: Platoon Sergeant (OPFOR)
  supervisors: au14-job-supervisors-opfor
  startingGear: AU14GearopforSectionSergeant
  dummyStartingGear: AU14GearopforPlatoonSergantDummy
  accessGroups:
  - AU14OpforCommand
  special:
  - !type:AddComponentSpecial
    components:
    - type: Marine
      Faction: opfor
    - type: UserIFF
      factions:
      - OPFOR
    - type: NpcFactionMember
      factions:
      - OPFOR
    - type: TacticalMapIcon
      icon:
        sprite: /Textures/_AU14/Interface/au14opforhud.rsi
        state: platoonsergeant

- type: startingGear
  id: AU14GearopforSectionSergeant
  equipment:
    id: AU14IDCardopforSecSergeant
    ears: AU14HeadsetOpforCommand

- type: entity
  parent: CMSpawnPointJobBase
  id: AU14SpawnPointopforSectionSergeant
  name: Spawn Point opfor Section Sergeant
  components:
  - type: SpawnPoint
    job_id: AU14JobOpforSectionSergeant
  - type: Sprite
    state: syn_spawn

- type: startingGear
  id: AU14GearopforPlatoonSergantDummy
  equipment:
    outerClothing: AU14ArmorM3JungleTwo
    shoes: CMBootsBrown
    head: AU14JunglePatrolCap
    jumpsuit: AU14JungleFatigues
    ears: AU14HeadsetOpforCommand
