- type: job
  parent: AU14JobPlatOpBase
  id: AU14JobOpforPlatOp
  name: au14-job-name-opforplatop
  description: au14-job-description-opforplatop
  icon: "AU14JobIconOPFOROpsOfc"
  spawnMenuRoleName: Junior Officer (OPFOR)
  supervisors: au14-job-supervisors-opfor
  startingGear: AU14GearOpforPlatOp
  dummyStartingGear: AU14GearOpforPlatOpDummy
  accessGroups:
  - AU14OpforCommand
  special:
  - !type:AddComponentSpecial
    components:
    - type: Marine
      Faction: opfor
    - type: NpcFactionMember
      factions:
      - OPFOR
    - type: UserIFF
      factions:
      - OPFOR
    - type: JobPrefix
      prefix: au14-job-prefix-opforplatop
    - type: TacticalMapIcon
      icon:
        sprite: /Textures/_AU14/Interface/au14opforhud.rsi
        state: po
    - type: Skills
      preset: AU14SkillPresetPlatoonJuniorOfficer

- type: startingGear
  id: AU14GearOpforPlatOp
  equipment:
    id: AU14IDCardopforPlatOp
    ears: AU14HeadsetOpforCommand

- type: startingGear
  id: AU14GearOpforPlatOpDummy
  equipment:
    shoes: CMBootsBlack
    head: AU14JunglePatrolCap
    jumpsuit: CMJumpsuitXOFormal
    ears: AU14HeadsetOpforCommand

- type: entity
  parent: CMSpawnPointJobBase
  id: AU14SpawnPointopforPlatOp
  name: Spawn Point opfor Platoon Operations Officer
  components:
  - type: SpawnPoint
    job_id: AU14JobOpforPlatOp
  - type: Sprite
    state: syn_spawn
