- type: job
  parent: CMJobBase
  id: AU14JobLEOLeaderBase
  name: au14-job-name-leoleader
  description: au14-job-description-leoleader
  setPreference: true
  playTimeTracker: AU14JobCivilianCMBMarshal
  icon: "RMCJobIconBureauMarshal"
  basePlaytimeTracker: true
  hidden: false
  access: # accessGroups in use by inheritors
  - AU14AccessColonyMarshall
  - AU14AccessColonyAdministrator
  - AU14AccessColonyHeadPhysician
  - AU14AccessColonyForeman
  - AU14AccessColonyHeadEngineer
  - AU14AccessColonyHeadOfService
  requirements:
  - !type:DepartmentTimeRequirement
    department: AU14DepartmentColonySecurity
    time: 36000 # 10 hours
  - !type:OverallPlaytimeRequirement
    time: 86400 # 24 hours
  - !type:AgeRequirement
    requiredAge: 25
  - !type:TraitsRequirement
    inverted: true
    traits:
    - Epilepsy

- type: playTimeTracker
  id: AU14JobCivilianCMBMarshal
  isHumanoid: true
