- type: job
  abstract: true
  parent: CMJobBase
  id: AU14JobWorkingJoeBase
  name: au14-job-name-workingjoe
  description: au14-job-description-workingjoe
  playTimeTracker: AU14JobWorkingJoe
  basePlaytimeTracker: true
  setPreference: true
  canBeAntag: false
  whitelisted: true
  whitelistParent: RMCWhitelistMedium
  jobEntity: AU14MobWorkingJoe
  jobPreviewEntity: AU14MobWorkingJoeDummy

- type: playTimeTracker
  id: AU14JobWorkingJoe
  isHumanoid: true

- type: startingGear
  id: AU14GearWorkingJoeBase
  equipment:
    shoes: CMBootsBlack
    jumpsuit: CMJumpsuitAverageJoe
    belt: CMBeltUtilityFilled
    back: AU14IMPBackpackMarine
    pocket1: RMCPouchElectronicsFill
    pocket2: RMCPouchConstructionFillFull
  storage:
      belt:
      - AU14MaintenanceJack
      back:
      - AU14SprayCleanerExperimental
      - RMCBucketJanitorial
      - CMMop
      - CMWetSign
      - RMCLightReplacer
      - CMFireExtinguisher
      - AU14StampJoe
  inhand:
  - TrashBag
