- type: job
  parent: CMJobBase
  id: AU14JobCLFGuerilla
  name: au14-job-name-clfguerilla
  description: au14-job-description-clfguerilla
  setPreference: true
  ignoreAllegiance: true
  playTimeTracker: AU14JobCLFGuerilla
  basePlaytimeTracker: true
  requirements: # TWEAK: since departments are subject to change, little bit of everything
  - !type:DepartmentTimeRequirement
    department: AU14DepartmentCivilian
    time: 1800 # ~1 round (30mins)
  - !type:DepartmentTimeRequirement
    department: AU14DepartmentLabor
    time: 1800 # ~1 round (30mins)
  - !type:DepartmentTimeRequirement
    department: AU14DepartmentServices
    time: 1800 # ~1 round (30mins)
  - !type:DepartmentTimeRequirement
    department: AU14DepartmentColonyMedical
    time: 3200 # 1 hour
  - !type:DepartmentTimeRequirement
    department: AU14DepartmentColonySecurity
    time: 3200 # 1 hour
  - !type:DepartmentTimeRequirement
    department: AU14DepartmentEngineering
    time: 3200 # 1 hour
  - !type:DepartmentTimeRequirement
    department: AU14DepartmentCriminal
    time: 1800 # ~1 round (30mins)
  - !type:OverallPlaytimeRequirement
    time: 36000 # 10 hours
  ranks:
    RMCRankCivilian: []
  startingGear: AU14GearCLFGuerilla
  icon: "RMCJobIconCLFSoldier"
  hasIcon: false
  requireAdminNotify: false
  joinNotifyCrew: false
  supervisors: au14-job-supervisors-clflrs
  accessGroups:
  - Colonist
  roleWeight: 0.25
  special:
  - !type:AddComponentSpecial
    components:
    - type: NpcFactionMember
      factions:
      - CLF
    - type: CLFMember
    - type: Skills
      skills:
        RMCSkillEndurance: 1
        RMCSkillFirearms: 2
        RMCSkillConstruction: 2
        RMCSkillEngineer: 3
        RMCSkillFireman: 1
        RMCSkillVehicles: 1
        RMCSkillPolice: 1
    - type: JobPrefix
      prefix: au14-job-prefix-clfguerilla
    - type: StartingMindRole
      mindRole: MindRoleCLFGuerrilla
    - type: TacticalMapIcon
      icon:
        sprite: /Textures/_RMC14/Interface/map_blips.rsi
        state: synth
    - type: ShowMarineIcons
      factions:
      - CLF
  hidden: false

- type: startingGear
  id: AU14GearCLFGuerilla
  equipment:
    id: AU14IDCardCLFCivilian
   # neck: RMCCLFArmband
  inhand:
  - AU14CLFHeadset

- type: entity
  parent: CMSpawnPointJobBase
  id: AU14SpawnPointCLFGuerilla
  name: Spawn Point CLF Guerilla
  components:
  - type: SpawnPoint
    job_id: AU14JobCLFGuerilla
  - type: Sprite
    state: syn_spawn

- type: playTimeTracker
  id: AU14JobCLFGuerilla
  isHumanoid: true
