using System.Collections.Generic;
using System.Numerics;
using Content.Client.UserInterface.Controls;
using Content.Shared.Construction.Prototypes;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;

namespace Content.Client.Construction.UI
{
    /// <summary>
    /// This is the interface for a UI View of the construction window. The point of it is to abstract away the actual
    /// UI controls and just provide higher level operations on the entire window. This View is completely passive and
    /// just raises events to the outside world. This class is controlled by the <see cref="ConstructionMenuPresenter"/>.
    /// </summary>
    public interface IConstructionMenuView : IDisposable
    {
        // It isn't optimal to expose UI controls like this, but the UI control design is
        // questionable so it can't be helped.
        string[] Categories { get; set; }
        OptionButton OptionCategories { get; }

        bool EraseButtonPressed { get; set; }
        bool GridViewButtonPressed { get; set; }
        bool BuildButtonPressed { get; set; }

        ListContainer Recipes { get; }
        ItemList RecipeStepList { get; }


        ScrollContainer RecipesGridScrollContainer { get; }
        GridContainer RecipesGrid { get; }

        /// <summary>
        /// If true, the presenter populates <see cref="GroupedRecipesContainer"/> with per-category
        /// sections (header + sub-grid) instead of the flat <see cref="RecipesGrid"/>.
        /// </summary>
        bool UseGroupedView { get; }

        /// <summary>
        /// Vertical container the presenter fills with grouped category sections when
        /// <see cref="UseGroupedView"/> is true.
        /// </summary>
        BoxContainer GroupedRecipesContainer { get; }

        /// <summary>
        /// If true, the construction menu closes as soon as a build/placement begins.
        /// </summary>
        bool CloseOnConstruct { get; }

        /// <summary>
        /// The spawnlist (top-level tree group) currently selected. Empty string means "no spawnlist
        /// filter" (show everything). Menus without spawnlist support return empty.
        /// </summary>
        string SelectedSpawnlist { get; }

        /// <summary>
        /// Provides the menu with the distinct spawnlists discovered among recipes, so it can build
        /// its left-tree entries. No-op for menus without spawnlist support.
        /// </summary>
        void SetSpawnlists(IReadOnlyList<string> spawnlists);

        event EventHandler<(string search, string catagory)> PopulateRecipes;
        event EventHandler<ConstructionMenu.ConstructionMenuListData?> RecipeSelected;
        event EventHandler RecipeFavorited;
        event EventHandler<bool> BuildButtonToggled;
        event EventHandler<bool> EraseButtonToggled;
        event EventHandler ClearAllGhosts;

        void ClearRecipeInfo();
        void SetConstructionSkillInfo(int skillLevel, int discountPercent);
        void SetRecipeInfo(string name, string description, EntityPrototype? targetPrototype, Color iconColor, bool isItem, bool isFavorite, ConstructionPrototype prototype);
        void ResetPlacement();

        #region Window Control

        event Action? OnClose;

        bool IsOpen { get; }

        void OpenCentered();
        void MoveToFront();
        bool IsAtFront();
        void Close();

        #endregion
    }

    [GenerateTypedNameReferences]
    public sealed partial class ConstructionMenu : DefaultWindow, IConstructionMenuView
    {
        public bool BuildButtonPressed
        {
            get => BuildButton.Pressed;
            set => BuildButton.Pressed = value;
        }

        public string[] Categories { get; set; } = Array.Empty<string>();

        // The classic menu uses the flat grid/list, never grouped, and stays open while building.
        private readonly BoxContainer _stubGroupedContainer = new();
        public bool UseGroupedView => false;
        public BoxContainer GroupedRecipesContainer => _stubGroupedContainer;
        public bool CloseOnConstruct => false;

        // The classic menu has no spawnlist tree; it always shows everything.
        public string SelectedSpawnlist => string.Empty;
        public void SetSpawnlists(IReadOnlyList<string> spawnlists) { }

        public bool EraseButtonPressed
        {
            get => EraseButton.Pressed;
            set => EraseButton.Pressed = value;
        }

        public bool GridViewButtonPressed
        {
            get => MenuGridViewButton.Pressed;
            set => MenuGridViewButton.Pressed = value;
        }

        public ConstructionMenu()
        {
            SetSize = new Vector2(560, 450);
            MinSize = new Vector2(560, 320);

            IoCManager.InjectDependencies(this);
            RobustXamlLoader.Load(this);

            Title = Loc.GetString("construction-menu-title");

            BuildButton.Text = Loc.GetString("construction-menu-place-ghost");
            Recipes.ItemPressed += (_, data) => RecipeSelected?.Invoke(this, data as ConstructionMenuListData);
            Recipes.NoItemSelected += () => RecipeSelected?.Invoke(this, null);
            Recipes.GenerateItem += (data, button) =>
            {
                if (data is not ConstructionMenuListData (var prototype, var targetPrototype))
                    return;

                var entProtoView = new EntityPrototypeView()
                {
                    SetSize = new(32f),
                    Stretch = SpriteView.StretchMode.Fill,
                    Scale = new(2),
                    Margin = new(0, 2),
                };
                entProtoView.SetPrototype(targetPrototype);

                var label = new Label()
                {
                    Text = prototype.Name,
                    Margin = new(5, 0),
                };

                var box = new BoxContainer();
                box.AddChild(entProtoView);
                box.AddChild(label);

                button.AddChild(box);
                button.ToolTip = prototype.Description;
                button.AddStyleClass(ListContainer.StyleClassListContainerButton);
            };

            SearchBar.OnTextChanged += _ =>
                PopulateRecipes?.Invoke(this, (SearchBar.Text, Categories[OptionCategories.SelectedId]));
            OptionCategories.OnItemSelected += obj =>
            {
                OptionCategories.SelectId(obj.Id);
                SearchBar.SetText(string.Empty);
                PopulateRecipes?.Invoke(this, (SearchBar.Text, Categories[obj.Id]));
            };

            BuildButton.Text = Loc.GetString("construction-menu-place-ghost");
            BuildButton.OnToggled += args => BuildButtonToggled?.Invoke(this, args.Pressed);
            ClearButton.Text = Loc.GetString("construction-menu-clear-all");
            ClearButton.OnPressed += _ => ClearAllGhosts?.Invoke(this, EventArgs.Empty);
            EraseButton.Text = Loc.GetString("construction-menu-eraser-mode");
            EraseButton.OnToggled += args => EraseButtonToggled?.Invoke(this, args.Pressed);

            FavoriteButton.OnPressed += args => RecipeFavorited?.Invoke(this, EventArgs.Empty);

            MenuGridViewButton.OnPressed += _ =>
                PopulateRecipes?.Invoke(this, (SearchBar.Text, Categories[OptionCategories.SelectedId]));
        }

        public event EventHandler? ClearAllGhosts;
        public event EventHandler<(string search, string catagory)>? PopulateRecipes;
        public event EventHandler<ConstructionMenuListData?>? RecipeSelected;
        public event EventHandler? RecipeFavorited;
        public event EventHandler<bool>? BuildButtonToggled;
        public event EventHandler<bool>? EraseButtonToggled;

        public void ResetPlacement()
        {
            BuildButton.Pressed = false;
            EraseButton.Pressed = false;
        }

        public void SetRecipeInfo(
            string name,
            string description,
            EntityPrototype? targetPrototype,
            Color iconColor,
            bool isItem,
            bool isFavorite,
            ConstructionPrototype prototype)
        {
            BuildButton.Disabled = false;
            BuildButton.Text = Loc.GetString(isItem ? "construction-menu-place-ghost" : "construction-menu-craft");
            TargetName.SetMessage(name);
            TargetDesc.SetMessage(description);
            TargetTexture.SetPrototype(targetPrototype?.ID);
            TargetTexture.Modulate = iconColor;
            FavoriteButton.Visible = true;
            FavoriteButton.Text = Loc.GetString(
                            isFavorite ? "construction-add-favorite-button" : "construction-remove-from-favorite-button");

            // RMC14
            if (prototype.RMCPrototype != null)
                BuildButton.Text = Loc.GetString("rmc-construction-build-here");
        }

        public void ClearRecipeInfo()
        {
            BuildButton.Disabled = true;
            TargetName.SetMessage(string.Empty);
            TargetDesc.SetMessage(string.Empty);
            TargetTexture.SetPrototype(null);
            TargetTexture.Modulate = Color.White;
            FavoriteButton.Visible = false;
            RecipeStepList.Clear();
            ConstructionSkillInfo.Visible = false;
        }

        public void SetConstructionSkillInfo(int skillLevel, int discountPercent)
        {
            ConstructionSkillInfo.SetMessage(Loc.GetString("construction-menu-skill-info",
                ("skill", skillLevel),
                ("discount", discountPercent)),
                Color.FromHex("#72C7FF"));
            ConstructionSkillInfo.Visible = skillLevel > 0;
        }

        public sealed record ConstructionMenuListData(ConstructionPrototype Prototype, EntityPrototype TargetPrototype) : ListData;
    }
}
