- type: job
  parent: CMJobXenoBase
  id: AU14JobThreatMember
  name: au-job-name-threat-member
  description: au-job-description-threat-member
  setPreference: true
  playTimeTracker: AUJobThreatMember
  hidden: false
  supervisors: nobody
  icon: "AU14JobIconThreatMember"
  jobPreviewEntity: RMCPlayerXenoQueenPreview
  accessGroups:
  - CMAccessXeno
  - CMAccessXenoQueen

- type: playTimeTracker
  id: AUJobThreatMember
