using Content.Client.Stylesheets;
using Content.Shared.CCVar;
using Content.Shared.Administration.Managers;
using JetBrains.Annotations;
using Robust.Client.AutoGenerated;
using Robust.Client.Player;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Configuration;

namespace Content.Client.Lobby.UI;

[GenerateTypedNameReferences]
[UsedImplicitly]
public sealed partial class ObserveWarningWindow : DefaultWindow
{
    [Dependency] private IConfigurationManager _cfg = default!;
    [Dependency] private ISharedAdminManager _adminManager = default!;
    [Dependency] private IPlayerManager _playerManager = default!;
    [Dependency] private IStylesheetManager _stylesheetManager = default!;

    public ObserveWarningWindow()
    {
        Title = Loc.GetString("observe-warning-window-title");
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
        ApplyCrtPalette();
        var player = _playerManager.LocalSession;

        if (player != null && _adminManager.IsAdmin(player))
        {
            ObserveButton.Text = Loc.GetString("observe-as-player");
            ObserveAsAdminButton.Visible = true;
            ObserveAsAdminButton.OnPressed += _ => { this.Close(); };
        }

        ObserveButton.OnPressed += _ => { this.Close(); };
        NevermindButton.OnPressed += _ => { this.Close(); };
        _cfg.OnValueChanged(CCVars.CrtUiEnabled, OnCrtUiEnabledChanged);
        _cfg.OnValueChanged(CCVars.CrtUiColor, OnCrtUiColorChanged);
    }

    [Obsolete("Controls should only be removed from UI tree instead of being disposed")]
    protected override void Dispose(bool disposing)
    {
        base.Dispose(disposing);

        _cfg.UnsubValueChanged(CCVars.CrtUiEnabled, OnCrtUiEnabledChanged);
        _cfg.UnsubValueChanged(CCVars.CrtUiColor, OnCrtUiColorChanged);
    }

    private void OnCrtUiEnabledChanged(bool _)
    {
        ApplyCrtPalette();
    }

    private void OnCrtUiColorChanged(string _)
    {
        ApplyCrtPalette();
    }

    private void ApplyCrtPalette()
    {
        Stylesheet = _stylesheetManager.SheetNano;
        CrtLobbyTheme.ApplyWindow(this, useCrtTypography: true);
    }
}
