- type: job
  parent: AU14JobAuxSupportSynthBase
  id: AU14JobGOVFORAuxSupportSynthUPP
  spawnMenuRoleName: Support Synth (UPP)
  requirements:
  - !type:OverallPlaytimeRequirement
    time: 7200 # 2 hours
  - !type:TraitsRequirement
    inverted: true
    traits:
    - SocialAnxietyHeavy
    - FrontalLisp
    - NonResuscitable
    - Epilepsy
  ranks:
    UPP_SeniorWarrantOfficer:
    - !type:RoleTimeRequirement
      role: AU14JobGOVFORAuxSupportSynth
      time: 180000 # 50 hours
    UPP_WarrantOfficer: []
  special:
  - !type:AddComponentSpecial
    components:
    - type: Skills
      skills:
        RMCSkillCqc: 5
        RMCSkillEndurance: 1
        RMCSkillEngineer: 4
        RMCSkillConstruction: 3
        RMCSkillFirearms: 2
        RMCSkillOverwatch: 1
        RMCSkillMedical: 4
        RMCSkillSurgery: 3
        RMCSkillResearch: 1
        RMCSkillMeleeWeapons: 2
        RMCSkillPilot: 2
        RMCSkillPolice: 2
        RMCSkillFireman: 5
        RMCSkillPowerLoader: 2
        RMCSkillVehicles: 2
        RMCSkillJtac: 3
        RMCSkillIntel: 2
        RMCSkillDomestics: 2
        RMCSkillNavigations: 1
