- type: job
  parent: AU14JobSquadCombatTechBase
  id: AU14JobGOVFORSquadCombatTechUPP
  spawnMenuRoleName: Combat Tech (UPP)
  ranks:
    UPP_Corporal:
    - !type:RoleTimeRequirement
      role: AU14JobGOVFORSquadCombatTech
      time: 216000 # 60 hours
    UPP_SeniorGefreiter:
    - !type:RoleTimeRequirement
      role: AU14JobGOVFORSquadCombatTech
      time: 108000 # 30 hours
    UPP_Gefreiter:
    - !type:RoleTimeRequirement
      role: AU14JobGOVFORSquadCombatTech
      time: 54000 # 15 hours
    UPP_Private: []
