- type: job
  parent: AU14JobSquadAutomaticRiflemanBase
  id: AU14JobGOVFORSquadAutomaticRiflemanUPP
  name: Machine Gunner
  spawnMenuRoleName: Automatic Rifleman (UPP)
  ranks:
    UPP_Gefreiter:
    - !type:RoleTimeRequirement
      role: AU14JobGOVFORSquadAutomaticRifleman
      time: 108000 # 30 hours
    UPP_Private: []
  special:
  - !type:AddComponentSpecial
    components:
    - type: Skills
      skills:
        RMCSkillFirearms: 2
        RMCSkillFireman: 1
        RMCSkillJtac: 1
        RMCSkillSmartGun: 1
        RMCSkillConstruction: 2
        RMCSkillEngineer: 3
        RMCSkillPolice: 1
    - type: JobPrefix
      prefix: au14-job-prefix-AU14JobGOVFORSquadAutomaticRiflemanUPP
