- type: job
  parent: AU14JobRadioTelephoneOperatorBase
  id: AU14JobGOVFORRadioTelephoneOperatorUPP
  name: au14-job-name-radiotelephoneoperator-alt
  spawnMenuRoleName: Fireteam Leader (UPP)
  overwatchRoleName: au14-job-name-radiotelephoneoperator-alt
  ranks:
    UPP_SeniorGefreiter:
    - !type:RoleTimeRequirement
      role: AU14JobGOVFORRadioTelephoneOperator
      time: 108000 # 30 hours
    UPP_Gefreiter: []
  special:
  - !type:AddComponentSpecial
    components:
    - type: Skills
      skills:
        RMCSkillConstruction: 2
        RMCSkillEngineer: 3
        RMCSkillFirearms: 2
        RMCSkillFireman: 1
        RMCSkillJtac: 3
        RMCSkillPolice: 1
    - type: JobPrefix
      prefix: au14-job-prefix-AU14JobGOVFORRadioTelephoneOperatorUPP
