- type: job
  parent: AU14JobPlatOpBase
  id: AU14JobGOVFORPlatOpUPP
  name: Staff Officer
  spawnMenuRoleName: Junior Officer (UPP)
  ranks:
    UPP_Lieutenant:
    - !type:RoleTimeRequirement
      role: AU14JobGOVFORPlatOp
      time: 216000 # 60 hours
    UPP_JuniorLieutenant: []
  special:
  - !type:AddComponentSpecial
    components:
    - type: JobPrefix
      prefix: au14-job-prefix-AU14JobGOVFORPlatOpUPP
