- type: job
  parent: AU14JobPlatCoBase
  id: AU14JobGOVFORPlatCoUPP
  requirements: []
  name: Platoon Commander
  spawnMenuRoleName: Platoon Commander (UPP)
  ranks:
    UPP_Captain:
    - !type:RoleTimeRequirement
      role: AU14JobGOVFORPlatCo
      time: 360000 # 100 hours
    UPP_SeniorLieutenant:
    - !type:RoleTimeRequirement
      role: AU14JobGOVFORPlatCo
      time: 108000 # 30 hours
    UPP_Lieutenant: []
  special:
  - !type:AddComponentSpecial
    components:
    - type: JobPrefix
      prefix: au14-job-prefix-AU14JobGOVFORPlatCoUPP
