- type: job
  parent: AU14JobadvisorBase
  id: AU14JobGOVFORadvisorUPP
  spawnMenuRoleName: Platoon Advisor (UPP)
  ranks:
    UPP_FirstSergeant:
    - !type:RoleTimeRequirement
      role: AU14JobGOVFORadvisor
      time: 360000 # 100 hours
    UPP_Chotar: []
