- type: job
  parent: AU14JobSquadSergeantBase
  id: AU14JobGOVFORSquadSergeantUPP
  requirements: []
  spawnMenuRoleName: Squad Sergeant (UPP)
  overwatchRoleName: Squad Sergeant
  ranks:
    UPP_Plutonowy: []
  special:
  - !type:AddComponentSpecial
    components:
    - type: JobPrefix
      prefix: au14-job-prefix-AU14JobGOVFORSquadSergeantUPP
