- type: job
  parent: AU14JobSquadSergeantBase
  id: AU14JobGOVFORSquadSergeantWYPMC
  name: PMC Squad Leader
  ranks:
    AU14RankWeYuEnforcerSenior:
    - !type:RoleTimeRequirement
      role: AU14JobGOVFORSquadSergeant
      time: 108000 # 30 hours
    AU14RankWeYuEnforcer: []
  spawnMenuRoleName: Squad Sergeant (WYPMC)
  special:
  - !type:AddComponentSpecial
    components:
    - type: JobPrefix
      prefix: au14-job-prefix-AU14JobGOVFORSquadSergeantWYPMC
