- type: job
  parent: AU14JobSquadCombatTechBase
  id: AU14JobGOVFORSquadCombatTechWYPMC
  name: au14-job-name-wypmc-combattech
  spawnMenuRoleName: Combat Tech (WYPMC)
  ranks:
    AU14RankWeYuSeniorOperator:
    - !type:RoleTimeRequirement
      role: AU14JobGOVFORSquadCombatTech
      time: 108000 # 30 hours
    AU14RankWeYuOperator: []
  special:
  - !type:AddComponentSpecial
    components:
    - type: Skills
      skills:
        RMCSkillEndurance: 1
        RMCSkillFirearms: 2
        RMCSkillConstruction: 2
        RMCSkillEngineer: 3
        RMCSkillFireman: 1
        RMCSkillVehicles: 1
        RMCSkillPolice: 1
