- type: job
  parent: AU14JobRadioTelephoneOperatorBase
  id: AU14JobGOVFORRadioTelephoneOperatorWYPMC
  name: PMC Communications Specialist
  spawnMenuRoleName: Fireteam Leader (WYPMC)
  overwatchRoleName: au14-job-name-radiotelephoneoperator-alt
  ranks:
    AU14RankWeYuSeniorOperator:
    - !type:RoleTimeRequirement
      role: AU14JobGOVFORRadioTelephoneOperator
      time: 108000 # 30 hours
    AU14RankWeYuOperator: []
  special:
  - !type:AddComponentSpecial
    components:
    - type: Skills
      skills:
        RMCSkillConstruction: 2
        RMCSkillEngineer: 3
        RMCSkillFirearms: 2
        RMCSkillFireman: 1
        RMCSkillJtac: 3
        RMCSkillPolice: 1
    - type: JobPrefix
      prefix: au14-job-prefix-AU14JobGOVFORRadioTelephoneOperatorWYPMC
