- type: job
  parent: AU14JobPlatOpBase
  id: AU14JobGOVFORPlatOpWYPMC
  name: PMC Operations Adjutant
  description: au14-job-description-govforplatop
  spawnMenuRoleName: Junior Officer (WYPMC)
  ranks:
    AU14RankWeYuAdjutant: []
  special:
  - !type:AddComponentSpecial
    components:
    - type: JobPrefix
      prefix: au14-job-prefix-AU14JobGOVFORPlatOpWYPMC
