- type: job
  parent: AU14JobSquadRiflemanBase
  id: AU14JobGOVFORSquadRiflemanWYPMC
  name: PMC Contractor
  description: au14-job-description-govforsquadrifleman
  setPreference: false
  ranks:
    AU14RankWeYuSeniorOperator:
    - !type:RoleTimeRequirement
      role: AU14JobGOVFORSquadRifleman
      time: 108000 # 30 hours
    AU14RankWeYuOperator:
    - !type:RoleTimeRequirement
      role: AU14JobGOVFORSquadRifleman
      time: 1200 # 2 hours
    AU14RankWeYuRecruit: []
  startingGear: AU14GearGOVFORSquadRifleman
  dummyStartingGear: AU14GearGOVFORRiflemanDummy
  icon: "AU14JobIconRFN"
  requireAdminNotify: false
  spawnMenuRoleName: Rifleman (WYPMC)
  joinNotifyCrew: false
  supervisors: au14-job-supervisors-govfor
  accessGroups:
  - AU14GovforSquad
  hasIcon: false
  roleWeight: 0.25
  special:
  - !type:AddComponentSpecial
    components:
    - type: Skills
      skills:
        RMCSkillEndurance: 1
        RMCSkillFirearms: 2
        RMCSkillConstruction: 2
        RMCSkillEngineer: 3
        RMCSkillFireman: 1
        RMCSkillVehicles: 1
        RMCSkillPolice: 1
    - type: JobPrefix
      prefix: au14-job-prefix-AU14JobGOVFORSquadRiflemanWYPMC
    - type: TacticalMapIcon
      icon:
        sprite: /Textures/_RMC14/Interface/map_blips.rsi
        state: synth
  hidden: true
