- type: job
  parent: AU14JobPlatCoBase
  id: AU14JobGOVFORPlatCoWYPMC
  requirements: []
  name: PMC Operations Director
  spawnMenuRoleName: Platoon Commander (WYPMC)
  ranks:
    AU14RankWeYuCommanderSenior:
    - !type:RoleTimeRequirement
      role: AU14JobGOVFORPlatCo
      time: 360000 # 100 hours
    AU14RankWeYuCommander: []
  special:
  - !type:AddComponentSpecial
    components:
    - type: JobPrefix
      prefix: au14-job-prefix-AU14JobGOVFORPlatCoWYPMC
