- type: job
  parent: AU14JobSquadAutomaticRiflemanBase
  id: AU14JobGOVFORSquadAutomaticRiflemanWYPMC
  name: PMC Smartgun Operator
  spawnMenuRoleName: Automatic Rifleman (WYPMC)
  ranks:
    AU14RankWeYuSeniorOperator:
    - !type:RoleTimeRequirement
      role: AU14JobGOVFORSquadAutomaticRifleman
      time: 108000 # 30 hours
    AU14RankWeYuOperator: []
  special:
  - !type:AddComponentSpecial
    components:
    - type: Skills
      skills:
        RMCSkillFirearms: 2
        RMCSkillFireman: 1
        RMCSkillJtac: 1
        RMCSkillSmartGun: 1
        RMCSkillConstruction: 2
        RMCSkillEngineer: 3
        RMCSkillPolice: 1
    - type: JobPrefix
      prefix: au14-job-prefix-AU14JobGOVFORSquadAutomaticRiflemanWYPMC
