- type: job
  parent: AU14JobDCCBase
  id: AU14JobGOVFORDCCRMC
  name: au14-job-name-govfordccRMC
  spawnMenuRoleName: Dropship Crew Chief (TWE RMC)
  ranks:
    RMC_WarrantOfficer1:
    - !type:RoleTimeRequirement
      role: AU14JobGOVFORDCC
      time: 360000 # 100 hours
    RMC_WarrantOfficer2:
    - !type:RoleTimeRequirement
      role: AU14JobGOVFORDCC
      time: 216000 # 60 hours
    RMC_ColourSergeant:
    - !type:RoleTimeRequirement
      role: AU14JobGOVFORDCC
      time: 43200 # 12 hours
    RMC_Sergeant: []
  special:
  - !type:AddComponentSpecial
    components:
    - type: Skills
      skills:
        RMCSkillFirearms: 2
        RMCSkillFireman: 1
        RMCSkillIntel: 1
        RMCSkillJtac: 2
        RMCSkillLeadership: 1
        RMCSkillMedical: 2
        RMCSkillOverwatch: 1
        RMCSkillPilot: 2
        RMCSkillPowerLoader: 2
        RMCSkillSurgery: 1
        RMCSkillPolice: 1
