- type: job
  parent: AU14JobSquadSergeantBase
  id: AU14JobGOVFORSquadSergeantRMC
  name: au14-job-name-govforsquadsergeantRMC
  spawnMenuRoleName: Squad Sergeant (TWE RMC)
  overwatchRoleName: Team Leader
  special:
  - !type:AddComponentSpecial
    components:
    - type: JobPrefix
      prefix: au14-job-prefix-govforsquadsergeantRMC
