- type: job
  parent: AU14JobPlatoonCorpsmanBase
  id: AU14JobGOVFORPlatoonCorpsmanRMC
  name: au14-job-name-govforplatooncorpsmanRMC
  spawnMenuRoleName: Hospital Corpsman (TWE RMC)
  ranks:
    RMC_Corporal:
    - !type:RoleTimeRequirement
      role: AU14JobGOVFORPlatoonCorpsman
      time: 72000 # 20 hours
    RMC_LanceCorporal: []
  special:
  - !type:AddComponentSpecial
    components:
    - type: Skills
      skills:
        RMCSkillFirearms: 2
        RMCSkillFireman: 1
        RMCSkillJtac: 1
        RMCSkillMedical: 2
        RMCSkillSurgery: 1
        RMCSkillConstruction: 2
        RMCSkillEngineer: 3
        RMCSkillPolice: 1
