- type: job
  parent: AU14JobRadioTelephoneOperatorBase
  id: AU14JobGOVFORRadioTelephoneOperatorRMC
  name: au14-job-name-radiotelephoneoperatorRMC
  spawnMenuRoleName: Fireteam Leader (TWE RMC)
  overwatchRoleName: au14-job-name-radiotelephoneoperator-alt
  ranks:
    RMC_Corporal:
    - !type:RoleTimeRequirement
      role: AU14JobGOVFORSquadAutomaticRifleman
      time: 216000 # 60 hours
    RMC_LanceCorporal:
    - !type:RoleTimeRequirement
      role: AU14JobGOVFORSquadAutomaticRifleman
      time: 108000 # 30 hours
    RMC_Marine: []
  special:
  - !type:AddComponentSpecial
    components:
    - type: Skills
      skills:
        RMCSkillConstruction: 2
        RMCSkillEngineer: 3
        RMCSkillFirearms: 2
        RMCSkillFireman: 1
        RMCSkillJtac: 3
        RMCSkillPolice: 1
