- type: job
  parent: AU14JobadvisorBase
  id: AU14JobGOVFORadvisorRMC
  spawnMenuRoleName: Platoon Advisor (TWE RMC)
  ranks:
    RMC_WarrantOfficer1:
    - !type:RoleTimeRequirement
      role: AU14JobGOVFORadvisor
      time: 360000 # 100 hours
    RMC_WarrantOfficer2: []
