- type: job
  parent: AU14JobSquadCombatTechBase
  id: AU14JobGOVFORSquadCombatTechRMC
  name: au14-job-name-govforsquadcombattechRMC
  spawnMenuRoleName: Combat Tech (TWE RMC)
  ranks:
    RMC_Corporal:
    - !type:RoleTimeRequirement
      role: AU14JobGOVFORSquadAutomaticRifleman
      time: 216000 # 60 hours
    RMC_LanceCorporal:
    - !type:RoleTimeRequirement
      role: AU14JobGOVFORSquadAutomaticRifleman
      time: 108000 # 30 hours
    RMC_Marine: []
  special:
  - !type:AddComponentSpecial
    components:
    - type: JobPrefix
      prefix: au14-job-prefix-govforsquadcombattechRMC
