using System.Linq;
using System.Numerics;
using Content.Client.Lobby.UI;
using Content.Client.Stylesheets;
using Content.Shared.CCVar;
using Content.Shared.Ghost;
using Content.Shared.StatusIcon;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.Graphics;
using Robust.Client.Player;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Configuration;
using Robust.Shared.Prototypes;
using Robust.Shared.Timing;

namespace Content.Client.UserInterface.Systems.Ghost.Controls
{
    [GenerateTypedNameReferences]
    public sealed partial class GhostTargetWindow : DefaultWindow
    {
        [Dependency] private IEntityManager _entityManager = default!;
        [Dependency] private IConfigurationManager _cfg = default!;
        [Dependency] private IPrototypeManager _prototypeManager = default!;
        [Dependency] private IPlayerManager _playerManager = default!;
        [Dependency] private IStylesheetManager _stylesheetManager = default!;
        [Dependency] private IUserInterfaceManager _uiManager = default!;

        private SpriteSystem? _spriteSystem;
        private readonly List<TabState> _tabs = new();
        private readonly List<RowState> _rows = new();
        private readonly List<SectionState> _sections = new();
        private readonly List<EntityUid> _previewDummies = new();
        private TabState? _activeTab;
        private List<GhostWarp> _warps = new();
        private string _searchText = string.Empty;
        private WarpRowDensity _rowDensity = WarpRowDensity.Standard;
        private static readonly Comparer<string> OrdinalComparer = Comparer<string>.Create(
            (x, y) => string.Compare(x, y, StringComparison.Ordinal));

        public event Action<NetEntity>? WarpClicked;
        public event Action? OnGhostnadoClicked;

        public GhostTargetWindow()
        {
            IoCManager.InjectDependencies(this);

            RobustXamlLoader.Load(this);
            ApplyCrtPalette();
            SearchBar.OnTextChanged += OnSearchTextChanged;

            GhostnadoButton.OnPressed += _ => OnGhostnadoClicked?.Invoke();
            _cfg.OnValueChanged(CCVars.CrtUiEnabled, OnCrtUiEnabledChanged);
            _cfg.OnValueChanged(CCVars.CrtUiColor, OnCrtUiColorChanged);
        }

        private void OnCrtUiEnabledChanged(bool _)
        {
            OnCrtUiColorChanged(string.Empty);
        }

        private void OnCrtUiColorChanged(string _)
        {
            ApplyCrtPalette();
            Timer.Spawn(0, () =>
            {
                if (!Disposed)
                    ApplyCrtPalette();
            });
        }

        private void ApplyCrtPalette()
        {
            Stylesheet = _stylesheetManager.SheetNano;
            CrtLobbyTheme.ApplyWindow(this, useCrtTypography: true);
            RefreshGeneratedPaletteState();
        }

        private void RefreshGeneratedPaletteState()
        {
            if (!GhostnadoButton.HasStyleClass(StyleNano.StyleClassCrtAttentionButton))
                GhostnadoButton.AddStyleClass(StyleNano.StyleClassCrtAttentionButton);

            foreach (var tab in _tabs)
            {
                CrtLobbyTheme.Apply(tab.Button);
            }

            foreach (var row in _rows)
            {
                CrtLobbyTheme.Apply(row.Button);
            }

            SetActiveTab(_activeTab);
        }

        public void UpdateWarps(IEnumerable<GhostWarp> warps)
        {
            _warps = warps
                .OrderBy(w => GetTabOrder(GetTabName(w)))
                .ThenBy(w => GetTabName(w), OrdinalComparer)
                .ThenBy(w => GetSectionOrder(GetSectionName(w)))
                .ThenBy(w => GetSectionName(w), OrdinalComparer)
                .ThenByDescending(w => w.SortWeight)
                .ThenBy(w => GetRoleName(w), OrdinalComparer)
                .ThenBy(w => w.DisplayName, OrdinalComparer)
                .ToList();
        }

        public void Populate()
        {
            var previousTab = _activeTab?.Name;
            ClearPreviewDummies();
            FactionTabBar.DisposeAllChildren();
            TabContentRoot.DisposeAllChildren();
            _tabs.Clear();
            _rows.Clear();
            _sections.Clear();
            _activeTab = null;
            _rowDensity = GetRowDensity(_warps
                .GroupBy(GetTabName)
                .Select(group => group.Count())
                .DefaultIfEmpty(0)
                .Max());

            foreach (var tabGroup in _warps.GroupBy(GetTabName))
            {
                AddTab(tabGroup.Key, tabGroup.ToList());
            }

            if (_tabs.Count > 0)
            {
                var tab = _tabs.FirstOrDefault(tab => tab.Name == previousTab) ?? _tabs[0];
                SetActiveTab(tab);
            }

            CrtLobbyTheme.ApplyWindow(this, useCrtTypography: true);
            UpdateVisibleRows();
        }

        private void AddTab(string tabName, List<GhostWarp> warps)
        {
            var scroll = new ScrollContainer
            {
                HorizontalExpand = true,
                VerticalExpand = true,
                HScrollEnabled = false,
            };

            var tabTitle = GetTabTitle(tabName, warps.Count, warps.Count);
            var tabButton = new Button
            {
                Text = tabTitle,
                HorizontalExpand = true,
                SizeFlagsStretchRatio = 1,
                ClipText = true,
                MinWidth = GetTabMinWidth(tabTitle),
                MinHeight = 28,
                TextAlign = Label.AlignMode.Center,
                ToolTip = $"{tabName} ({warps.Count})",
            };

            var container = new BoxContainer
            {
                Orientation = BoxContainer.LayoutOrientation.Vertical,
                SeparationOverride = 8,
                Margin = new Thickness(8),
                HorizontalExpand = true,
                VerticalExpand = true,
            };

            scroll.AddChild(container);
            scroll.Visible = false;

            var tab = new TabState(tabName, tabButton, scroll, warps.Count);
            _tabs.Add(tab);
            tabButton.OnPressed += _ => SetActiveTab(tab);

            AddTabHeader(container, tabName, warps.Count);

            foreach (var sectionGroup in warps.GroupBy(GetSectionName)
                         .OrderBy(group => GetSectionOrder(group.Key))
                         .ThenBy(group => group.Key, OrdinalComparer))
            {
                AddSection(tab, container, sectionGroup.Key, sectionGroup.ToList());
            }

            FactionTabBar.AddChild(tabButton);
            TabContentRoot.AddChild(scroll);
        }

        private void AddTabHeader(BoxContainer container, string tabName, int count)
        {
            var header = new PanelContainer
            {
                StyleClasses = { StyleNano.StyleClassCrtHeaderPanel },
                HorizontalExpand = true,
            };

            var headerBox = new BoxContainer
            {
                Orientation = BoxContainer.LayoutOrientation.Horizontal,
                SeparationOverride = 8,
                Margin = new Thickness(8, 6),
                HorizontalExpand = true,
            };

            headerBox.AddChild(new Label
            {
                Text = tabName.ToUpperInvariant(),
                StyleClasses = { StyleNano.StyleClassCrtHeading },
                HorizontalExpand = true,
            });

            headerBox.AddChild(new Label
            {
                Text = Loc.GetString("ghost-target-window-tracked-count", ("count", count)),
                StyleClasses = { StyleNano.StyleClassCrtDimText },
                Align = Label.AlignMode.Right,
                VerticalAlignment = VAlignment.Center,
            });

            header.AddChild(headerBox);
            container.AddChild(header);
        }

        private void AddSection(TabState tab, BoxContainer tabContainer, string sectionName, List<GhostWarp> warps)
        {
            var sectionContainer = new BoxContainer
            {
                Orientation = BoxContainer.LayoutOrientation.Vertical,
                SeparationOverride = 6,
                HorizontalExpand = true,
            };

            var header = CreateSectionHeader(sectionName, warps.Count, out var countLabel);
            var section = new SectionState(sectionContainer, countLabel);
            _sections.Add(section);
            tab.Sections.Add(section);

            sectionContainer.AddChild(header);

            foreach (var warp in warps)
            {
                var row = CreateWarpRow(warp, _rowDensity);
                var rowState = new RowState(warp, row);
                section.Rows.Add(rowState);
                _rows.Add(rowState);
                sectionContainer.AddChild(row);
            }

            tabContainer.AddChild(sectionContainer);
        }

        private Control CreateSectionHeader(string sectionName, int count, out Label countLabel)
        {
            var panel = new PanelContainer
            {
                StyleClasses = { StyleNano.StyleClassCrtHeaderPanel },
                HorizontalExpand = true,
            };

            var box = new BoxContainer
            {
                Orientation = BoxContainer.LayoutOrientation.Horizontal,
                Margin = new Thickness(8, 4),
                HorizontalExpand = true,
            };

            box.AddChild(new Label
            {
                Text = sectionName.ToUpperInvariant(),
                StyleClasses = { StyleNano.StyleClassCrtHeading },
                HorizontalExpand = true,
            });

            countLabel = new Label
            {
                Text = count.ToString(),
                StyleClasses = { StyleNano.StyleClassCrtDimText },
                Align = Label.AlignMode.Right,
            };

            box.AddChild(countLabel);

            panel.AddChild(box);
            return panel;
        }

        private Button CreateWarpRow(GhostWarp warp, WarpRowDensity density)
        {
            var button = new Button
            {
                HorizontalExpand = true,
                MinSize = new Vector2(0, GetRowHeight(density)),
                Margin = new Thickness(0, 1),
                ToolTip = Loc.GetString("ghost-target-window-current-button", ("name", GetSearchText(warp))),
            };

            var backing = new PanelContainer
            {
                HorizontalExpand = true,
                StyleClasses = { StyleNano.StyleClassCrtInsetPanel },
            };

            var row = new BoxContainer
            {
                Orientation = BoxContainer.LayoutOrientation.Horizontal,
                SeparationOverride = GetRowSeparation(density),
                Margin = GetRowMargin(density),
                HorizontalExpand = true,
            };

            row.AddChild(CreatePreview(warp, density));

            var textBox = new BoxContainer
            {
                Orientation = BoxContainer.LayoutOrientation.Vertical,
                HorizontalExpand = true,
                VerticalAlignment = VAlignment.Center,
            };

            var nameLabel = new Label
            {
                Text = warp.DisplayName,
                ClipText = true,
                HorizontalExpand = true,
            };
            if (density != WarpRowDensity.Dense)
                nameLabel.StyleClasses.Add(StyleNano.StyleClassCrtHeading);

            textBox.AddChild(nameLabel);

            textBox.AddChild(new Label
            {
                Text = GetRowSubtitle(warp),
                ClipText = true,
                HorizontalExpand = true,
                StyleClasses = { StyleNano.StyleClassCrtDimText },
            });

            row.AddChild(textBox);

            if (!warp.IsWarpPoint && warp.SortWeight > 0)
            {
                row.AddChild(new Label
                {
                    Text = warp.SortWeight.ToString(),
                    Align = Label.AlignMode.Right,
                    StyleClasses = { StyleNano.StyleClassCrtDimText },
                    VerticalAlignment = VAlignment.Center,
                    MinWidth = GetWeightWidth(density),
                });
            }

            backing.AddChild(row);
            button.AddChild(backing);
            button.OnPressed += _ => WarpClicked?.Invoke(warp.Entity);
            CrtLobbyTheme.Apply(button);
            return button;
        }

        private Control CreatePreview(GhostWarp warp, WarpRowDensity density)
        {
            var frame = new PanelContainer
            {
                MinSize = GetPreviewFrameSize(density),
                StyleClasses = { StyleNano.StyleClassCrtPanel },
            };

            Control icon;
            EntityUid? target = null;
            if (!warp.IsWarpPoint &&
                _entityManager.TryGetEntity(warp.Entity, out var targetEntity))
            {
                target = targetEntity.Value;
            }

            if (target is { } targetUid &&
                _entityManager.HasComponent<SpriteComponent>(targetUid) &&
                GhostPreviewHelper.CanUseLiveSprite(_entityManager, _playerManager, targetUid))
            {
                icon = CreateSpritePreview(targetUid, density);
            }
            else if (!string.IsNullOrWhiteSpace(warp.EntityPrototype))
            {
                var preview = new EntityPrototypeView
                {
                    SetSize = GetPreviewViewportSize(density),
                    Stretch = SpriteView.StretchMode.Fit,
                    Scale = GetPreviewSpriteScale(density),
                };
                preview.SetPrototype(warp.EntityPrototype);
                icon = preview;
            }
            else if (target is { } previewSource &&
                     GhostPreviewHelper.TryCreateJobPreviewDummy(
                         _uiManager,
                         _prototypeManager,
                         _entityManager,
                         previewSource,
                         warp.JobPrototype,
                         warp.DisplayName,
                         out var dummy))
            {
                _previewDummies.Add(dummy);
                icon = CreateSpritePreview(dummy, density);
            }
            else if (!string.IsNullOrWhiteSpace(warp.IconPrototype) &&
                     _prototypeManager.TryIndex<JobIconPrototype>(warp.IconPrototype, out var jobIcon))
            {
                icon = new TextureRect
                {
                    Texture = (_spriteSystem ??= _entityManager.System<SpriteSystem>()).Frame0(jobIcon.Icon),
                    TextureScale = GetJobIconScale(density),
                    Stretch = TextureRect.StretchMode.KeepCentered,
                    SetSize = GetPreviewViewportSize(density),
                };
            }
            else
            {
                icon = new Label
                {
                    Text = GetFallbackIcon(warp),
                    StyleClasses = { StyleNano.StyleClassCrtHeading },
                    Align = Label.AlignMode.Center,
                    VerticalAlignment = VAlignment.Center,
                    HorizontalAlignment = HAlignment.Center,
                };
            }

            frame.AddChild(icon);
            CrtLobbyTheme.Apply(frame);
            return frame;
        }

        private SpriteView CreateSpritePreview(EntityUid uid, WarpRowDensity density)
        {
            var preview = new SpriteView
            {
                SetSize = GetPreviewViewportSize(density),
                OverrideDirection = Direction.South,
                Stretch = SpriteView.StretchMode.Fit,
                Scale = GetPreviewSpriteScale(density),
            };
            preview.SetEntity(uid);
            return preview;
        }

        private void ClearPreviewDummies()
        {
            foreach (var dummy in _previewDummies)
            {
                _entityManager.DeleteEntity(dummy);
            }

            _previewDummies.Clear();
        }

        [Obsolete("Controls should only be removed from UI tree instead of being disposed")]
        protected override void Dispose(bool disposing)
        {
            base.Dispose(disposing);

            if (!disposing)
                return;

            _cfg.UnsubValueChanged(CCVars.CrtUiColor, OnCrtUiColorChanged);
            _cfg.UnsubValueChanged(CCVars.CrtUiEnabled, OnCrtUiEnabledChanged);
            ClearPreviewDummies();
        }

        private static WarpRowDensity GetRowDensity(int rowCount)
        {
            return rowCount switch
            {
                >= 36 => WarpRowDensity.Dense,
                >= 20 => WarpRowDensity.Compact,
                _ => WarpRowDensity.Standard,
            };
        }

        private static float GetRowHeight(WarpRowDensity density)
        {
            return density switch
            {
                WarpRowDensity.Dense => 46,
                WarpRowDensity.Compact => 56,
                _ => 68,
            };
        }

        private static int GetRowSeparation(WarpRowDensity density)
        {
            return density switch
            {
                WarpRowDensity.Dense => 6,
                WarpRowDensity.Compact => 8,
                _ => 10,
            };
        }

        private static Thickness GetRowMargin(WarpRowDensity density)
        {
            return density switch
            {
                WarpRowDensity.Dense => new Thickness(6, 4),
                WarpRowDensity.Compact => new Thickness(7, 5),
                _ => new Thickness(8, 6),
            };
        }

        private static Vector2 GetPreviewFrameSize(WarpRowDensity density)
        {
            return density switch
            {
                WarpRowDensity.Dense => new Vector2(36, 36),
                WarpRowDensity.Compact => new Vector2(44, 44),
                _ => new Vector2(56, 56),
            };
        }

        private static Vector2 GetPreviewViewportSize(WarpRowDensity density)
        {
            return density switch
            {
                WarpRowDensity.Dense => new Vector2(34, 34),
                WarpRowDensity.Compact => new Vector2(40, 40),
                _ => new Vector2(52, 52),
            };
        }

        private static Vector2 GetPreviewSpriteScale(WarpRowDensity density)
        {
            return density switch
            {
                WarpRowDensity.Dense => new Vector2(0.9f, 0.9f),
                WarpRowDensity.Compact => new Vector2(1f, 1f),
                _ => new Vector2(1.15f, 1.15f),
            };
        }

        private static Vector2 GetJobIconScale(WarpRowDensity density)
        {
            return density switch
            {
                WarpRowDensity.Dense => new Vector2(1.35f, 1.35f),
                WarpRowDensity.Compact => new Vector2(1.6f, 1.6f),
                _ => new Vector2(2, 2),
            };
        }

        private static float GetWeightWidth(WarpRowDensity density)
        {
            return density == WarpRowDensity.Dense ? 18 : 24;
        }

        private bool WarpIsVisible(GhostWarp warp)
        {
            return string.IsNullOrWhiteSpace(_searchText) ||
                   GetSearchText(warp).Contains(_searchText, StringComparison.OrdinalIgnoreCase);
        }

        private void UpdateVisibleRows()
        {
            foreach (var row in _rows)
            {
                row.Button.Visible = WarpIsVisible(row.Warp);
            }

            TabState? firstVisibleTab = null;
            var anyVisibleTabs = false;

            foreach (var tab in _tabs)
            {
                var visibleInTab = 0;

                foreach (var section in tab.Sections)
                {
                    var visibleInSection = section.Rows.Count(row => row.Button.Visible);
                    visibleInTab += visibleInSection;
                    section.Container.Visible = visibleInSection > 0;
                    section.CountLabel.Text = GetCountText(visibleInSection, section.Rows.Count);
                }

                var tabVisible = visibleInTab > 0;
                tab.Button.Visible = tabVisible;
                var tabTitle = GetTabTitle(tab.Name, visibleInTab, tab.TotalCount);
                tab.Button.Text = tabTitle;
                tab.Button.MinWidth = GetTabMinWidth(tabTitle);
                tab.Scroll.SetScrollValue(Vector2.Zero);

                if (!tabVisible)
                    continue;

                anyVisibleTabs = true;
                firstVisibleTab ??= tab;
            }

            if (_activeTab == null || !_activeTab.Button.Visible)
                SetActiveTab(firstVisibleTab);
            else
                SetActiveTab(_activeTab);

            TabBarScroll.Visible = anyVisibleTabs;
            ContentPanel.Visible = anyVisibleTabs;
            EmptyLabel.Text = string.IsNullOrWhiteSpace(_searchText)
                ? Loc.GetString("ghost-target-window-empty")
                : Loc.GetString("ghost-target-window-no-results");
            EmptyLabel.Visible = !anyVisibleTabs;
        }

        private void SetActiveTab(TabState? activeTab)
        {
            _activeTab = activeTab;

            foreach (var tab in _tabs)
            {
                var active = tab == activeTab && tab.Button.Visible;
                tab.Scroll.Visible = active;
                if (active)
                {
                    if (!tab.Button.HasStyleClass(StyleNano.StyleClassCrtAttentionButton))
                        tab.Button.AddStyleClass(StyleNano.StyleClassCrtAttentionButton);
                }
                else
                {
                    tab.Button.RemoveStyleClass(StyleNano.StyleClassCrtAttentionButton);
                }

                tab.Button.Modulate = active
                    ? Color.White
                    : StyleNano.CrtGreenDim;
            }
        }

        private static int GetTabOrder(string tab)
        {
            return tab switch
            {
                "Military" => 0,
                "Xenos" => 1,
                "Survivors" => 2,
                "WeYa/PMC" => 3,
                "CLF" => 4,
                "SPP" => 5,
                "TSE/Royal" => 6,
                "CMB/Provost" => 7,
                "Locations" => 98,
                "Other" => 99,
                _ => 50,
            };
        }

        private static int GetSectionOrder(string section)
        {
            if (section == "Queen")
                return 0;

            if (section.StartsWith("Tier ", StringComparison.OrdinalIgnoreCase) &&
                int.TryParse(section["Tier ".Length..], out var tier))
            {
                return 10 - tier;
            }

            return section switch
            {
                "High Command" => 0,
                "Command" => 1,
                "Specialists" => 2,
                "Line Personnel" => 3,
                "Personnel" => 4,
                "Warp Points" => 0,
                _ => 10,
            };
        }

        private static string GetTabName(GhostWarp warp)
        {
            if (!string.IsNullOrWhiteSpace(warp.Tab))
                return warp.Tab;

            return warp.IsWarpPoint
                ? "Locations"
                : "Other";
        }

        private static string GetSectionName(GhostWarp warp)
        {
            if (!string.IsNullOrWhiteSpace(warp.Section))
                return warp.Section;

            return warp.IsWarpPoint
                ? "Warp Points"
                : "Personnel";
        }

        private static string GetRoleName(GhostWarp warp)
        {
            if (warp.IsWarpPoint)
                return Loc.GetString("ghost-target-window-location-role");

            return !string.IsNullOrWhiteSpace(warp.RoleName)
                ? warp.RoleName
                : Loc.GetString("generic-unknown-title");
        }

        private static string GetFallbackIcon(GhostWarp warp)
        {
            if (warp.IsWarpPoint)
                return "LOC";

            if (warp.IsXeno)
                return "X";

            var role = GetRoleName(warp);
            var letters = role
                .Split(' ', StringSplitOptions.RemoveEmptyEntries)
                .Take(2)
                .Select(word => char.ToUpperInvariant(word[0]))
                .ToArray();

            return letters.Length == 0 ? "?" : new string(letters);
        }

        private static string GetRowSubtitle(GhostWarp warp)
        {
            var role = GetRoleName(warp);
            var section = GetSectionName(warp);

            if (warp.IsWarpPoint || role == section)
                return role;

            return $"{role} - {section}";
        }

        private static string GetSearchText(GhostWarp warp)
        {
            return $"{warp.DisplayName} {GetRoleName(warp)} {GetTabName(warp)} {GetSectionName(warp)}";
        }

        private static string GetTabTitle(string tab, int visible, int total)
        {
            var label = tab.ToUpperInvariant();
            return visible == total
                ? $"{label} {total}"
                : $"{label} {visible}/{total}";
        }

        private static float GetTabMinWidth(string title)
        {
            return Math.Max(96, (title.Length * 9) + 32);
        }

        private string GetCountText(int visible, int total)
        {
            if (string.IsNullOrWhiteSpace(_searchText) || visible == total)
                return total.ToString();

            return $"{visible}/{total}";
        }

        private void OnSearchTextChanged(LineEdit.LineEditEventArgs args)
        {
            _searchText = args.Text;

            UpdateVisibleRows();
        }

        private enum WarpRowDensity : byte
        {
            Standard,
            Compact,
            Dense,
        }

        private sealed partial class SectionState
        {
            public readonly BoxContainer Container;
            public readonly Label CountLabel;
            public readonly List<RowState> Rows = new();

            public SectionState(BoxContainer container, Label countLabel)
            {
                Container = container;
                CountLabel = countLabel;
            }
        }

        private sealed partial class TabState
        {
            public readonly string Name;
            public readonly Button Button;
            public readonly ScrollContainer Scroll;
            public readonly int TotalCount;
            public readonly List<SectionState> Sections = new();

            public TabState(string name, Button button, ScrollContainer scroll, int totalCount)
            {
                Name = name;
                Button = button;
                Scroll = scroll;
                TotalCount = totalCount;
            }
        }

        private sealed partial class RowState
        {
            public readonly GhostWarp Warp;
            public readonly Button Button;

            public RowState(GhostWarp warp, Button button)
            {
                Warp = warp;
                Button = button;
            }
        }
    }
}
