using System;
using System.Collections.Generic;
using Content.Client.Lobby.UI;
using Content.Client.Stylesheets;
using Content.Shared.CCVar;
using Content.Shared.Database;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Configuration;
using Robust.Shared.Localization;

namespace Content.Client._RMC14.Commendations;

[GenerateTypedNameReferences]
public sealed partial class CommendationsWindow : DefaultWindow
{
    [Dependency] private IConfigurationManager _cfg = default!;
    [Dependency] private ILocalizationManager _loc = default!;
    [Dependency] private IStylesheetManager _stylesheetManager = default!;

    private readonly Dictionary<CommendationType, ScrollContainer> _tabContainers = new();

    public CommendationsWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        ApplyCrtPalette();
        InitializeTabs();
        _cfg.OnValueChanged(CCVars.CrtUiColor, OnCrtUiColorChanged);
    }

    [Obsolete("Controls should only be removed from UI tree instead of being disposed")]
    protected override void Dispose(bool disposing)
    {
        base.Dispose(disposing);

        _cfg.UnsubValueChanged(CCVars.CrtUiColor, OnCrtUiColorChanged);
    }

    private void OnCrtUiColorChanged(string _)
    {
        ApplyCrtPalette();
    }

    private void ApplyCrtPalette()
    {
        Stylesheet = _stylesheetManager.SheetNano;
        CrtLobbyTheme.Apply(this);
    }

    private void InitializeTabs()
    {
        // Create tab for each CommendationType enum value
        foreach (CommendationType type in Enum.GetValues<CommendationType>())
        {
            var tabName = GetCommendationTypeName(type);

            // Create scroll container for this tab
            var scrollContainer = new ScrollContainer
            {
                HScrollEnabled = false,
                VScrollEnabled = true,
                VerticalExpand = true,
                HorizontalExpand = true
            };

            var boxContainer = new BoxContainer
            {
                Orientation = BoxContainer.LayoutOrientation.Vertical,
                HorizontalExpand = true,
                SeparationOverride = 6,
                Margin = new Thickness(8)
            };

            scrollContainer.AddChild(boxContainer);
            _tabContainers[type] = scrollContainer;


            TabContainer.AddChild(scrollContainer);
            TabContainer.SetTabTitle(TabContainer.ChildCount - 1, tabName);
        }
    }

    public void AddCommendation(CommendationType type, Control control)
    {
        if (_tabContainers.TryGetValue(type, out var scrollContainer))
        {
            var boxContainer = (BoxContainer)scrollContainer.GetChild(0);
            boxContainer.AddChild(control);
            CrtLobbyTheme.Apply(control);
        }
    }

    private string GetCommendationTypeName(CommendationType type)
    {
        // Try to get localized name, fallback to enum name
        var locKey = $"rmc-commendation-type-{type.ToString().ToLower()}";
        var localized = _loc.TryGetString(locKey, out var result) ? result : type.ToString();
        return localized;
    }
}
