using Content.Client._RMC14.Language.Systems;
using System.Linq;
using Content.Shared._RMC14.Language.Prototypes;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Client.Graphics;
using Robust.Shared.IoC;
using Robust.Shared.Prototypes;
using Robust.Shared.ContentPack;
using Robust.Client.UserInterface;
using System.Numerics;
using Robust.Shared.Input;

namespace Content.Client._RMC14.UserInterface.Systems.Language;

[GenerateTypedNameReferences]
public sealed partial class LanguageMenuWindow : DefaultWindow
{
    [Dependency] private IPrototypeManager _prototypeManager = default!;
    [Dependency] private IResourceManager _resource = default!;

    private static readonly IReadOnlyDictionary<ProtoId<LanguagePrototype>, LanguageLearningViewData> EmptyLearningLanguages =
        new Dictionary<ProtoId<LanguagePrototype>, LanguageLearningViewData>();

    private static readonly StyleBoxFlat FlatTransparent = new()
    {
        BackgroundColor = Color.Transparent,
        BorderThickness = new Thickness(0)
    };

    private ProtoId<LanguagePrototype>? _currentLanguage;
    private IReadOnlySet<ProtoId<LanguagePrototype>> _knownLanguages = new HashSet<ProtoId<LanguagePrototype>>();
    private IReadOnlyDictionary<ProtoId<LanguagePrototype>, LanguageLearningViewData> _learningLanguages = EmptyLearningLanguages;

    private readonly Dictionary<ProtoId<LanguagePrototype>, bool> _expansionStates = [];
    private readonly Dictionary<ProtoId<LanguagePrototype>, bool> _descriptionExpansionStates = [];

    private LanguageTabs _tabs = default!;
    private LanguageTab? _activeCustomTab = null;

    public event Action<ProtoId<LanguagePrototype>>? OnLanguageSelected;

    public LanguageMenuWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        _tabs = new LanguageTabs(_resource);

        SetupTabs();
        SetupStyling();
        SetupSearch();
        RebuildTabStrip();
    }

    private void SetupTabs()
    {
        TabContainer.SetTabTitle(KnownLanguagesTab, Loc.GetString("language-menu-known-tab"));
        TabContainer.SetTabTitle(LearningTab, Loc.GetString("language-menu-learning-tab"));
    }

    private void SetupStyling()
    {
        MainContainer.PanelOverride = FlatTransparent;
        ContentContainer.PanelOverride = FlatTransparent;
        KnownLanguagesContainer.PanelOverride = FlatTransparent;
        LearningLanguagesContainer.PanelOverride = FlatTransparent;
        TabContainer.PanelStyleBoxOverride = FlatTransparent;
    }

    private void SetupSearch()
    {
        SearchBar.OnTextChanged += _ => RebuildKnownList();
    }

    private void RebuildTabStrip()
    {
        TabStrip.RemoveAllChildren();

        var allBtn = new Button
        {
            Text = "All",
            ToggleMode = true,
            Pressed = _activeCustomTab == null,
            HorizontalExpand = true,
        };
        allBtn.OnPressed += _ =>
        {
            _activeCustomTab = null;
            RebuildTabStrip();
            RebuildKnownList();
        };
        TabStrip.AddChild(allBtn);

        foreach (var tab in _tabs.Tabs)
        {
            var capturedTab = tab;
            var btn = new Button
            {
                Text = tab.Name,
                ToggleMode = true,
                Pressed = _activeCustomTab == tab,
                MinWidth = 60,
            };
            btn.OnPressed += _ =>
            {
                _activeCustomTab = capturedTab;
                RebuildTabStrip();
                RebuildKnownList();
            };
            btn.OnKeyBindDown += args =>
            {
                if (args.Function != EngineKeyFunctions.UIRightClick)
                    return;
                ShowTabContextMenu(capturedTab);
            };
            TabStrip.AddChild(btn);
        }

        var addBtn = new Button { Text = "+", MinWidth = 28, ToolTip = "New tab" };
        addBtn.OnPressed += _ => ShowNewTabDialog();
        TabStrip.AddChild(addBtn);
    }

    private void ShowTabContextMenu(LanguageTab tab)
    {
        var popup = new Popup();
        var box = new BoxContainer { Orientation = BoxContainer.LayoutOrientation.Vertical };

        var renameBtn = new Button { Text = "Rename" };
        renameBtn.OnPressed += _ =>
        {
            popup.Orphan();
            ShowRenameTabDialog(tab);
        };

        var deleteBtn = new Button { Text = "Delete tab" };
        deleteBtn.OnPressed += _ =>
        {
            popup.Orphan();
            _tabs.RemoveTab(tab);
            if (_activeCustomTab == tab)
                _activeCustomTab = null;
            RebuildTabStrip();
            RebuildKnownList();
        };

        box.AddChild(renameBtn);
        box.AddChild(deleteBtn);
        popup.AddChild(box);
        UserInterfaceManager.ModalRoot.AddChild(popup);
        popup.Open(UIBox2.FromDimensions(UserInterfaceManager.MousePositionScaled.Position, new Vector2(120, 60)));
    }

    private void ShowNewTabDialog(string defaultName = "")
    {
        ShowNameDialog("New tab", defaultName, name =>
        {
            var tab = _tabs.AddTab(name);
            _activeCustomTab = tab;
            RebuildTabStrip();
            RebuildKnownList();
        });
    }

    private void ShowRenameTabDialog(LanguageTab tab)
    {
        ShowNameDialog("Rename tab", tab.Name, name =>
        {
            _tabs.RenameTab(tab, name);
            RebuildTabStrip();
        });
    }

    private void ShowNameDialog(string title, string defaultValue, Action<string> onConfirm)
    {
        var dialog = new DefaultWindow { Title = title, SetSize = new Vector2(280, 140) };
        var box = new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Vertical,
            Margin = new Thickness(8),
            SeparationOverride = 6,
        };

        var input = new LineEdit { Text = defaultValue, HorizontalExpand = true };
        var confirmBtn = new Button { Text = "OK", HorizontalExpand = true, Margin = new Thickness(0, 4, 0, 0) };

        confirmBtn.OnPressed += _ =>
        {
            var name = input.Text.Trim();
            if (name.Length > 0)
                onConfirm(name);
            dialog.Close();
        };

        input.OnTextEntered += _ =>
        {
            var name = input.Text.Trim();
            if (name.Length > 0)
                onConfirm(name);
            dialog.Close();
        };

        box.AddChild(input);
        box.AddChild(confirmBtn);
        dialog.Contents.AddChild(box);
        dialog.OpenCentered();
        input.GrabKeyboardFocus();
    }

    public void UpdateLanguages(
        ProtoId<LanguagePrototype> currentLanguage,
        IReadOnlySet<ProtoId<LanguagePrototype>> knownLanguages,
        IReadOnlyDictionary<ProtoId<LanguagePrototype>, LanguageLearningViewData> learningLanguages)
    {
        _currentLanguage = currentLanguage;
        _knownLanguages = knownLanguages;
        _learningLanguages = learningLanguages;

        RebuildKnownList();

        var sortedLearning = GetSortedLearningLanguages();
        UpdateLearningTab(sortedLearning);

        var hasLearning = sortedLearning.Count > 0;
        TabContainer.SetTabVisible(LearningTab, hasLearning);
        if (!hasLearning)
            TabContainer.CurrentTab = 0;
    }

    private void RebuildKnownList()
    {
        KnownLanguageList.RemoveAllChildren();

        var search = SearchBar.Text.Trim().ToLowerInvariant();

        IEnumerable<ProtoId<LanguagePrototype>> filtered = _activeCustomTab != null
            ? _knownLanguages.Where(l => _activeCustomTab.Languages.Contains(l.Id))
            : _knownLanguages;

        filtered = filtered
            .Where(lang => _prototypeManager.TryIndex<LanguagePrototype>(lang, out var p) && !p.IsInvisibleLanguage)
            .Where(lang =>
            {
                if (string.IsNullOrEmpty(search))
                    return true;
                return _prototypeManager.TryIndex<LanguagePrototype>(lang, out var p) &&
                       p.LocalizedName.ToLowerInvariant().Contains(search);
            })
            .OrderBy(lang => _prototypeManager.Index<LanguagePrototype>(lang).LocalizedName);

        foreach (var languageId in filtered)
        {
            if (!_prototypeManager.TryIndex<LanguagePrototype>(languageId, out var proto))
                continue;

            var row = new BoxContainer
            {
                Orientation = BoxContainer.LayoutOrientation.Horizontal,
                HorizontalExpand = true,
                SeparationOverride = 2,
            };

            var capturedId = languageId;

            // tab assign button
            var tabsContaining = _tabs.GetTabsContaining(languageId.Id);
            var tabBtn = new Button
            {
                Text = tabsContaining.Count > 0 ? "[*]" : "[+]",
                MinWidth = 28,
                MaxWidth = 28,
                ToolTip = "Add/remove from tabs",
            };
            tabBtn.OnPressed += _ => ShowLanguageTabMenu(capturedId, tabBtn);
            row.AddChild(tabBtn);

            var button = new LanguageButton(proto, languageId == _currentLanguage);
            button.HorizontalExpand = true;
            button.OnPressed += _ => OnLanguageSelected?.Invoke(capturedId);

            if (_descriptionExpansionStates.GetValueOrDefault(languageId, false))
                button.SetDescriptionExpanded(true);

            button.OnDescriptionExpansionChanged += (langId, expanded) =>
                _descriptionExpansionStates[langId] = expanded;

            row.AddChild(button);
            KnownLanguageList.AddChild(row);
        }

        if (!KnownLanguageList.Children.Any())
        {
            KnownLanguageList.AddChild(new Label
            {
                Text = "No languages found.",
                FontColorOverride = Color.FromHex("#888888"),
                HorizontalAlignment = HAlignment.Center,
                Margin = new Thickness(0, 12),
            });
        }
    }

    private void ShowLanguageTabMenu(ProtoId<LanguagePrototype> languageId, Control anchor)
    {
        if (_tabs.Tabs.Count == 0)
        {
            ShowNewTabDialog();
            return;
        }

        var popup = new Popup();
        var box = new BoxContainer { Orientation = BoxContainer.LayoutOrientation.Vertical };

        foreach (var tab in _tabs.Tabs)
        {
            var capturedTab = tab;
            var inTab = tab.Languages.Contains(languageId.Id);
            var btn = new Button
            {
                Text = inTab ? $"In {tab.Name}" : $"   {tab.Name}",
                HorizontalExpand = true,
                TextAlign = Label.AlignMode.Left,
            };
            btn.OnPressed += _ =>
            {
                if (inTab)
                    _tabs.RemoveLanguageFromTab(capturedTab, languageId.Id);
                else
                    _tabs.AddLanguageToTab(capturedTab, languageId.Id);
                popup.Orphan();
                RebuildKnownList();
            };
            box.AddChild(btn);
        }

        var newTabBtn = new Button { Text = "+ New tab", TextAlign = Label.AlignMode.Left };
        newTabBtn.OnPressed += _ =>
        {
            popup.Orphan();
            ShowNewTabDialog();
        };
        box.AddChild(newTabBtn);

        popup.AddChild(box);
        UserInterfaceManager.ModalRoot.AddChild(popup);
        popup.Open(UIBox2.FromDimensions(
            anchor.GlobalPosition + new Vector2(0, anchor.Height),
            new Vector2(140, _tabs.Tabs.Count * 32 + 36)));
    }

    private void UpdateLearningTab(IReadOnlyList<ProtoId<LanguagePrototype>> sortedLearningLanguages)
    {
        var existingControls = CacheExistingControls();
        LearningLanguageList.RemoveAllChildren();
        foreach (var languageId in sortedLearningLanguages)
        {
            var progressControl = CreateOrUpdateProgressControl(languageId, existingControls);
            if (progressControl != null)
                LearningLanguageList.AddChild(progressControl);
        }
    }

    private Dictionary<ProtoId<LanguagePrototype>, LanguageLearningProgressControl> CacheExistingControls()
    {
        var existing = new Dictionary<ProtoId<LanguagePrototype>, LanguageLearningProgressControl>();
        foreach (var child in LearningLanguageList.Children.OfType<LanguageLearningProgressControl>())
            existing[child.LanguageId] = child;
        return existing;
    }

    private List<ProtoId<LanguagePrototype>> GetSortedLearningLanguages()
    {
        return _learningLanguages.Keys
            .Where(IsVisibleLearnableLanguage)
            .OrderBy(lang => _prototypeManager.Index<LanguagePrototype>(lang).LocalizedName)
            .ToList();
    }

    private bool IsVisibleLearnableLanguage(ProtoId<LanguagePrototype> language)
    {
        if (!_prototypeManager.TryIndex<LanguagePrototype>(language, out var proto) || proto.IsInvisibleLanguage)
            return false;
        return !_learningLanguages.TryGetValue(language, out var data) || data.IsVisible;
    }

    private LanguageLearningProgressControl? CreateOrUpdateProgressControl(
        ProtoId<LanguagePrototype> languageId,
        Dictionary<ProtoId<LanguagePrototype>, LanguageLearningProgressControl> existingControls)
    {
        if (!_prototypeManager.TryIndex(languageId, out var proto) ||
            !_learningLanguages.TryGetValue(languageId, out var progressData))
            return null;

        if (existingControls.TryGetValue(languageId, out var existing))
        {
            existing.UpdateData(proto, progressData);
            return existing;
        }

        var control = new LanguageLearningProgressControl(proto, progressData);

        if (_expansionStates.GetValueOrDefault(languageId, false))
            control.SetExpanded(true);

        control.OnExpansionChanged += (langId, expanded) => _expansionStates[langId] = expanded;
        return control;
    }
}