using Content.Shared._AU14.Formations;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.ResourceManagement;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.IoC;

namespace Content.Client._AU14.Formations;

[GenerateTypedNameReferences]
public sealed partial class FormationMenuWindow : DefaultWindow
{
    public FormationMenuWindow()
    {
        RobustXamlLoader.Load(this);

        // Load section header icons from the AU14 texture atlas.
        var cache = IoCManager.Resolve<IResourceCache>();
        Texture? TryLoad(string path)
        {
            try { return cache.GetResource<TextureResource>(path).Texture; }
            catch { return null; }
        }

        IconStep1.Texture     = TryLoad("/Textures/_AU14/Interface/icon_step1.png");
        IconStep2.Texture     = TryLoad("/Textures/_AU14/Interface/icon_step2.png");
        IconStep3.Texture     = TryLoad("/Textures/_AU14/Interface/icon_step3.png");
        IconMode.Texture      = TryLoad("/Textures/_AU14/Interface/icon_mode.png");
        IconCollision.Texture = TryLoad("/Textures/_AU14/Interface/icon_collision.png");
        IconDebug.Texture     = TryLoad("/Textures/_AU14/Interface/icon_debug.png");
    }

    public void UpdateState(FormationMenuBuiState state)
    {
        var hasMembers = state.SlottedCount > 0;
        var hasOpenSlots = state.ActiveDotCount > 0;
        var hasPending = state.PendingDots.Count > 0;

        // Status label
        if (state.IsInPlanningMode)
        {
            StatusLabel.Text = Loc.GetString("formation-status-planning");
            StatusLabel.FontColorOverride = Color.Yellow;
        }
        else if (hasMembers)
        {
            StatusLabel.Text = Loc.GetString("formation-status-active", ("count", state.SlottedCount));
            StatusLabel.FontColorOverride = Color.LimeGreen;
        }
        else if (hasOpenSlots)
        {
            StatusLabel.Text = Loc.GetString("formation-status-open-slots", ("count", state.ActiveDotCount));
            StatusLabel.FontColorOverride = Color.Cyan;
        }
        else if (hasPending)
        {
            StatusLabel.Text = Loc.GetString("formation-status-staged");
            StatusLabel.FontColorOverride = Color.Orange;
        }
        else
        {
            StatusLabel.Text = Loc.GetString("formation-status-start");
            StatusLabel.FontColorOverride = Color.White;
        }

        // Staged marker list
        PendingDotsList.DisposeAllChildren();
        foreach (var dot in state.PendingDots)
        {
            var typeStr = Loc.GetString(dot.IsLeaderDot ? "formation-dot-type-leader" : "formation-dot-type-squad");
            var label = new Label
            {
                Text = Loc.GetString("formation-pending-dot",
                    ("type", typeStr),
                    ("x", dot.TileX),
                    ("y", dot.TileY),
                    ("facing", dot.Facing)),
                FontColorOverride = dot.IsLeaderDot ? Color.Gold : Color.Cyan,
            };
            PendingDotsList.AddChild(label);
        }
        if (!hasPending)
            PendingDotsList.AddChild(new Label { Text = Loc.GetString("formation-none-staged"), FontColorOverride = Color.DimGray });

        // Counts footer
        ActiveDotsLabel.Text = Loc.GetString("formation-counts", ("slots", state.ActiveDotCount), ("members", state.SlottedCount));

        // Dot lifetime toggle + warning
        DotLifetimeToggleButton.Text = state.ExtendedDotLifetime
            ? Loc.GetString("formation-dot-lifetime-extended")
            : Loc.GetString("formation-dot-lifetime-standard");
        LifetimeWarningBox.Visible = state.ExtendedDotLifetime;

        // Halt / March (formation starts frozen)
        HaltMarchButton.Text = state.FormationFrozen ? Loc.GetString("formation-march") : Loc.GetString("formation-halt");

        // Follow mode (active one is disabled so you can't re-click it)
        ModeHoldButton.Text = state.FollowMode == FormationFollowMode.Hold
            ? Loc.GetString("formation-hold-active")
            : Loc.GetString("formation-hold");
        ModeChaseButton.Text = state.FollowMode == FormationFollowMode.Chase
            ? Loc.GetString("formation-chase-active")
            : Loc.GetString("formation-chase");
        ModeHoldButton.Disabled  = !hasMembers || state.FollowMode == FormationFollowMode.Hold;
        ModeChaseButton.Disabled = !hasMembers || state.FollowMode == FormationFollowMode.Chase;

        // Collision toggle
        CollisionToggleButton.Text = state.CollisionsDisabled
            ? Loc.GetString("formation-collisions-off")
            : Loc.GetString("formation-collisions-on");

        // Debug button
        DebugToggleButton.Text = state.DebugShowSlots
            ? Loc.GetString("formation-hide-slots")
            : Loc.GetString("formation-show-slots");

        // Enabled states
        ConfirmButton.Disabled = !hasPending;
        CancelPlanningButton.Disabled = !hasPending && !state.IsInPlanningMode;
        UndoLastButton.Disabled = !hasPending;
        ClearAllButton.Disabled = !hasOpenSlots;
        DisbandButton.Disabled = !hasMembers && !hasOpenSlots;
        HaltMarchButton.Disabled = !hasMembers;
        CollisionToggleButton.Disabled = !hasMembers;
        DebugToggleButton.Disabled = !hasMembers;
    }
}
