lore-examinable-verb-text = Лор
lore-examinable-verb-disabled = Напомним подробнее об этом объекте.

rmc-lore-examinable-trimax-polarized-shades = Последняя линейка TriMax «TactOptix» включает улучшенную поляризацию и легкие баллистические линзы, способные выдерживать небольшие удары шрапнели. Эти очки, любимые операторами на передовой и разведчиками дальнего космоса, продаются как «проверенные в бою и одобренные к действию». Ходят слухи о том, что удачливые пользователи выживают после лазерных выстрелов с близкого расстояния благодаря многоотражающему покрытию линз, хотя официальная позиция TriMax заключается в том, чтобы «перестать стоять перед лазерами».
rmc-lore-examinable-trimex-personal-shades = Эти подделки, продаваемые как «TriMex» с буквой «E», чтобы обойти авторские права, популярны среди скупых прокладок и подражателей-задир. В то время как настоящая сделка может похвастаться запатентованным зеркальным преломлением для атомной вспышки, солнечного излучения и защитой от прицельного лазера, эти урезанные имитации едва сдерживают ультрафиолетовые лучи. А что касается знаменитой истории о лазерном пистолете, отражающемся от оригиналов? Удачи в поиске тех, кто верит, что это справится. Но эй, они дешевы, и их слоган «Экономь бюджет и выгляди круто, делая это» действительно продает их.

rmc-lore-examinable-m3-eod-pattern-heavy-armor = Эта конфигурация культовой брони была разработана во время войны между SPP и UNMC. Разработанная в ответ на необходимость более высокой защиты ComTech, назначенных в качестве EOD во время конфликта, это вершина защиты для обычного морского пехотинца. Плечи и наколенники сильно расширены, закрывая артерии на каждой конечности. Для этого костюма была разработана специальная противоосколочная подкладка, та же технология используется в бронежилете M70, разрабатываемом в то же время.
rmc-lore-examinable-armor-xm4-pattern-intel-armor = ЭГИС Совершенство. Система оповещения солдата XM4 сочетает в себе жесткую броню в стиле M4 и распределенную серию датчиков движения, прикрепленных к нагруднику. При подключении к любому оптическому интерфейсу HUD он повторяет эффекты детектора движения M314, повышая ситуационную осведомленность пользователя. В настоящее время он проходит полевые испытания сотрудниками разведки.

rmc-lore-examinable-thirteen-loko = Редкость на современном рынке, «Тринадцать Локо» — это всеземной оригинал. Этот энергетический напиток, получивший название, придуманное по общему мнению, что его могут употреблять лишь слегка безумные люди, заслужил печально известную репутацию и многочисленный культ последователей, соответствующий ему. После серии судебных разбирательств со стороны Weston-Yamada денатурированный яд кобры был исключен из рецепта, к большому разочарованию потребителей напитка.
rmc-lore-examinable-boda = Рекламная кампания BODA, задуманная еще в 2109 году, началась как попытка SPP завоевать сердца и умы колонистов и поселенцев по всей галактике. Вскоре после этого на складах ООН начали появляться вездесущие продавцы голубого цвета и большие запасы напитка, происхождение которых, казалось бы, неясно. Несмотря на некоторые опасения, после того, как первоначальное тестирование показало, что хранящиеся продукты безопасны для потребления и удивительно популярны при слепом тестировании с фокус-группами, странный избыток BODA был разрешен к использованию в колониях, связанных с ООН. Впоследствии он пользовался относительной популярностью, но в ближайшие десятилетия канул в безвестность из-за сокращения поставок.
rmc-lore-examinable-red-hot-bottle = Этот сорт пряного вкуса, предположительно созданный как нечто среднее между кетчупом и кайенским перцем, получил признание критиков во всем пространстве ООН, как в колониях, так и на судах. Внезапное и широкое распространение было любопытно совмещено с почти одновременным снятием с хранения оригинального острого соуса «ULTRA».

rmc-lore-examinable-pitchblende = Колонии по всему сектору активно добывают урановую руду. Он находит применение в устаревших реакторах деления, ядерном оружии и, чаще всего, бронебойных боеприпасах. Исследовательская группа, финансируемая WY, установила, что радиационное отравление от использования этих боеприпасов «незначительно».

rmc-lore-examinable-bottle-of-bone-gel = Костный гель – биологический синтетический аналог кости, имеющий консистенцию глины. Он способен лечить как волосяные переломы, так и сложные переломы. Костный гель не следует использовать для восстановления отсутствующей кости, поскольку он не заменяет костный мозг. Чрезмерное употребление за короткий период может вызвать острый иммунодефицит или анемию.

rmc-lore-examinable-fountain-pen = «Перьевая ручка AEGIS — это не просто инструмент для письма, она является символом отличия и авторитета в рядах Корпуса морской пехоты ООН, называемого UNMC. Это предмет наследия, вручаемый исключительно высшему командному составу, каждая ручка — дань уважения лидерству и преданности получателя.
                                    AEGIS, renowned for their weapons technology, took a different approach in crafting this piece. The fountain pen, though seemingly a departure from their usual field, is deeply ingrained with the company's engineering philosophy, embodying precision, functionality, and robustness.
                                    The golden accents are not mere embellishments; they're an identifier, setting apart these pens and their owners from the rest. The gold is meticulously alloyed with a durable metallic substance, granting it resilience to daily wear and tear. Such resilience is symbolic of the tenacity and perseverance required of UNMC command personnel.
                                    Each pen is equipped with an intricate color changing mechanism, allowing the user to switch between various ink colors. This feature, inspired by the advanced targeting systems of AEGIS' weaponry, uses miniaturized actuators and precision-ground components to smoothly transition the ink flow. A simple twist of the pen's body activates the change, rotating the internal ink cartridges into place with mechanical grace, ready for the user's command.
                                    The ink colors are not chosen arbitrarily. Each represents a different echelon within the UNMC, allowing the pen's owner to write in the hue that corresponds with their rank or the rank of the recipient of their written orders. This acts as a silent testament to the authority of their words, as if each stroke of the pen echoes through the halls of UNMC authority.
                                    Despite its ornate appearance, the pen is as robust as any AEGIS weapon, reflecting the company's commitment to reliability and durability. The metal components are corrosion-resistant, ensuring the pen's longevity, even under the challenging conditions often faced by UNMC high command.
                                    The fusion of luxury and utility, the blend of gold and metal, is an embodiment of the hard-won elegance of command, of the fusion between power and grace. It's more than a writing instrument - it's an emblem of leadership, an accolade to the dedication and strength of those who bear it. AEGIS' fountain pen stands as a monument to the precision, integrity, and courage embodied by the UNMC's highest-ranking officers."

rmc-lore-examinable-s5-red-dot-sight = Всепогодный коллиматорный прицел, получивший обозначение AN/PVQ-64 Dot Sight. Оснащен солнцезащитным козырьком для повышения прозрачности при ярком освещении и защиты от атмосферных воздействий. Компактный и эффективный, чудо военного дизайна, пока не поймешь, что на самом деле это просто готовая конструкция, получившая военное обозначение.
rmc-lore-examinable-s6-reflex-sight = Простой складной коллиматорный прицел, обозначенный как коллиматорный прицел AN/PVG-72, совместимый с большинством рельсовых систем. Громоздкий и долговечный, он может подключаться к военным HUD для ограниченных расчетов точки прицеливания.
rmc-lore-examinable-s8-4x-telescopic-scope = Прицел «Армат» средней мощности, получивший обозначение AN/PVQ-31 4x Optic. Довольно простой, но одновременно прочный и функциональный... достаточно. На самом деле 780 метров — это примерно предел, на который можно протолкнуть патрон 10х24 мм.
rmc-lore-examinable-s4-2x-telescopic-mini-scope = Легкая оптика, получившая обозначение AN/PVQ-45 2x Optic. Подходит для боевых действий на коротких и средних дистанциях. Пользователям рекомендуется часто обнулять его, поскольку первая партия массового производства имела тенденцию смещаться в том или ином направлении при длительном использовании.
rmc-lore-examinable-b8-smart-scope = Экспериментальная оптика управления огнем, способная подключаться к совместимым системам IFF на определенном оружии, получившая обозначение XAN / PVG-110 Smart Scope. Экспериментальная технология, разработанная компанией AEGIS, которая заверила, что все ранее сообщаемые проблемы с распознаванием ложноотрицательных результатов IFF были решены. На всякий случай обязательно проверяйте прицел после каждого использования.
rmc-lore-examinable-laser-sight = Стандартный лазерный модуль видимого диапазона, обозначенный как лазерный прицел AN/PEQ-42. Может быть установлен на любое огнестрельное оружие, имеющее достаточно большую нижнюю направляющую для его размещения.
rmc-lore-examinable-xm-vesg-1-flamer-nozzle = Экспериментальная насадка-генератор летучих экзотермических сфер для мусоросжигательной установки M34 была специально разработана, чтобы морские пехотинцы могли запускать огненные шары во вражеские окопы и бункеры. Несмотря на покрытие из геля и смолы, пылающий шар из нафты разрывается на части из-за сопротивления, вызванного его запуском в воздух, что заставляет морских пехотинцев использовать это приспособление в качестве импровизированной пусковой установки для фейерверков во время увольнения на берег.

rmc-lore-examinable-sasos = Новейшая оптика с поддержкой IFF, разработанная и изготовленная для системы вспомогательного вооружения L91 и получившая обозначение «умный оптический прицел для стрелкового оружия L91O1», хотя стрелки RCM ласково называют ее «соусом». Хотя серийная модель широко рассматривается ее эксплуатантами как неотъемлемая часть L91 SWS, ранние прототипы были опасно ненадежными и широко осуждались ее испытателями, что привело лишь к ограниченному использованию стрелками RCM, при этом многие из них продолжали использовать стандартную оптику 2x или 4x.

rmc-lore-examinable-hjra-12-extreme-intensity-incendiary-rocket = В этой зажигательной ракете используется экспериментальное химическое вещество, обозначенное SPP как «Р-189». Он предназначен для прорыва укреплений и бункеров, но чаще всего используется в противопехотных целях из-за чрезмерного использования и температуры после использования по назначению, оставляя после себя облако перегретого воздуха, препятствующее продвижению войск.
rmc-lore-examinable-ar10-assault-rifle = AR10 первоначально производился корпорацией Armalite (купленной Weston-Yamada в 2002 году) в 1950-х годах. Это была первая серийная винтовка, в которой было реализовано множество новых и инновационных функций, таких как газовый затвор и система держателей. Всего было произведено всего 10 000 экземпляров, и единственными национальными организациями, которые их использовали, были Португалия и Судан. С конца 20-го века эти винтовки – наряду с гораздо более распространенными M16 и AR15 – летали по менее цивилизованным областям космоса, засоряя джунгли и полы колоний своими необычными гильзовыми боеприпасами – редкость с момента появления импульсных боеприпасов. На боковой стороне этой винтовки выгравировано слово «Салазар».
rmc-lore-examinable-m54c-ap-magazine = В отличие от стандартных магазинов HEAP, эти запасные пули не имеют наконечников из обедненного урана. Вместо этого в этих патронах часть пули заменена на меньший вес, что снижает урон, но увеличивает проникающую способность и начальную скорость.

rmc-lore-examinable-xm-88-heavy-rifle = Первоначально разработан компанией AEGIS Armaments для правительства штата Большая Бразилия для использования против механизированной пехоты. Платформа оснащена бортовой компьютеризированной системой наведения, набором датчиков и электронным автоматом заряжания; эти функции работают в тандеме, уменьшая и делая инертной броню цели пользователя при последовательных попаданиях. Almayer получил небольшое количество XM88 во время подготовки к операции Swamp Hopper с UNS Nan-Shan.
rmc-lore-examinable-type-64-submachine-gun = Тип 64 попадает в руки не только солдат СПП, он активно взаимодействует с повстанческими группировками, силами корпоративной безопасности, наемниками, менее хорошо вооруженными вооруженными силами и практически со всем или со всеми, кто находится между ними.

rmc-lore-examinable-smart-gun = Интеллектуальная артиллерийская система ML66A была разработана, чтобы обеспечить отделения UNMC мобильной тяжелой огневой мощью и способностью плевать свинцом, что доказало свою необходимость на современном поле боя. Он использует новаторские технологии, созданные в результате исследований и разработок Aegis Armaments, для быстрого определения целей в полевых условиях и позволяет пользователю нацеливаться или игнорировать определенные частоты IFF на лету.
                                UNMC models are hard-wired to the IFF frequencies used by marine forces, as to avoid friendly fire incidents, and streamline use for the smart gunner in the heat of battle. Additionally, it has several motion tracking sensors built into the gun and accompanying rig able to relay any motion it detects straight to the user's HUD, allowing for even faster target acquisition.
                                Although more advanced smart guns exist, the ML66A has proven to be the perfect balance of affordability and capability for a large scale military such as the UNMC. Research on the IFF technologies required for the smart gun took several decades to complete, an endeavor partially funded by the UN to ensure it was the first nation to get its hands on the promising new technology. Although, the TSE quickly secured its own variants for use with the Royal Crown Marines.

rmc-lore-examinable-m54c-mk2 = Aegis Armaments M54C Mk2 — это стандартная винтовка, повсеместно используемая в UNMC, и воплощение настоящей винтовки космической эпохи. Платформа M54 была создана на основе десятилетий полевого опыта боевых действий в недавно открытых и разнообразных средах, которые могла предложить большая Вселенная. Выдерживать земные условия было уже недостаточно; настоящая винтовка космической эры должна была выдерживать экстремальные условия космоса.
                                The platform dominated in UNMC trials thanks to its innovative design and caseless ammunition usage. The UNMC quickly ordered a large production run of M54C Mk1s to get field feedback before committing to a new standard issue rifle. While still effective, after extended use the flaws of the Mk1 were clear; a lack of modularity combined with bulky magazines contributed to an overall lackluster performance. Aegis, not wanting to lose the contract, swiftly came up with the Mk2.
                                The M54C Mk2 improves upon the Mk1 mainly in its attachment compatibility. While the Mk1 lacked a standardized attachment mounting system, the Mk2 supported nearly every standard attachment mounting system employed by the UNMC. Additionally, the larger bulky magazines of the Mk1 were exchanged for smaller and more ergonomic magazines, improving reload times and ammunition storage efficiency.
                                Because of its effectiveness within the marine corp, the M54C Mk2 has seen adoption by several PMC groups, and even some colonial riot response teams. Its modularity and easily replaceable parts make it extremely adaptable to any given organization's needs, as well as allowing the average soldier to perform even advanced maintenance.

rmc-lore-examinable-ssg-45 = Разработанный в ответ на постоянные жалобы со стороны подразделений внутренней безопасности и ЧВК Уэстон Ямада, SSG45 является прямым результатом недовольства на местах стандартом UNMC M54C Mk2.
                            While the M54C was lightweight and easy to mass-produce, it lacked the stopping power and durability required for the kind of off-grid, high-intensity operations typically assigned to WeYa corporate teams.
                            Several units began modifying their standard-issue rifles into custom variants, unofficially dubbed M54C/2s, to improve handling, penetration, and reliability. These field modifications drew enough attention that Weston Yamada’s R&D division launched a formal weapons program to design a purpose-built rifle based on actual combat feedback.
                            The result was the SSG45: a heavy-caliber, caseless assault rifle designed for harsh environments and close-quarters superiority. It features an integrated recoil mitigation system, hardened internal components, and support for smart optics and upgraded attachments. Though still technically in field testing, the SSG45 has seen wide adoption across multiple WeYa security teams operating in high-threat zones.
                            Reports suggest the rifle performs well in sustained engagements, with only minor overheating issues during prolonged automatic fire. The R&D team is already addressing these issues in ongoing iterations.

rmc-lore-examinable-un-flag = Организация Объединенных Наций. Самая процветающая нация во вселенной. Через испытания и невзгоды, мятежи и войны Организация Объединенных Наций объединила людей Земли, людей галактики под одним знаменем. Этот баннер.
                            This is a nation worth dying for. You will triumph, you will fail, you will live, and you will die, but this flag will stand through it all. Glory to the United Nations.

rmc-lore-examinable-ceremonial-sabre = Церемониальная сабля, стандартная для командиров Корпуса морской пехоты ООН, — это больше, чем реликвия, это обряд. Выкованная из композитного сплава и отполированная до зеркального блеска, на каждой сабле выгравировано имя морского пехотинца и его подразделения после повышения до командования.
                                        While primarily used in formal ceremonies and change-of-command rituals, the blade is combat-capable, a silent reminder that in the UNMC, even tradition draws blood when necessary.
                                        Veteran officers are known to carry their sabres into battle, not for the weapon’s edge, but for what it represents: unwavering leadership in the unforgiving cold dark void of space. The sabre’s design dates back to the Old Earth naval traditions, carried forward into the stars with grim pride.
                                        Some say that if you die with it in your hand, your name is forever etched deeper into UNMC history.

rmc-lore-examinable-fax-machine =  Факс, хотя и имеет архаичное происхождение, на удивление подходит современным космическим державам.
                                    It utilizes the preexisting groundbreaking interstellar phone system to transmit documents as audio signals, which can then be decoded into the original document at the receiving fax machine.
                                    Weston-Yamada has patented the technology, resulting in other models of fax machines being far slower, and far less common.
                                    Security concerns have been raised as to the security of using the telephone system for sensitive documents, but Weston-Yamada has promised their infrastructure is extremely secure.

rmc-lore-examniable-orbital-cannon = После того, как неоднократное использование ядерного оружия во время операций UNMC с участием гражданских колоний привело как к ненужным жертвам среди гражданского населения, так и к долгосрочным экологическим катастрофам в пострадавших районах, UNMC решил, что промежуточное оружие между обычной артиллерией и ядерной взрывчаткой необходимо, чтобы избежать дальнейших ядерных инцидентов и общественного недоброжелательства.
                                    Several companies offered various prototypes to help solve this issue, including anti-ship missiles modified to target laser designations on the ground, and large low altitude conventional bombs intended to be delivered via a standard AUD-25 dropship. In the end, the UNMC decided Aegis Armament’s proposal to be most practical; a large, 400mm ship mounted artillery cannon designed to fire a variety of specially made ammunition.
                                    A vast majority of troop carrying UNMC starships were outfitted with these cannons, giving each and every marine company the capability of orbital bombardment. After widespread success in the field, several new models of orbital cannon were created to address a few major concerns with the weapon, namely the concerningly high rate of blue on blue incidents.
                                    Most notably, new models of Aegis orbital cannons are able to effectively target and fire both laser and precision GPS guided shells, vastly increasing the accuracy and reducing the risk of friendly fire. Unfortunately, these new models have yet to reach the poorly funded frontier fleets, and friendly fire incidents involving orbital bombardments are all too common.

rmc-lore-examinable-lady-fingers = Смелый маркетинговый эксперимент: эти брутальные сигареты с ментолом без фильтра выпускаются в упаковке пыльно-розового цвета, предназначенной для женщин UNMC. Запах настолько невыносимый, что их иногда используют для отпугивания насекомых от полевых палаток. Несмотря на все усилия, их выбирают редко, и в большинстве случаев они лежат нетронутыми в торговых автоматах, тихо предлагая кому-нибудь попробовать. Нравятся ли они кому-то на самом деле, это другой вопрос.
rmc-lore-examinable-kierland-electro-golds = Эти сигареты, популяризированные рабочими Novaris во время строительства главной станции, легко зажигались, горели равномерно и давали простой и надежный дым. Плоский, пыльный вкус и устойчивая тяга быстро сделали их основным продуктом колониальной эпохи. Позже Кирлан увеличил производство на приграничных фермерских мирах и заключил эксклюзивные торговые сделки с UNMC.
rmc-lore-examinable-emerald-greens = Эти сигареты, мгновенно узнаваемые по цене, которая дешевле даже воды, стали неотъемлемой частью везде, где бюджет и моральный дух иссякают. Никто точно не знает, что входит в смесь, но большинство согласны с тем, что изумрудную зелень покупают не ради вкуса.

rmc-lore-examinable-boots-07 = Большая часть журнала описывает защитную броню B18, то, как она создана, чтобы сделать современного морского пехотинца непобедимым, и что она недавно завершила испытания, что повышает ожидания руководства в отношении этой новой части снаряжения.
rmc-lore-examinable-boots-45 = В первой части статьи объясняются основные принципы обслуживания огнестрельного оружия и включена небольшая реклама известного оружейника на Станции Ворот. Во второй описаны лучшие позы для сна, положив пистолет под подушку на случай неожиданной крамольной деятельности.
rmc-lore-examinable-boots-58 = В статье описывается опыт ветеранов 1-го батальона ФОРЕКОН в Тяньцзиньской кампании и суровые условия джунглей, через которые им пришлось пройти, имея дело с СНП и местными партизанами.
rmc-lore-examinable-boots-113 = В статье подробно описаны ожесточенные городские бои, с которыми морским пехотинцам пришлось столкнуться против человеческих колонистов на Марсе в первые дни его колонизации. Когда Уэстон Ямада расширял свою территорию на красной границе, они столкнулись с вооруженным сопротивлением со стороны колонистов, которые отказались от корпоративной экспансии. ЧВК Уэстон Ямада с помощью близлежащих сил UNMC отбили повстанцев. В статье также упоминаются несколько рассказов танкистов об эффективности их новых основных боевых танков, а также недавние наблюдения операторов MARSOC в АО. Этот конфликт стал одним из первых зарегистрированных случаев использования орбитальных бомбардировок в активных боевых действиях UNMC с участием UNS Omaha.
rmc-lore-examinable-boots-150 = Большая часть этого выпуска объясняет, что полевые рационы SPP не стандартизированы и производятся на местном уровне. Из-за этого захваченные и конфискованные рационы SPP включали некоторые странные продукты, такие как утиная печень, столетние яйца, лютефиск, маринованная свиная морда, консервированный рубец и обезвоженные закуски из засахаренного редиса.

rmc-lore-examinable-orrery-65 = Половину этого вопроса занимают слухи о том, что один из руководителей неправильно представил свой квартальный отчет о прибыли компании Danton's Perch в диспетчерское подразделение PMC. Далее следует статья для дебатов между двумя руководителями спецслужб по поводу создания колонии в системе Му Араэ. Дебаты сосредоточены вокруг местоположения колонии: один руководитель считает, что колония должна представлять собой суборбитальный сборщик газа вокруг газового гиганта, в то время как другой считает, что она должна быть расположена на зеленой луне газового гиганта. В середине дебатов оба руководителя, похоже, теряют самообладание и начинают оскорблять. После этого остальная часть статьи, похоже, подвергается жесткой цензуре.
rmc-lore-examinable-orrery-175 = В центре номера — рассказ о создании нового корабля для ВМФ, призванного не только выдерживать всевозможные повреждения и атаки, но и обладать достаточной огневой мощью, чтобы уничтожить целый город. В статье объясняется, что это совместный проект TSE и Weston-Yamada, а также даются интервью различным инженерам WeYa и Imperial, работающим на корабле. Хотя никакой конфиденциальной информации внутри не содержится, неоднократное упоминание о рельсотронах, лазерах тройной точечной защиты и комплекте ракетных орудий дает вам хорошее представление о силе корабля.
rmc-lore-examinable-orrery-184 = В этом специальном выпуске рассказывается о нескольких различных проектах, реализуемых корпорацией Weston-Yamada, которые были одобрены для публикации в прессе акционерами и директором подразделения. Известные проекты включают в себя смесительный блок UY-21 Weston-Yamada (который устраняет склонность UY-20 к взрыву при нагревании), «прототип портативного тяжелого шахтного лазера», предназначенный для резки камней, как масло, и систему ПЗРК Weston-Yamada (обозначенную как «ТАЙФУН EK-403»), предназначенную для использования ЧВК. В середине номера журнал предлагает купон «Купи один, получи один в подарок» на пачку пива Sequoia; Похоже, что срок его действия истек на следующий день после публикации выпуска.
rmc-lore-examinable-orrery-34 = Большая часть этого выпуска посвящена широкому ассортименту различных вариантов одежды, которые в настоящее время популярны среди руководителей Weston-Yamada по всей галактике и по регионам. Выбор одежды внутреннего обода выглядит несколько бросающимся в глаза, но стильным и привлекательным. В этом разделе преобладают элегантные костюмы с четырехзначными ценниками, а также яркие галстуки. Однако ближе к границе общий выбор расширяется: от толстых курток, способных с легкостью противостоять холодному фронту, до модных шорт, способных сохранять прохладу трудолюбивых руководителей в знойном климате. В статье также упоминаются усилия R&D по переосмыслению и улучшению классических «We-Ya Stompers».
rmc-lore-examinable-orrery-202 = Основное внимание в этом выпуске уделяется синтетической программе Weston-Yamada, в частности тому, как внедрение синтетики третьего поколения было, по общему мнению, чрезвычайно успешным. Он противопоставляет недостатки предыдущих поколений 2, такие как их несколько хрупкая конструкция, а также их привычка к сбоям в работе, с достижениями, достигнутыми программой поколения 3, которая утверждает, что исправляет указанные проблемы, поднимая планку для будущих синтетических проектов. Это также объясняет, как внедрение увеличило цену акций WEYA на 4% и что многие страны и организации инвестировали в синтезаторы третьего поколения, такие как TSE, ООН и полицейские агентства, такие как CMP и TSEPA.
rmc-lore-examinable-orrery-217 = В этом выпуске основное внимание уделяется активам частной военной компании Silverguard компании Weston-Yamada, таким как AZURE-15. Эти наемники, дислоцированные в различных зонах для обеспечения безопасности, защиты или приобретения корпоративных активов, полностью работают на зарплату Уэстон-Ямада, обучены и оснащены снаряжением на уровне многих официальных вооруженных сил. Упоминаются такое оружие, как SSG-45 и M80, а также современная броня. Далее обсуждается успех развертывания ЧВК в подавлении ячеек мешалок CLF, а также обеспечении безопасности активов WEYA от враждебных сил. В середине журнала в небольшой статье говорится о потенциальном понижении в должности руководителя спецслужб после того, как они не сообщили своему начальству о крупномасштабной промышленной аварии, которую они курировали.
rmc-lore-examinable-orrery-220 = Большая часть этого вопроса сосредоточена на недавних проблемах, с которыми столкнулось логистическое подразделение Уэстон-Ямада, особенно на границе с Зайфероном. В нем говорится о том, как недавняя напряженность между UN/TSE и SPP, а также беспорядки, вызванные CLF, повлияли на цепочку поставок Компании, например, увеличили стоимость потребительских товаров, а также сократили количество жизнеспособных портов для пополнения запасов и дозаправки. Тем не менее, в нем обсуждаются текущие планы по решению этой проблемы и минимизации затрат, такие как строительство дополнительных складов снабжения в ключевых местах, таких как OCP-583, и углубление торговых потоков с заинтересованными организациями, такими как ООН и TSE. В нем также обсуждаются новейшие возможности транспортных судов, способных перевозить пятьдесят тысяч транспортных контейнеров по всей галактике.
rmc-lore-examinable-orrery-258 = В этом выпуске обсуждаются усилия по созданию колонии в Среднем Кольце, на мире с умеренным климатом LV-676. Первоначально эта планета рассматривалась как возможное место для колонии, но только в последнее время стали рассматриваться планы колонизации планеты. После собрания акционеров 2102 года компания Weston-Yamada Special Services получила добро на начало колонизации. Первоначально состоявшие из 234 сотрудников и двух синтетиков, они заявили о своих правах и назвали планету «Форт Денст». Первоначальные усилия оказались трудными; Сложная местность, сломанные водоочистители и сильный ветер привели к жертвам и ранениям. Однако жители Форта Денста держались и упорствовали; в настоящее время в колонии проживает 1430 человек, и она славится экспортом сыра.

rmc-lore-examinable-weya-windbreaker = В результате 7-летней программы исследований и разработок эта ветровка отличается улучшенной регулировкой температуры, удобным дизайном и гидрофобным внешним видом, что делает ее идеальной практически для любой погоды. К сожалению, никто не догадался дать ему капот.
rmc-lore-examinable-atmospheric-composition-scanner = Портативное сверхмощное оборудование, способное собирать информацию о местных атмосферных данных, а также информацию с использованием передовых технологий, которую WEYA R&D стремится сохранить в секрете. Используется по всей галактике для множества целей, таких как поиск утечек газа, обеспечение прогресса в терраформировании и сбор научных данных об окрестностях экзопланет. Это устройство используется в WEYA, TSE и UN с 2078 года с очень небольшими изменениями и известно своей надежностью, особенно в более суровых условиях.

rmc-lore-examinable-spp-survival-ration = Они производятся массово в качестве экстренного рациона, они доступны в изобилии повсюду у прогрессивных народов и содержат питательные добавки. Они являются обычным явлением в рационе многих граждан народов, которые едят их из соображений удобства вместо более ароматных питательных батончиков или в качестве пищевых добавок к блюдам. Несмотря на популярные в ООН мифы, они не являются стандартным MRE морской пехоты СПП, но используются в сценариях, когда фактические запасы MRE исчерпаны, как и следовало ожидать от продовольствия для выживания.

rmc-lore-examinable-m13-extended-recoil-compensator = Дульное устройство ограниченной серии, разработанное компанией AEGIS Armaments. Компенсатор направляет дульные газы для противодействия отдаче и слегка увеличивает скорость пули за счет направленного давления, незначительно улучшая баллистические характеристики.

# Missing entries synced from en-US

rmc-lore-examinable-bug-juice = Протеиновый напиток «Bug Juice», чаще называемый «Bug Juice», представляет собой недорогой и калорийный напиток, приготовленный из выращенных и обработанных насекомых, таких как тараканы, мучные черви и жуки. Предлагаемый различными производителями сок Bug Juice упаковывается в картонные коробки и бутылки и широко потребляется на Фронтире. Он классифицируется как напиток и пищевой продукт и является источником белка и воды.

rmc-lore-examinable-soylent = Первоначально разработанный в 2173 году как заменитель еды для высокоинтенсивных работников, MRD несколько раз отзывался с рынка из-за сообщений о желудочно-кишечных заболеваниях, включая тошноту, рвоту и диарею. Была создана улучшенная формула, но торговая марка уже была испорчена, поэтому теперь напиток остается в качестве запаса продуктов питания для внутреннего использования Компании.
